tables:
  Test_02_Sum:
    validations:
      data_validation:
        source: athena
        report_tile: Revenue By Type or Revenue By Types - Table
        test_case: Test_002_Sum
        summary: Compare total revenue for each types in the last 24 months
        sourcecolumn: facility_id,report_month,types
        sourcequery: "SELECT
                      COALESCE(NULLIF(TRIM(CAST(facility_id AS VARCHAR)), ''), '_NULL_VALUE_') AS facility_id,
                      COALESCE(DATE_FORMAT(CAST(DATE_TRUNC('month', report_date) AS DATE), '%Y-%m'), '_NULL_VALUE_') AS report_month,
                      COALESCE(NULLIF(LOWER(TRIM(CAST(types AS VARCHAR))), ''), '_NULL_VALUE_') AS types,
                      COALESCE(CAST(CAST(COALESCE(ROUND(SUM(rev_amount_today), 2), 0) AS DECIMAL(18,2)) AS VARCHAR), '_NULL_VALUE_') AS rev_amount_today
                      FROM stodl_reporting_prod.sefms_management_summary_final_report_iceberg
                      WHERE report_date >= DATE_ADD('month', -24, DATE_TRUNC('month', CURRENT_DATE))
                      AND report_section = 'revenue_report'
                      GROUP BY 1, 2, 3
                      ORDER BY 2 DESC, 1, 3;"
        target: snowflake
        targetcolumn: facility_id,report_month,types
        targetquery: "SELECT
                      COALESCE(NULLIF(TRIM(CAST(f.facility_id AS VARCHAR)), ''), '_NULL_VALUE_') AS facility_id,
                      COALESCE(TO_CHAR(CAST(DATE_TRUNC('month', r.report_date) AS DATE), 'YYYY-MM'), '_NULL_VALUE_') AS report_month,
                      COALESCE(NULLIF(LOWER(TRIM(CAST(r.types AS VARCHAR))), ''), '_NULL_VALUE_') AS types,
                      CAST(COALESCE(ROUND(SUM(r.amount_today), 2), 0) AS NUMBER(18,2)) AS rev_amount_today
                      FROM DEV_GOLD.CORE.FACT_REVENUE_DAILY r
                      JOIN DEV_GOLD.DIM.DIM_FACILITY f
                      ON r.facility_key = f.facility_key
                      AND f.is_active = TRUE
                      WHERE r.report_date >= DATEADD(month, -24, DATE_TRUNC('month', CURRENT_DATE))
                        AND r.report_date <  DATEADD(month, 1, DATE_TRUNC('month', CURRENT_DATE))
                        AND r.report_section = 'revenue_report'
                        AND r.platform_source = 'EDGE'
                      GROUP BY 1, 2, 3
                    ORDER BY 2 DESC, 1, 3;"
