tables:
  account_balance_taxes:
    validations:
      data_validation:
        source_table_name: account_balance_taxes
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(t.account_balance_id AS TEXT),'<<NULL>>') AS account_balance_id,
              COALESCE(CAST(t.tax_rate_id AS TEXT),'<<NULL>>') AS tax_rate_id,
              COALESCE(CAST(CAST(t.amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              COALESCE(CAST(CAST(t.rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS rate,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code
          FROM public.account_balance_taxes t
          WHERE t.created_at >= '2026-08-01';
        target_table_name: account_balance_taxes
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.account_balance_id),'<<NULL>>') AS account_balance_id,
              COALESCE(TO_VARCHAR(t.tax_rate_id),'<<NULL>>') AS tax_rate_id,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              COALESCE(TO_VARCHAR(t.rate),'<<NULL>>') AS rate,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.account_balance_taxes t
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.created_at >= '2026-08-01'
