tables:
  account_codes:
    validations:
      data_validation:
        source_table_name: account_codes
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(code),'<<NULL>>') AS code,
              COALESCE(TRIM(description),'<<NULL>>') AS description,
              COALESCE(TRIM(category),'<<NULL>>') AS category,
              COALESCE(TRIM(subcategory),'<<NULL>>') AS subcategory,
              CASE WHEN deleted IS NULL THEN '<<NULL>>' WHEN deleted IS TRUE THEN 'TRUE' WHEN deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(internal_code),'<<NULL>>') AS internal_code,
              CASE WHEN locked IS NULL THEN '<<NULL>>' WHEN locked IS TRUE THEN 'TRUE' WHEN locked IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS locked,
              COALESCE(TRIM(internal_description),'<<NULL>>') AS internal_description,
              COALESCE(CAST(company_id AS TEXT),'<<NULL>>') AS company_id,
              COALESCE(CAST(account_code_set_id AS TEXT),'<<NULL>>') AS account_code_set_id,
              CASE WHEN pass_through IS NULL THEN '<<NULL>>' WHEN pass_through IS TRUE THEN 'TRUE' WHEN pass_through IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS pass_through
          FROM public.account_codes
          ;
        target_table_name: account_codes
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.code),'<<NULL>>') AS code,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TRIM(t.category),'<<NULL>>') AS category,
              COALESCE(TRIM(t.subcategory),'<<NULL>>') AS subcategory,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.internal_code),'<<NULL>>') AS internal_code,
              CASE WHEN t.locked IS NULL THEN '<<NULL>>' WHEN t.locked = TRUE THEN 'TRUE' WHEN t.locked = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS locked,
              COALESCE(TRIM(t.internal_description),'<<NULL>>') AS internal_description,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              COALESCE(TO_VARCHAR(t.account_code_set_id),'<<NULL>>') AS account_code_set_id,
              CASE WHEN t.pass_through IS NULL THEN '<<NULL>>' WHEN t.pass_through = TRUE THEN 'TRUE' WHEN t.pass_through = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS pass_through
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.account_codes t
          WHERE t._FIVETRAN_ACTIVE = TRUE
