tables:
  account_balances:
    validations:
      data_validation:
        source_table_name: account_balances
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(CAST(t.amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              CASE WHEN t.resolved IS NULL THEN '<<NULL>>' WHEN t.resolved IS TRUE THEN 'TRUE' WHEN t.resolved IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS resolved,
              COALESCE(CAST(t.created_by_id AS TEXT),'<<NULL>>') AS created_by_id,
              COALESCE(CAST(t.accountable_id AS TEXT),'<<NULL>>') AS accountable_id,
              COALESCE(TRIM(t.accountable_type),'<<NULL>>') AS accountable_type,
              COALESCE(CAST(t.tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(TO_CHAR(t.effective_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS effective_on,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TO_CHAR(t.resolved_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS resolved_on,
              COALESCE(CAST(CAST(t.subtotal AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS subtotal,
              CASE WHEN t.calculated_store IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.calculated_store) h) || '}', '{}') END AS calculated_store,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted IS TRUE THEN 'TRUE' WHEN t.deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(t.deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(CAST(CAST(t.amount_paid AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount_paid,
              COALESCE(TO_CHAR(t.paid_through_date,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS paid_through_date
          FROM public.account_balances t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01';
        target_table_name: account_balances
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_calculated_store AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.account_balances AS _flt
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
                   , TABLE(FLATTEN(INPUT => _flt.calculated_store, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.calculated_store) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND _flt.created_at >= '2025-08-01'
              GROUP BY _flt.id
          ),
          variant_calculated_store AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.calculated_store IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.calculated_store
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.calculated_store
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.calculated_store
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.calculated_store
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.calculated_store
                      ),

                      '<<NULL>>'

                  )

          END AS calculated_store
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.account_balances t
              LEFT JOIN obj_agg_calculated_store obj ON obj.id = t.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01'

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              CASE WHEN t.resolved IS NULL THEN '<<NULL>>' WHEN t.resolved = TRUE THEN 'TRUE' WHEN t.resolved = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS resolved,
              COALESCE(TO_VARCHAR(t.created_by_id),'<<NULL>>') AS created_by_id,
              COALESCE(TO_VARCHAR(t.accountable_id),'<<NULL>>') AS accountable_id,
              COALESCE(TRIM(t.accountable_type),'<<NULL>>') AS accountable_type,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_CHAR(t.effective_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS effective_on,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TO_CHAR(t.resolved_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS resolved_on,
              COALESCE(TO_VARCHAR(t.subtotal),'<<NULL>>') AS subtotal,
              v_calculated_store.calculated_store AS calculated_store,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_VARCHAR(t.amount_paid),'<<NULL>>') AS amount_paid,
              COALESCE(TO_CHAR(t.paid_through_date,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS paid_through_date
          FROM variant_calculated_store v_calculated_store LEFT JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.account_balances t ON v_calculated_store.id = t.id
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01'
