tables:
  addresses:
    validations:
      data_validation:
        source_table_name: addresses
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.type),'<<NULL>>') AS type,
              COALESCE(TRIM(t.address1),'<<NULL>>') AS address1,
              COALESCE(TRIM(t.address2),'<<NULL>>') AS address2,
              COALESCE(TRIM(t.city),'<<NULL>>') AS city,
              COALESCE(TRIM(t.state),'<<NULL>>') AS state,
              COALESCE(TRIM(t.postal),'<<NULL>>') AS postal,
              COALESCE(CAST(t.latitude AS TEXT),'<<NULL>>') AS latitude,
              COALESCE(CAST(t.longitude AS TEXT),'<<NULL>>') AS longitude,
              COALESCE(CAST(t.addressable_id AS TEXT),'<<NULL>>') AS addressable_id,
              COALESCE(TRIM(t.addressable_type),'<<NULL>>') AS addressable_type,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.country),'<<NULL>>') AS country,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.invalid_data IS NULL THEN '<<NULL>>' WHEN t.invalid_data IS TRUE THEN 'TRUE' WHEN t.invalid_data IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS invalid_data,
              COALESCE(TRIM(t.time_zone),'<<NULL>>') AS time_zone,
              COALESCE(TRIM(t.address_type),'<<NULL>>') AS address_type,
              CASE WHEN t."primary" IS NULL THEN '<<NULL>>' WHEN t."primary" IS TRUE THEN 'TRUE' WHEN t."primary" IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS "primary",
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted IS TRUE THEN 'TRUE' WHEN t.deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(t.deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.geocode_fingerprint),'<<NULL>>') AS geocode_fingerprint
          FROM public.addresses t
          JOIN public.facilities f ON t.addressable_id = f.id
          WHERE t.addressable_type = 'Facility';
        target_table_name: addresses
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.type),'<<NULL>>') AS type,
              COALESCE(TRIM(t.address1),'<<NULL>>') AS address1,
              COALESCE(TRIM(t.address2),'<<NULL>>') AS address2,
              COALESCE(TRIM(t.city),'<<NULL>>') AS city,
              COALESCE(TRIM(t.state),'<<NULL>>') AS state,
              COALESCE(TRIM(t.postal),'<<NULL>>') AS postal,
              COALESCE(TO_VARCHAR(t.latitude),'<<NULL>>') AS latitude,
              COALESCE(TO_VARCHAR(t.longitude),'<<NULL>>') AS longitude,
              COALESCE(TO_VARCHAR(t.addressable_id),'<<NULL>>') AS addressable_id,
              COALESCE(TRIM(t.addressable_type),'<<NULL>>') AS addressable_type,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.country),'<<NULL>>') AS country,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.invalid_data IS NULL THEN '<<NULL>>' WHEN t.invalid_data = TRUE THEN 'TRUE' WHEN t.invalid_data = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS invalid_data,
              COALESCE(TRIM(t.time_zone),'<<NULL>>') AS time_zone,
              COALESCE(TRIM(t.address_type),'<<NULL>>') AS address_type,
              CASE WHEN t."PRIMARY" IS NULL THEN '<<NULL>>' WHEN t."PRIMARY" = TRUE THEN 'TRUE' WHEN t."PRIMARY" = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS "primary",
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.geocode_fingerprint),'<<NULL>>') AS geocode_fingerprint
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.addresses t
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.addressable_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.addressable_type = 'Facility'
