tables:
  companies:
    validations:
      data_validation:
        source_table_name: companies
        source: postgres
        sourcecolumn: id
        sourcequery: "SELECT\n    COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,\n \
          \   COALESCE(TRIM(name),'<<NULL>>') AS name,\n    COALESCE(TO_CHAR(created_at,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,\n    COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,\n    COALESCE(TRIM(payment_provider_name),'<<NULL>>')\
          \ AS payment_provider_name,\n    CASE WHEN payment_provider_data IS NULL\
          \ THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT)\
          \ || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(payment_provider_data)\
          \ h) || '}', '{}') END AS payment_provider_data,\n    COALESCE(UPPER(TRIM(CAST(uuid\
          \ AS TEXT))),'<<NULL>>') AS uuid,\n    COALESCE(CAST(customer_number AS\
          \ TEXT),'<<NULL>>') AS customer_number,\n    COALESCE(TO_CHAR(customer_since,'YYYY-MM-DD'),'<<NULL>>')\
          \ AS customer_since,\n    COALESCE(TRIM(contact_first),'<<NULL>>') AS contact_first,\n\
          \    COALESCE(TRIM(contact_last),'<<NULL>>') AS contact_last,\n    COALESCE(TRIM(contact_email),'<<NULL>>')\
          \ AS contact_email,\n    COALESCE(TRIM(notes),'<<NULL>>') AS notes,\n  \
          \  COALESCE(TRIM(contact_phone),'<<NULL>>') AS contact_phone,\n    COALESCE(TRIM(business_phone),'<<NULL>>')\
          \ AS business_phone,\n    CASE WHEN deleted IS NULL THEN '<<NULL>>' WHEN\
          \ deleted IS TRUE THEN 'TRUE' WHEN deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>'\
          \ END AS deleted,\n    COALESCE(TO_CHAR(deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>')\
          \ AS deleted_on,\n    COALESCE(CAST(deleted_by_id AS TEXT),'<<NULL>>') AS\
          \ deleted_by_id,\n    CASE WHEN data IS NULL THEN '<<NULL>>' ELSE COALESCE('{'\
          \ || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT),\
          \ ', ' ORDER BY h.key) FROM EACH(data) h) || '}', '{}') END AS data,\n \
          \   COALESCE(ARRAY_TO_JSON(tags)::TEXT,'<<NULL>>') AS tags,\n    COALESCE(TRIM(software_provider),'<<NULL>>')\
          \ AS software_provider,\n    COALESCE(TRIM(salesforce_account_id),'<<NULL>>')\
          \ AS salesforce_account_id\nFROM public.companies;"
        target_table_name: companies
        target: snowflake
        targetcolumn: id
        targetquery: "WITH\nobj_agg_payment_provider_data AS\n(\n    SELECT\n    \
          \    _flt.id AS id,\n        LISTAGG(\n            CASE\n              \
          \  WHEN f.key IS NULL THEN NULL\n                ELSE\n                \
          \    TO_JSON(TO_VARIANT(f.key::VARCHAR)) || ': ' ||\n                  \
          \  CASE\n                        WHEN f.value IS NULL THEN 'null'\n    \
          \                    WHEN IS_NULL_VALUE(f.value) THEN 'null'\n         \
          \               WHEN TYPEOF(f.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(f.value::VARCHAR))\n\
          \                        WHEN TYPEOF(f.value) = 'BOOLEAN' THEN LOWER(f.value::VARCHAR)\n\
          \                        WHEN TYPEOF(f.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER')\
          \ THEN f.value::VARCHAR\n                        ELSE TO_JSON(f.value)\n\
          \                    END\n            END, ', ') WITHIN GROUP (ORDER BY\
          \ f.key) AS obj_body\n    FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ AS _flt,\n         TABLE(FLATTEN(INPUT => _flt.payment_provider_data,\
          \ RECURSIVE => FALSE)) f\n    WHERE _flt._FIVETRAN_ACTIVE = TRUE\n     \
          \ AND TYPEOF(_flt.payment_provider_data) = 'OBJECT'\n      AND _flt._FIVETRAN_ACTIVE\
          \ = TRUE\n    GROUP BY _flt.id\n),\nvariant_payment_provider_data AS\n(\n\
          \    SELECT\n        t.id AS id,\n        CASE\n\n    -- ======================================================\n\
          \    -- SQL NULL\n    -- ======================================================\n\
          \n    WHEN t.payment_provider_data IS NULL\n        THEN '<<NULL>>'\n\n\n\
          \    -- =====================================================\n    -- JSON\
          \ NULL\n    -- =====================================================\n\n\
          \    WHEN IS_NULL_VALUE(\n        t.payment_provider_data\n    )\n     \
          \   THEN 'null'\n\n\n    -- =====================================================\n\
          \    -- OBJECT\n    -- =====================================================\n\
          \n    WHEN TYPEOF(\n        t.payment_provider_data\n    ) = 'OBJECT'\n\n\
          \        THEN\n\n            CHR(123)\n\n            ||\n\n            COALESCE(COALESCE(obj.obj_body,\
          \ ''), '')\n\n            ||\n\n            CHR(125)\n\n\n    -- =====================================================\n\
          \    -- ARRAY\n    -- =====================================================\n\
          \n    WHEN TYPEOF(\n        t.payment_provider_data\n    ) = 'ARRAY'\n\n\
          \        THEN COALESCE(\n\n            TO_JSON(\n                t.payment_provider_data\n\
          \            ),\n\n            '[]'\n\n        )\n\n\n    -- =====================================================\n\
          \    -- SCALAR\n    -- =====================================================\n\
          \n    ELSE\n\n        COALESCE(\n\n            TO_JSON(\n              \
          \  t.payment_provider_data\n            ),\n\n            '<<NULL>>'\n\n\
          \        )\n\nEND AS payment_provider_data\n    FROM\n        DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ t\n    LEFT JOIN obj_agg_payment_provider_data obj ON obj.id = t.id\n\
          \    WHERE t._FIVETRAN_ACTIVE = TRUE\n\n),\nobj_agg_data AS\n(\n    SELECT\n\
          \        _flt.id AS id,\n        LISTAGG(\n            CASE\n          \
          \      WHEN f.key IS NULL THEN NULL\n                ELSE\n            \
          \        TO_JSON(TO_VARIANT(f.key::VARCHAR)) || ': ' ||\n              \
          \      CASE\n                        WHEN f.value IS NULL THEN 'null'\n\
          \                        WHEN IS_NULL_VALUE(f.value) THEN 'null'\n     \
          \                   WHEN TYPEOF(f.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(f.value::VARCHAR))\n\
          \                        WHEN TYPEOF(f.value) = 'BOOLEAN' THEN LOWER(f.value::VARCHAR)\n\
          \                        WHEN TYPEOF(f.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER')\
          \ THEN f.value::VARCHAR\n                        ELSE TO_JSON(f.value)\n\
          \                    END\n            END, ', ') WITHIN GROUP (ORDER BY\
          \ f.key) AS obj_body\n    FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ AS _flt,\n         TABLE(FLATTEN(INPUT => _flt.data, RECURSIVE => FALSE))\
          \ f\n    WHERE _flt._FIVETRAN_ACTIVE = TRUE\n      AND TYPEOF(_flt.data)\
          \ = 'OBJECT'\n      AND _flt._FIVETRAN_ACTIVE = TRUE\n    GROUP BY _flt.id\n\
          ),\nvariant_data AS\n(\n    SELECT\n        t.id AS id,\n        CASE\n\n\
          \    -- ======================================================\n    -- SQL\
          \ NULL\n    -- ======================================================\n\n\
          \    WHEN t.data IS NULL\n        THEN '<<NULL>>'\n\n\n    -- =====================================================\n\
          \    -- JSON NULL\n    -- =====================================================\n\
          \n    WHEN IS_NULL_VALUE(\n        t.data\n    )\n        THEN 'null'\n\n\
          \n    -- =====================================================\n    -- OBJECT\n\
          \    -- =====================================================\n\n    WHEN\
          \ TYPEOF(\n        t.data\n    ) = 'OBJECT'\n\n        THEN\n\n        \
          \    CHR(123)\n\n            ||\n\n            COALESCE(COALESCE(obj.obj_body,\
          \ ''), '')\n\n            ||\n\n            CHR(125)\n\n\n    -- =====================================================\n\
          \    -- ARRAY\n    -- =====================================================\n\
          \n    WHEN TYPEOF(\n        t.data\n    ) = 'ARRAY'\n\n        THEN COALESCE(\n\
          \n            TO_JSON(\n                t.data\n            ),\n\n     \
          \       '[]'\n\n        )\n\n\n    -- =====================================================\n\
          \    -- SCALAR\n    -- =====================================================\n\
          \n    ELSE\n\n        COALESCE(\n\n            TO_JSON(\n              \
          \  t.data\n            ),\n\n            '<<NULL>>'\n\n        )\n\nEND\
          \ AS data\n    FROM\n        DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ t\n    LEFT JOIN obj_agg_data obj ON obj.id = t.id\n    WHERE t._FIVETRAN_ACTIVE\
          \ = TRUE\n\n),\nobj_agg_tags AS\n(\n    SELECT\n        _flt.id AS id,\n\
          \        LISTAGG(\n            CASE\n                WHEN f.key IS NULL\
          \ THEN NULL\n                ELSE\n                    TO_JSON(TO_VARIANT(f.key::VARCHAR))\
          \ || ': ' ||\n                    CASE\n                        WHEN f.value\
          \ IS NULL THEN 'null'\n                        WHEN IS_NULL_VALUE(f.value)\
          \ THEN 'null'\n                        WHEN TYPEOF(f.value) = 'VARCHAR'\
          \ THEN TO_JSON(TO_VARIANT(f.value::VARCHAR))\n                        WHEN\
          \ TYPEOF(f.value) = 'BOOLEAN' THEN LOWER(f.value::VARCHAR)\n           \
          \             WHEN TYPEOF(f.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER')\
          \ THEN f.value::VARCHAR\n                        ELSE TO_JSON(f.value)\n\
          \                    END\n            END, ', ') WITHIN GROUP (ORDER BY\
          \ f.key) AS obj_body\n    FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ AS _flt,\n         TABLE(FLATTEN(INPUT => _flt.tags, RECURSIVE => FALSE))\
          \ f\n    WHERE _flt._FIVETRAN_ACTIVE = TRUE\n      AND TYPEOF(_flt.tags)\
          \ = 'OBJECT'\n      AND _flt._FIVETRAN_ACTIVE = TRUE\n    GROUP BY _flt.id\n\
          ),\nvariant_tags AS\n(\n    SELECT\n        t.id AS id,\n        CASE\n\n\
          \    -- ======================================================\n    -- SQL\
          \ NULL\n    -- ======================================================\n\n\
          \    WHEN t.tags IS NULL\n        THEN '<<NULL>>'\n\n\n    -- =====================================================\n\
          \    -- JSON NULL\n    -- =====================================================\n\
          \n    WHEN IS_NULL_VALUE(\n        t.tags\n    )\n        THEN 'null'\n\n\
          \n    -- =====================================================\n    -- OBJECT\n\
          \    -- =====================================================\n\n    WHEN\
          \ TYPEOF(\n        t.tags\n    ) = 'OBJECT'\n\n        THEN\n\n        \
          \    CHR(123)\n\n            ||\n\n            COALESCE(COALESCE(obj.obj_body,\
          \ ''), '')\n\n            ||\n\n            CHR(125)\n\n\n    -- =====================================================\n\
          \    -- ARRAY\n    -- =====================================================\n\
          \n    WHEN TYPEOF(\n        t.tags\n    ) = 'ARRAY'\n\n        THEN COALESCE(\n\
          \n            TO_JSON(\n                t.tags\n            ),\n\n     \
          \       '[]'\n\n        )\n\n\n    -- =====================================================\n\
          \    -- SCALAR\n    -- =====================================================\n\
          \n    ELSE\n\n        COALESCE(\n\n            TO_JSON(\n              \
          \  t.tags\n            ),\n\n            '<<NULL>>'\n\n        )\n\nEND\
          \ AS tags\n    FROM\n        DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ t\n    LEFT JOIN obj_agg_tags obj ON obj.id = t.id\n    WHERE t._FIVETRAN_ACTIVE\
          \ = TRUE\n\n)\nSELECT\n    COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,\n\
          \    COALESCE(TRIM(t.name),'<<NULL>>') AS name,\n    COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,\n    COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,\n    COALESCE(TRIM(t.payment_provider_name),'<<NULL>>')\
          \ AS payment_provider_name,\n    v_payment_provider_data.payment_provider_data\
          \ AS payment_provider_data,\n    COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,\n\
          \    COALESCE(TO_VARCHAR(t.customer_number),'<<NULL>>') AS customer_number,\n\
          \    COALESCE(TO_CHAR(t.customer_since,'YYYY-MM-DD'),'<<NULL>>') AS customer_since,\n\
          \    COALESCE(TRIM(t.contact_first),'<<NULL>>') AS contact_first,\n    COALESCE(TRIM(t.contact_last),'<<NULL>>')\
          \ AS contact_last,\n    COALESCE(TRIM(t.contact_email),'<<NULL>>') AS contact_email,\n\
          \    COALESCE(TRIM(t.notes),'<<NULL>>') AS notes,\n    COALESCE(TRIM(t.contact_phone),'<<NULL>>')\
          \ AS contact_phone,\n    COALESCE(TRIM(t.business_phone),'<<NULL>>') AS\
          \ business_phone,\n    CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN\
          \ t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE\
          \ '<<NULL>>' END AS deleted,\n    COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,\n    COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>')\
          \ AS deleted_by_id,\n    v_data.data AS data,\n    v_tags.tags AS tags,\n\
          \    COALESCE(TRIM(t.software_provider),'<<NULL>>') AS software_provider,\n\
          \    COALESCE(TRIM(t.salesforce_account_id),'<<NULL>>') AS salesforce_account_id\n\
          FROM variant_tags v_tags LEFT JOIN variant_data v_data LEFT JOIN variant_payment_provider_data\
          \ v_payment_provider_data LEFT JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.companies\
          \ t ON v_payment_provider_data.id = t.id ON v_data.id = t.id ON v_tags.id\
          \ = t.id\nWHERE t._FIVETRAN_ACTIVE = TRUE"
