tables:
  contacts:
    validations:
      data_validation:
        source_table_name: contacts
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.first_name),'<<NULL>>') AS first_name,
              COALESCE(TRIM(t.last_name),'<<NULL>>') AS last_name,
              COALESCE(TRIM(t.middle_initial),'<<NULL>>') AS middle_initial,
              CASE WHEN t.deletable IS NULL THEN '<<NULL>>' WHEN t.deletable IS TRUE THEN 'TRUE' WHEN t.deletable IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deletable,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted IS TRUE THEN 'TRUE' WHEN t.deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(t.deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(CAST(t.tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TRIM(t.title),'<<NULL>>') AS title,
              COALESCE(TRIM(t.email),'<<NULL>>') AS email,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(CAST(t.primary_phone_number_id AS TEXT),'<<NULL>>') AS primary_phone_number_id,
              CASE WHEN t.opt_in_to_transactional_sms IS NULL THEN '<<NULL>>' WHEN t.opt_in_to_transactional_sms IS TRUE THEN 'TRUE' WHEN t.opt_in_to_transactional_sms IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS opt_in_to_transactional_sms,
              CASE WHEN t.opt_in_to_marketing_sms IS NULL THEN '<<NULL>>' WHEN t.opt_in_to_marketing_sms IS TRUE THEN 'TRUE' WHEN t.opt_in_to_marketing_sms IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS opt_in_to_marketing_sms,
              CASE WHEN t.opt_in_to_marketing_emails IS NULL THEN '<<NULL>>' WHEN t.opt_in_to_marketing_emails IS TRUE THEN 'TRUE' WHEN t.opt_in_to_marketing_emails IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS opt_in_to_marketing_emails,
              CASE WHEN t.email_invoices IS NULL THEN '<<NULL>>' WHEN t.email_invoices IS TRUE THEN 'TRUE' WHEN t.email_invoices IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS email_invoices,
              CASE WHEN t.delinquency_docs_by_email IS NULL THEN '<<NULL>>' WHEN t.delinquency_docs_by_email IS TRUE THEN 'TRUE' WHEN t.delinquency_docs_by_email IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS delinquency_docs_by_email,
              CASE WHEN t.receive_legal_notices_by_email IS NULL THEN '<<NULL>>' WHEN t.receive_legal_notices_by_email IS TRUE THEN 'TRUE' WHEN t.receive_legal_notices_by_email IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS receive_legal_notices_by_email,
              COALESCE(UPPER(TRIM(CAST(t.deleted_by_uuid AS TEXT))),'<<NULL>>') AS deleted_by_uuid,
              COALESCE(UPPER(TRIM(CAST(t.primary_phone_number_uuid AS TEXT))),'<<NULL>>') AS primary_phone_number_uuid,
              COALESCE(UPPER(TRIM(CAST(t.tenant_uuid AS TEXT))),'<<NULL>>') AS tenant_uuid
          FROM public.contacts t
          JOIN public.tenants t1 ON t.tenant_id = t1.id
              JOIN public.facilities f ON t1.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: contacts
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.first_name),'<<NULL>>') AS first_name,
              COALESCE(TRIM(t.last_name),'<<NULL>>') AS last_name,
              COALESCE(TRIM(t.middle_initial),'<<NULL>>') AS middle_initial,
              CASE WHEN t.deletable IS NULL THEN '<<NULL>>' WHEN t.deletable = TRUE THEN 'TRUE' WHEN t.deletable = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deletable,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TRIM(t.title),'<<NULL>>') AS title,
              COALESCE(TRIM(t.email),'<<NULL>>') AS email,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_VARCHAR(t.primary_phone_number_id),'<<NULL>>') AS primary_phone_number_id,
              CASE WHEN t.opt_in_to_transactional_sms IS NULL THEN '<<NULL>>' WHEN t.opt_in_to_transactional_sms = TRUE THEN 'TRUE' WHEN t.opt_in_to_transactional_sms = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS opt_in_to_transactional_sms,
              CASE WHEN t.opt_in_to_marketing_sms IS NULL THEN '<<NULL>>' WHEN t.opt_in_to_marketing_sms = TRUE THEN 'TRUE' WHEN t.opt_in_to_marketing_sms = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS opt_in_to_marketing_sms,
              CASE WHEN t.opt_in_to_marketing_emails IS NULL THEN '<<NULL>>' WHEN t.opt_in_to_marketing_emails = TRUE THEN 'TRUE' WHEN t.opt_in_to_marketing_emails = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS opt_in_to_marketing_emails,
              CASE WHEN t.email_invoices IS NULL THEN '<<NULL>>' WHEN t.email_invoices = TRUE THEN 'TRUE' WHEN t.email_invoices = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS email_invoices,
              CASE WHEN t.delinquency_docs_by_email IS NULL THEN '<<NULL>>' WHEN t.delinquency_docs_by_email = TRUE THEN 'TRUE' WHEN t.delinquency_docs_by_email = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS delinquency_docs_by_email,
              CASE WHEN t.receive_legal_notices_by_email IS NULL THEN '<<NULL>>' WHEN t.receive_legal_notices_by_email = TRUE THEN 'TRUE' WHEN t.receive_legal_notices_by_email = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS receive_legal_notices_by_email,
              COALESCE(TRIM(t.deleted_by_uuid),'<<NULL>>') AS deleted_by_uuid,
              COALESCE(TRIM(t.primary_phone_number_uuid),'<<NULL>>') AS primary_phone_number_uuid,
              COALESCE(TRIM(t.tenant_uuid),'<<NULL>>') AS tenant_uuid
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.contacts t
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants t1 ON t.tenant_id = t1.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t1.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
