tables:
  delinquency_stage_actions:
    validations:
      data_validation:
        source_table_name: delinquency_stage_actions
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(delinquency_stage_id AS TEXT),'<<NULL>>') AS delinquency_stage_id,
              COALESCE(TRIM(name),'<<NULL>>') AS name,
              CASE WHEN params IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(params) h) || '}', '{}') END AS params,
              CASE WHEN deleted IS NULL THEN '<<NULL>>' WHEN deleted IS TRUE THEN 'TRUE' WHEN deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(CAST(invoiceable_item_id AS TEXT),'<<NULL>>') AS invoiceable_item_id,
              COALESCE(CAST(template_id AS TEXT),'<<NULL>>') AS template_id,
              COALESCE(CAST(sms_template_id AS TEXT),'<<NULL>>') AS sms_template_id,
              COALESCE(CAST(email_template_id AS TEXT),'<<NULL>>') AS email_template_id,
              COALESCE(CAST(mail_house_template_id AS TEXT),'<<NULL>>') AS mail_house_template_id,
              CASE WHEN require_file_upload IS NULL THEN '<<NULL>>' WHEN require_file_upload IS TRUE THEN 'TRUE' WHEN require_file_upload IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS require_file_upload
          FROM public.delinquency_stage_actions
          ;
        target_table_name: delinquency_stage_actions
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_params AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.delinquency_stage_actions AS _flt,
                   TABLE(FLATTEN(INPUT => _flt.params, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.params) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE
              GROUP BY _flt.id
          ),
          variant_params AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.params IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.params
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.params
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.params
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.params
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.params
                      ),

                      '<<NULL>>'

                  )

          END AS params
              FROM
                  DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.delinquency_stage_actions t
              LEFT JOIN obj_agg_params obj ON obj.id = t.id
              WHERE t._FIVETRAN_ACTIVE = TRUE

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.delinquency_stage_id),'<<NULL>>') AS delinquency_stage_id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              v_params.params AS params,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_VARCHAR(t.invoiceable_item_id),'<<NULL>>') AS invoiceable_item_id,
              COALESCE(TO_VARCHAR(t.template_id),'<<NULL>>') AS template_id,
              COALESCE(TO_VARCHAR(t.sms_template_id),'<<NULL>>') AS sms_template_id,
              COALESCE(TO_VARCHAR(t.email_template_id),'<<NULL>>') AS email_template_id,
              COALESCE(TO_VARCHAR(t.mail_house_template_id),'<<NULL>>') AS mail_house_template_id,
              CASE WHEN t.require_file_upload IS NULL THEN '<<NULL>>' WHEN t.require_file_upload = TRUE THEN 'TRUE' WHEN t.require_file_upload = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS require_file_upload
          FROM variant_params v_params LEFT JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.delinquency_stage_actions t ON v_params.id = t.id
          WHERE t._FIVETRAN_ACTIVE = TRUE
