tables:
  deposits:
    validations:
      data_validation:
        source_table_name: deposits
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(CAST(ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(CAST(unit_id AS TEXT),'<<NULL>>') AS unit_id,
              COALESCE(CAST(payable_balance_id AS TEXT),'<<NULL>>') AS payable_balance_id,
              COALESCE(TRIM(kind),'<<NULL>>') AS kind,
              COALESCE(CAST(CAST(amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              COALESCE(CAST(CAST(collected_amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS collected_amount,
              COALESCE(CAST(CAST(refunded_amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS refunded_amount,
              COALESCE(CAST(CAST(retained_amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS retained_amount,
              COALESCE(TO_CHAR(collected_on,'YYYY-MM-DD'),'<<NULL>>') AS collected_on,
              COALESCE(TO_CHAR(refunded_on,'YYYY-MM-DD'),'<<NULL>>') AS refunded_on,
              COALESCE(TO_CHAR(retained_on,'YYYY-MM-DD'),'<<NULL>>') AS retained_on,
              CASE WHEN refunded IS NULL THEN '<<NULL>>' WHEN refunded IS TRUE THEN 'TRUE' WHEN refunded IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS refunded,
              CASE WHEN retained IS NULL THEN '<<NULL>>' WHEN retained IS TRUE THEN 'TRUE' WHEN retained IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS retained,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(balance_entry_id AS TEXT))),'<<NULL>>') AS balance_entry_id
          FROM public.deposits
          ;
        target_table_name: deposits
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_VARCHAR(t.unit_id),'<<NULL>>') AS unit_id,
              COALESCE(TO_VARCHAR(t.payable_balance_id),'<<NULL>>') AS payable_balance_id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              COALESCE(TO_VARCHAR(t.collected_amount),'<<NULL>>') AS collected_amount,
              COALESCE(TO_VARCHAR(t.refunded_amount),'<<NULL>>') AS refunded_amount,
              COALESCE(TO_VARCHAR(t.retained_amount),'<<NULL>>') AS retained_amount,
              COALESCE(TO_CHAR(t.collected_on,'YYYY-MM-DD'),'<<NULL>>') AS collected_on,
              COALESCE(TO_CHAR(t.refunded_on,'YYYY-MM-DD'),'<<NULL>>') AS refunded_on,
              COALESCE(TO_CHAR(t.retained_on,'YYYY-MM-DD'),'<<NULL>>') AS retained_on,
              CASE WHEN t.refunded IS NULL THEN '<<NULL>>' WHEN t.refunded = TRUE THEN 'TRUE' WHEN t.refunded = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS refunded,
              CASE WHEN t.retained IS NULL THEN '<<NULL>>' WHEN t.retained = TRUE THEN 'TRUE' WHEN t.retained = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS retained,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.balance_entry_id),'<<NULL>>') AS balance_entry_id
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.deposits t
          WHERE t._FIVETRAN_ACTIVE = TRUE
