tables:
  discount_plan_ledger_instances:
    validations:
      data_validation:
        source_table_name: discount_plan_ledger_instances
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(t.discount_plan_id AS TEXT),'<<NULL>>') AS discount_plan_id,
              COALESCE(CAST(t.created_by_id AS TEXT),'<<NULL>>') AS created_by_id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TO_CHAR(t.start_date,'YYYY-MM-DD'),'<<NULL>>') AS start_date,
              COALESCE(TO_CHAR(t.end_date,'YYYY-MM-DD'),'<<NULL>>') AS end_date,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted IS TRUE THEN 'TRUE' WHEN t.deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(t.deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(CAST(t.min_occupancy_months AS TEXT),'<<NULL>>') AS min_occupancy_months,
              COALESCE(CAST(t.prepay_months AS TEXT),'<<NULL>>') AS prepay_months,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(CAST(t.round_to_nearest AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS round_to_nearest,
              COALESCE(CAST(CAST(t.variable_amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS variable_amount,
              COALESCE(TRIM(t.public_description),'<<NULL>>') AS public_description,
              CASE WHEN t.use_month_zero_schedule IS NULL THEN '<<NULL>>' WHEN t.use_month_zero_schedule IS TRUE THEN 'TRUE' WHEN t.use_month_zero_schedule IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS use_month_zero_schedule
          FROM public.discount_plan_ledger_instances t
          JOIN public.discount_plan_ledger_instances_line_items j ON j.discount_plan_ledger_instance_id = t.id
          WHERE t.created_at >= '2026-08-01';
        target_table_name: discount_plan_ledger_instances
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.discount_plan_id),'<<NULL>>') AS discount_plan_id,
              COALESCE(TO_VARCHAR(t.created_by_id),'<<NULL>>') AS created_by_id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TO_CHAR(t.start_date,'YYYY-MM-DD'),'<<NULL>>') AS start_date,
              COALESCE(TO_CHAR(t.end_date,'YYYY-MM-DD'),'<<NULL>>') AS end_date,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TO_VARCHAR(t.min_occupancy_months),'<<NULL>>') AS min_occupancy_months,
              COALESCE(TO_VARCHAR(t.prepay_months),'<<NULL>>') AS prepay_months,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.round_to_nearest),'<<NULL>>') AS round_to_nearest,
              COALESCE(TO_VARCHAR(t.variable_amount),'<<NULL>>') AS variable_amount,
              COALESCE(TRIM(t.public_description),'<<NULL>>') AS public_description,
              CASE WHEN t.use_month_zero_schedule IS NULL THEN '<<NULL>>' WHEN t.use_month_zero_schedule = TRUE THEN 'TRUE' WHEN t.use_month_zero_schedule = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS use_month_zero_schedule
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_plan_ledger_instances t
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_plan_ledger_instances_line_items j ON j.discount_plan_ledger_instance_id = t.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.created_at >= '2026-08-01'
