tables:
  discount_plan_ledger_instances_line_items:
    validations:
      data_validation:
        source_table_name: discount_plan_ledger_instances_line_items
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.discount_plan_ledger_instance_id AS TEXT),'<<NULL>>') AS discount_plan_ledger_instance_id,
              COALESCE(CAST(t.line_item_id AS TEXT),'<<NULL>>') AS line_item_id,
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id
          FROM public.discount_plan_ledger_instances_line_items t
          JOIN public.discount_plan_ledger_instances ss ON t.discount_plan_ledger_instance_id = ss.id
          WHERE ss.created_at >= '2026-08-01';
        target_table_name: discount_plan_ledger_instances_line_items
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.discount_plan_ledger_instance_id),'<<NULL>>') AS discount_plan_ledger_instance_id,
              COALESCE(TO_VARCHAR(t.line_item_id),'<<NULL>>') AS line_item_id,
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_plan_ledger_instances_line_items t
          JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_plan_ledger_instances ss ON t.discount_plan_ledger_instance_id = ss.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND ss.created_at >= '2026-08-01'
