tables:
  discount_lines:
    validations:
      data_validation:
        source_table_name: discount_lines
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(CAST(CAST(t.amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              COALESCE(CAST(CAST(t.discount_amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS discount_amount,
              COALESCE(CAST(CAST(t.original_subtotal AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS original_subtotal,
              COALESCE(TRIM(t.note),'<<NULL>>') AS note,
              COALESCE(TO_CHAR(t.discounted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS discounted_on,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(CAST(t.owner_id AS TEXT),'<<NULL>>') AS owner_id,
              COALESCE(TRIM(t.owner_type),'<<NULL>>') AS owner_type,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(CAST(t.discounted_by_id AS TEXT),'<<NULL>>') AS discounted_by_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(t.source AS TEXT),'<<NULL>>') AS source,
              CASE WHEN t.discount_amount_per_type IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.discount_amount_per_type) h) || '}', '{}') END AS discount_amount_per_type,
              CASE WHEN t.discount_amount_by_id IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.discount_amount_by_id) h) || '}', '{}') END AS discount_amount_by_id
          FROM public.discount_lines t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501) AND t.created_at >= '2024-08-01';
        target_table_name: discount_lines
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_discount_amount_per_type AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_lines AS _flt
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
                   , TABLE(FLATTEN(INPUT => _flt.discount_amount_per_type, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.discount_amount_per_type) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND _flt.created_at >= '2024-08-01'
              GROUP BY _flt.id
          ),
          variant_discount_amount_per_type AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.discount_amount_per_type IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.discount_amount_per_type
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.discount_amount_per_type
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.discount_amount_per_type
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.discount_amount_per_type
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.discount_amount_per_type
                      ),

                      '<<NULL>>'

                  )

          END AS discount_amount_per_type
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_lines t
              LEFT JOIN obj_agg_discount_amount_per_type obj ON obj.id = t.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2024-08-01'

          ),
          obj_agg_discount_amount_by_id AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_lines AS _flt
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
                   , TABLE(FLATTEN(INPUT => _flt.discount_amount_by_id, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.discount_amount_by_id) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND _flt.created_at >= '2024-08-01'
              GROUP BY _flt.id
          ),
          variant_discount_amount_by_id AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.discount_amount_by_id IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.discount_amount_by_id
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.discount_amount_by_id
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.discount_amount_by_id
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.discount_amount_by_id
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.discount_amount_by_id
                      ),

                      '<<NULL>>'

                  )

          END AS discount_amount_by_id
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_lines t
              LEFT JOIN obj_agg_discount_amount_by_id obj ON obj.id = t.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2024-08-01'

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              COALESCE(TO_VARCHAR(t.discount_amount),'<<NULL>>') AS discount_amount,
              COALESCE(TO_VARCHAR(t.original_subtotal),'<<NULL>>') AS original_subtotal,
              COALESCE(TRIM(t.note),'<<NULL>>') AS note,
              COALESCE(TO_CHAR(t.discounted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS discounted_on,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_VARCHAR(t.owner_id),'<<NULL>>') AS owner_id,
              COALESCE(TRIM(t.owner_type),'<<NULL>>') AS owner_type,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_VARCHAR(t.discounted_by_id),'<<NULL>>') AS discounted_by_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.source),'<<NULL>>') AS source,
              v_discount_amount_per_type.discount_amount_per_type AS discount_amount_per_type,
              v_discount_amount_by_id.discount_amount_by_id AS discount_amount_by_id
          FROM variant_discount_amount_by_id v_discount_amount_by_id LEFT JOIN variant_discount_amount_per_type v_discount_amount_per_type LEFT JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.discount_lines t ON v_discount_amount_per_type.id = t.id ON v_discount_amount_by_id.id = t.id
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2024-08-01'
