tables:
  facilities:
    validations:
      data_validation:
        source_table_name: facilities
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(name),'<<NULL>>') AS name,
              COALESCE(TRIM(phone),'<<NULL>>') AS phone,
              COALESCE(TRIM(time_zone),'<<NULL>>') AS time_zone,
              COALESCE(CAST(company_id AS TEXT),'<<NULL>>') AS company_id,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(phnkey_id_token),'<<NULL>>') AS phnkey_id_token,
              COALESCE(TRIM(phnkey_api_key),'<<NULL>>') AS phnkey_api_key,
              COALESCE(TRIM(phnkey_auth_token),'<<NULL>>') AS phnkey_auth_token,
              COALESCE(TRIM(payment_provider_name),'<<NULL>>') AS payment_provider_name,
              CASE WHEN payment_provider_data IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(payment_provider_data) h) || '}', '{}') END AS payment_provider_data,
              COALESCE(TRIM(tenant_portal_key),'<<NULL>>') AS tenant_portal_key,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN deleted IS NULL THEN '<<NULL>>' WHEN deleted IS TRUE THEN 'TRUE' WHEN deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(accounting_method),'<<NULL>>') AS accounting_method,
              COALESCE(TO_CHAR(last_exported_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_exported_on,
              COALESCE(TRIM(public_url),'<<NULL>>') AS public_url,
              CASE WHEN access_hours_same_as_office_hours IS NULL THEN '<<NULL>>' WHEN access_hours_same_as_office_hours IS TRUE THEN 'TRUE' WHEN access_hours_same_as_office_hours IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS access_hours_same_as_office_hours,
              COALESCE(TRIM(logo),'<<NULL>>') AS logo,
              COALESCE(TRIM(email),'<<NULL>>') AS email,
              COALESCE(TRIM(fax),'<<NULL>>') AS fax,
              COALESCE(TRIM(store_number),'<<NULL>>') AS store_number,
              COALESCE(TRIM(custom_portal_url),'<<NULL>>') AS custom_portal_url,
              COALESCE(TRIM(brand_name),'<<NULL>>') AS brand_name,
              COALESCE(TRIM(landmarks),'<<NULL>>') AS landmarks,
              COALESCE(CAST(max_truck_length AS TEXT),'<<NULL>>') AS max_truck_length,
              COALESCE(TRIM(direct_phone),'<<NULL>>') AS direct_phone,
              COALESCE(TRIM(notice),'<<NULL>>') AS notice,
              COALESCE(TRIM(sms_phone),'<<NULL>>') AS sms_phone,
              COALESCE(TRIM(pay_online_url),'<<NULL>>') AS pay_online_url,
              COALESCE(TRIM(click_to_call_phone),'<<NULL>>') AS click_to_call_phone,
              COALESCE(TRIM(rental_center_subdomain),'<<NULL>>') AS rental_center_subdomain,
              COALESCE(CAST(account_code_set_id AS TEXT),'<<NULL>>') AS account_code_set_id,
              COALESCE(TO_CHAR(last_close_of_day_happened_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_close_of_day_happened_at,
              COALESCE(CAST(facility_analytics_generation_frequency AS TEXT),'<<NULL>>') AS facility_analytics_generation_frequency,
              COALESCE(CAST(required_field_set_id AS TEXT),'<<NULL>>') AS required_field_set_id,
              COALESCE(TO_CHAR(next_analytics_generation_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS next_analytics_generation_at,
              COALESCE(CAST(secured_action_set_id AS TEXT),'<<NULL>>') AS secured_action_set_id,
              COALESCE(CAST(insurance_policy_id AS TEXT),'<<NULL>>') AS insurance_policy_id,
              COALESCE(TO_CHAR(hard_delete_start_time,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS hard_delete_start_time,
              COALESCE(TRIM(hard_delete_jid),'<<NULL>>') AS hard_delete_jid,
              COALESCE(TRIM(legal_entity),'<<NULL>>') AS legal_entity,
              COALESCE(TO_CHAR(abacus_conversion_date,'YYYY-MM-DD'),'<<NULL>>') AS abacus_conversion_date,
              COALESCE(TRIM(software_provider),'<<NULL>>') AS software_provider,
              COALESCE(TRIM(abacus_chart_of_account_type),'<<NULL>>') AS abacus_chart_of_account_type,
              COALESCE(TRIM(currency),'<<NULL>>') AS currency,
              COALESCE(TRIM(salesforce_asset_id),'<<NULL>>') AS salesforce_asset_id
          FROM public.facilities
          ;
        target_table_name: facilities
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_payment_provider_data AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities AS _flt
                   , TABLE(FLATTEN(INPUT => _flt.payment_provider_data, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.payment_provider_data) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE
              GROUP BY _flt.id
          ),
          variant_payment_provider_data AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.payment_provider_data IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.payment_provider_data
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.payment_provider_data
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.payment_provider_data
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.payment_provider_data
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.payment_provider_data
                      ),

                      '<<NULL>>'

                  )

          END AS payment_provider_data
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities t
              LEFT JOIN obj_agg_payment_provider_data obj ON obj.id = t.id
              WHERE t._FIVETRAN_ACTIVE = TRUE

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TRIM(t.phone),'<<NULL>>') AS phone,
              COALESCE(TRIM(t.time_zone),'<<NULL>>') AS time_zone,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.phnkey_id_token),'<<NULL>>') AS phnkey_id_token,
              COALESCE(TRIM(t.phnkey_api_key),'<<NULL>>') AS phnkey_api_key,
              COALESCE(TRIM(t.phnkey_auth_token),'<<NULL>>') AS phnkey_auth_token,
              COALESCE(TRIM(t.payment_provider_name),'<<NULL>>') AS payment_provider_name,
              v_payment_provider_data.payment_provider_data AS payment_provider_data,
              COALESCE(TRIM(t.tenant_portal_key),'<<NULL>>') AS tenant_portal_key,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.accounting_method),'<<NULL>>') AS accounting_method,
              COALESCE(TO_CHAR(t.last_exported_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_exported_on,
              COALESCE(TRIM(t.public_url),'<<NULL>>') AS public_url,
              CASE WHEN t.access_hours_same_as_office_hours IS NULL THEN '<<NULL>>' WHEN t.access_hours_same_as_office_hours = TRUE THEN 'TRUE' WHEN t.access_hours_same_as_office_hours = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS access_hours_same_as_office_hours,
              COALESCE(TRIM(t.logo),'<<NULL>>') AS logo,
              COALESCE(TRIM(t.email),'<<NULL>>') AS email,
              COALESCE(TRIM(t.fax),'<<NULL>>') AS fax,
              COALESCE(TRIM(t.store_number),'<<NULL>>') AS store_number,
              COALESCE(TRIM(t.custom_portal_url),'<<NULL>>') AS custom_portal_url,
              COALESCE(TRIM(t.brand_name),'<<NULL>>') AS brand_name,
              COALESCE(TRIM(t.landmarks),'<<NULL>>') AS landmarks,
              COALESCE(TO_VARCHAR(t.max_truck_length),'<<NULL>>') AS max_truck_length,
              COALESCE(TRIM(t.direct_phone),'<<NULL>>') AS direct_phone,
              COALESCE(TRIM(t.notice),'<<NULL>>') AS notice,
              COALESCE(TRIM(t.sms_phone),'<<NULL>>') AS sms_phone,
              COALESCE(TRIM(t.pay_online_url),'<<NULL>>') AS pay_online_url,
              COALESCE(TRIM(t.click_to_call_phone),'<<NULL>>') AS click_to_call_phone,
              COALESCE(TRIM(t.rental_center_subdomain),'<<NULL>>') AS rental_center_subdomain,
              COALESCE(TO_VARCHAR(t.account_code_set_id),'<<NULL>>') AS account_code_set_id,
              COALESCE(TO_CHAR(t.last_close_of_day_happened_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_close_of_day_happened_at,
              COALESCE(TO_VARCHAR(t.facility_analytics_generation_frequency),'<<NULL>>') AS facility_analytics_generation_frequency,
              COALESCE(TO_VARCHAR(t.required_field_set_id),'<<NULL>>') AS required_field_set_id,
              COALESCE(TO_CHAR(t.next_analytics_generation_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS next_analytics_generation_at,
              COALESCE(TO_VARCHAR(t.secured_action_set_id),'<<NULL>>') AS secured_action_set_id,
              COALESCE(TO_VARCHAR(t.insurance_policy_id),'<<NULL>>') AS insurance_policy_id,
              COALESCE(TO_CHAR(t.hard_delete_start_time,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS hard_delete_start_time,
              COALESCE(TRIM(t.hard_delete_jid),'<<NULL>>') AS hard_delete_jid,
              COALESCE(TRIM(t.legal_entity),'<<NULL>>') AS legal_entity,
              COALESCE(TO_CHAR(t.abacus_conversion_date,'YYYY-MM-DD'),'<<NULL>>') AS abacus_conversion_date,
              COALESCE(TRIM(t.software_provider),'<<NULL>>') AS software_provider,
              COALESCE(TRIM(t.abacus_chart_of_account_type),'<<NULL>>') AS abacus_chart_of_account_type,
              COALESCE(TRIM(t.currency),'<<NULL>>') AS currency,
              COALESCE(TRIM(t.salesforce_asset_id),'<<NULL>>') AS salesforce_asset_id
          FROM variant_payment_provider_data v_payment_provider_data LEFT JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities t ON v_payment_provider_data.id = t.id
          WHERE t._FIVETRAN_ACTIVE = TRUE
