tables:
  facilities_facility_groups:
    validations:
      data_validation:
        source_table_name: facilities_facility_groups
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(CAST(facility_group_id AS TEXT),'<<NULL>>') AS facility_group_id,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM public.facilities_facility_groups
          ;
        target_table_name: facilities_facility_groups
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_VARCHAR(t.facility_group_id),'<<NULL>>') AS facility_group_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities_facility_groups t
          WHERE t._FIVETRAN_ACTIVE = TRUE
