tables:
  facility_groups:
    validations:
      data_validation:
        source_table_name: facility_groups
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(group_name),'<<NULL>>') AS group_name,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(company_id AS TEXT),'<<NULL>>') AS company_id,
              COALESCE(CAST(updated_by_id AS TEXT),'<<NULL>>') AS updated_by_id
          FROM public.facility_groups
          ;
        target_table_name: facility_groups
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.group_name),'<<NULL>>') AS group_name,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              COALESCE(TO_VARCHAR(t.updated_by_id),'<<NULL>>') AS updated_by_id
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facility_groups t
          WHERE t._FIVETRAN_ACTIVE = TRUE
