tables:
  general_ledger_line_items:
    validations:
      data_validation:
        source_table_name: general_ledger_line_items
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(TO_CHAR(t.effective_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS effective_on,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(CAST(CAST(t.amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              COALESCE(CAST(t.account_balance_id AS TEXT),'<<NULL>>') AS account_balance_id,
              COALESCE(CAST(t.tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.reversal IS NULL THEN '<<NULL>>' WHEN t.reversal IS TRUE THEN 'TRUE' WHEN t.reversal IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS reversal,
              COALESCE(CAST(t.account_balance_item_id AS TEXT),'<<NULL>>') AS account_balance_item_id,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code,
              CASE WHEN t.daily_transaction IS NULL THEN '<<NULL>>' WHEN t.daily_transaction IS TRUE THEN 'TRUE' WHEN t.daily_transaction IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS daily_transaction,
              COALESCE(TRIM(t.transaction_type),'<<NULL>>') AS transaction_type,
              CASE WHEN t.hidden IS NULL THEN '<<NULL>>' WHEN t.hidden IS TRUE THEN 'TRUE' WHEN t.hidden IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS hidden,
              COALESCE(TRIM(t.reference_number),'<<NULL>>') AS reference_number,
              COALESCE(TRIM(t.display_code),'<<NULL>>') AS display_code,
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id
          FROM public.general_ledger_line_items t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501) AND t.created_at >= '2024-08-01';
        target_table_name: general_ledger_line_items
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_CHAR(t.effective_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS effective_on,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              COALESCE(TO_VARCHAR(t.account_balance_id),'<<NULL>>') AS account_balance_id,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.reversal IS NULL THEN '<<NULL>>' WHEN t.reversal = TRUE THEN 'TRUE' WHEN t.reversal = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS reversal,
              COALESCE(TO_VARCHAR(t.account_balance_item_id),'<<NULL>>') AS account_balance_item_id,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code,
              CASE WHEN t.daily_transaction IS NULL THEN '<<NULL>>' WHEN t.daily_transaction = TRUE THEN 'TRUE' WHEN t.daily_transaction = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS daily_transaction,
              COALESCE(TRIM(t.transaction_type),'<<NULL>>') AS transaction_type,
              CASE WHEN t.hidden IS NULL THEN '<<NULL>>' WHEN t.hidden = TRUE THEN 'TRUE' WHEN t.hidden = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS hidden,
              COALESCE(TRIM(t.reference_number),'<<NULL>>') AS reference_number,
              COALESCE(TRIM(t.display_code),'<<NULL>>') AS display_code,
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.general_ledger_line_items t
          JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2024-08-01'
