tables:
  invoiceable_amounts:
    validations:
      data_validation:
        source_table_name: invoiceable_amounts
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(t.invoiceable_id AS TEXT),'<<NULL>>') AS invoiceable_id,
              COALESCE(TRIM(t.invoiceable_type),'<<NULL>>') AS invoiceable_type,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(CAST(CAST(t.amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              COALESCE(CAST(CAST(t."limit" AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS "limit",
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.round_up IS NULL THEN '<<NULL>>' WHEN t.round_up IS TRUE THEN 'TRUE' WHEN t.round_up IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS round_up,
              COALESCE(CAST(CAST(t.round_to_nearest AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS round_to_nearest
          FROM public.invoiceable_amounts t
          WHERE t.created_at >= '2026-08-01';
        target_table_name: invoiceable_amounts
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.invoiceable_id),'<<NULL>>') AS invoiceable_id,
              COALESCE(TRIM(t.invoiceable_type),'<<NULL>>') AS invoiceable_type,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              COALESCE(TO_VARCHAR(t."limit"),'<<NULL>>') AS "limit",
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.round_up IS NULL THEN '<<NULL>>' WHEN t.round_up = TRUE THEN 'TRUE' WHEN t.round_up = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS round_up,
              COALESCE(TO_VARCHAR(t.round_to_nearest),'<<NULL>>') AS round_to_nearest
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.invoiceable_amounts t
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.created_at >= '2026-08-01'
