tables:
  leads:
    validations:
      data_validation:
        source_table_name: leads
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.caller_first_name),'<<NULL>>') AS caller_first_name,
              COALESCE(TRIM(t.caller_last_name),'<<NULL>>') AS caller_last_name,
              COALESCE(CAST(t.caller_phone_number_id AS TEXT),'<<NULL>>') AS caller_phone_number_id,
              COALESCE(CAST(t.tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(CAST(t.source_id AS TEXT),'<<NULL>>') AS source_id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TRIM(t.size),'<<NULL>>') AS size,
              COALESCE(CAST(t.floor AS TEXT),'<<NULL>>') AS floor,
              COALESCE(CAST(CAST(t.quoted_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS quoted_rate,
              COALESCE(TO_CHAR(t.desired_move_in_date,'YYYY-MM-DD'),'<<NULL>>') AS desired_move_in_date,
              CASE WHEN t.urgent IS NULL THEN '<<NULL>>' WHEN t.urgent IS TRUE THEN 'TRUE' WHEN t.urgent IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS urgent,
              CASE WHEN t.extra_details IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.extra_details) h) || '}', '{}') END AS extra_details,
              COALESCE(CAST(t.unit_id AS TEXT),'<<NULL>>') AS unit_id,
              COALESCE(TRIM(t.confirmation_number),'<<NULL>>') AS confirmation_number,
              COALESCE(CAST(t.unit_type_id AS TEXT),'<<NULL>>') AS unit_type_id,
              CASE WHEN t.reservation_fee_required IS NULL THEN '<<NULL>>' WHEN t.reservation_fee_required IS TRUE THEN 'TRUE' WHEN t.reservation_fee_required IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS reservation_fee_required,
              COALESCE(CAST(t.reservation_invoice_id AS TEXT),'<<NULL>>') AS reservation_invoice_id,
              COALESCE(CAST(t.reservation_fee_invoiceable_id AS TEXT),'<<NULL>>') AS reservation_fee_invoiceable_id,
              COALESCE(TO_CHAR(t.next_action_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS next_action_at,
              COALESCE(CAST(t.current_user_id AS TEXT),'<<NULL>>') AS current_user_id,
              CASE WHEN t.closed IS NULL THEN '<<NULL>>' WHEN t.closed IS TRUE THEN 'TRUE' WHEN t.closed IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS closed,
              CASE WHEN t.wait_list IS NULL THEN '<<NULL>>' WHEN t.wait_list IS TRUE THEN 'TRUE' WHEN t.wait_list IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS wait_list,
              COALESCE(TRIM(t.status),'<<NULL>>') AS status,
              COALESCE(TO_CHAR(t.reserved_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS reserved_at,
              COALESCE(TO_CHAR(t.moved_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS moved_in_at,
              COALESCE(TO_CHAR(t.cancelled_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS cancelled_at,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(CAST(t.company_id AS TEXT),'<<NULL>>') AS company_id,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.next_lead_action),'<<NULL>>') AS next_lead_action,
              CASE WHEN t.lead_action_data IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.lead_action_data) h) || '}', '{}') END AS lead_action_data,
              CASE WHEN t.move_in_started IS NULL THEN '<<NULL>>' WHEN t.move_in_started IS TRUE THEN 'TRUE' WHEN t.move_in_started IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS move_in_started,
              CASE WHEN t.missed_move_in IS NULL THEN '<<NULL>>' WHEN t.missed_move_in IS TRUE THEN 'TRUE' WHEN t.missed_move_in IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS missed_move_in,
              CASE WHEN t.needs_closing IS NULL THEN '<<NULL>>' WHEN t.needs_closing IS TRUE THEN 'TRUE' WHEN t.needs_closing IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS needs_closing,
              COALESCE(CAST(t.close_reason_id AS TEXT),'<<NULL>>') AS close_reason_id,
              COALESCE(CAST(t.length_of_stay_id AS TEXT),'<<NULL>>') AS length_of_stay_id,
              COALESCE(TRIM(t.most_recent_action_performed),'<<NULL>>') AS most_recent_action_performed,
              COALESCE(TRIM(t.next_action_to_perform),'<<NULL>>') AS next_action_to_perform,
              CASE WHEN t.confirmed IS NULL THEN '<<NULL>>' WHEN t.confirmed IS TRUE THEN 'TRUE' WHEN t.confirmed IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS confirmed,
              CASE WHEN t.wait_list_available IS NULL THEN '<<NULL>>' WHEN t.wait_list_available IS TRUE THEN 'TRUE' WHEN t.wait_list_available IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS wait_list_available,
              COALESCE(TO_CHAR(t.started_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS started_at,
              CASE WHEN t.appointment IS NULL THEN '<<NULL>>' WHEN t.appointment IS TRUE THEN 'TRUE' WHEN t.appointment IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS appointment,
              COALESCE(CAST(CAST(t.standard_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS standard_rate,
              COALESCE(TRIM(t.origination),'<<NULL>>') AS origination,
              COALESCE(TRIM(t.origination_platform),'<<NULL>>') AS origination_platform,
              COALESCE(CAST(t.originating_client_application_id AS TEXT),'<<NULL>>') AS originating_client_application_id,
              COALESCE(TO_CHAR(t.last_online_move_in_action_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_online_move_in_action_at,
              COALESCE(TO_CHAR(t.abandoned_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS abandoned_at,
              COALESCE(CAST(t.transferred_from_lead_id AS TEXT),'<<NULL>>') AS transferred_from_lead_id
          FROM public.leads t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: leads
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_extra_details AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.leads AS _flt,
                   TABLE(FLATTEN(INPUT => _flt.extra_details, RECURSIVE => FALSE)) flt_kv
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.extra_details) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
              GROUP BY _flt.id
          ),
          variant_extra_details AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.extra_details IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.extra_details
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.extra_details
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.extra_details
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.extra_details
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.extra_details
                      ),

                      '<<NULL>>'

                  )

          END AS extra_details
              FROM
                  DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.leads t
              LEFT JOIN obj_agg_extra_details obj ON obj.id = t.id
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)

          ),
          obj_agg_lead_action_data AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.leads AS _flt,
                   TABLE(FLATTEN(INPUT => _flt.lead_action_data, RECURSIVE => FALSE)) flt_kv
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.lead_action_data) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
              GROUP BY _flt.id
          ),
          variant_lead_action_data AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.lead_action_data IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.lead_action_data
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.lead_action_data
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.lead_action_data
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.lead_action_data
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.lead_action_data
                      ),

                      '<<NULL>>'

                  )

          END AS lead_action_data
              FROM
                  DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.leads t
              LEFT JOIN obj_agg_lead_action_data obj ON obj.id = t.id
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.caller_first_name),'<<NULL>>') AS caller_first_name,
              COALESCE(TRIM(t.caller_last_name),'<<NULL>>') AS caller_last_name,
              COALESCE(TO_VARCHAR(t.caller_phone_number_id),'<<NULL>>') AS caller_phone_number_id,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_VARCHAR(t.source_id),'<<NULL>>') AS source_id,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TRIM(t.size),'<<NULL>>') AS size,
              COALESCE(TO_VARCHAR(t.floor),'<<NULL>>') AS floor,
              COALESCE(TO_VARCHAR(t.quoted_rate),'<<NULL>>') AS quoted_rate,
              COALESCE(TO_CHAR(t.desired_move_in_date,'YYYY-MM-DD'),'<<NULL>>') AS desired_move_in_date,
              CASE WHEN t.urgent IS NULL THEN '<<NULL>>' WHEN t.urgent = TRUE THEN 'TRUE' WHEN t.urgent = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS urgent,
              v_extra_details.extra_details AS extra_details,
              COALESCE(TO_VARCHAR(t.unit_id),'<<NULL>>') AS unit_id,
              COALESCE(TRIM(t.confirmation_number),'<<NULL>>') AS confirmation_number,
              COALESCE(TO_VARCHAR(t.unit_type_id),'<<NULL>>') AS unit_type_id,
              CASE WHEN t.reservation_fee_required IS NULL THEN '<<NULL>>' WHEN t.reservation_fee_required = TRUE THEN 'TRUE' WHEN t.reservation_fee_required = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS reservation_fee_required,
              COALESCE(TO_VARCHAR(t.reservation_invoice_id),'<<NULL>>') AS reservation_invoice_id,
              COALESCE(TO_VARCHAR(t.reservation_fee_invoiceable_id),'<<NULL>>') AS reservation_fee_invoiceable_id,
              COALESCE(TO_CHAR(t.next_action_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS next_action_at,
              COALESCE(TO_VARCHAR(t.current_user_id),'<<NULL>>') AS current_user_id,
              CASE WHEN t.closed IS NULL THEN '<<NULL>>' WHEN t.closed = TRUE THEN 'TRUE' WHEN t.closed = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS closed,
              CASE WHEN t.wait_list IS NULL THEN '<<NULL>>' WHEN t.wait_list = TRUE THEN 'TRUE' WHEN t.wait_list = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS wait_list,
              COALESCE(TRIM(t.status),'<<NULL>>') AS status,
              COALESCE(TO_CHAR(t.reserved_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS reserved_at,
              COALESCE(TO_CHAR(t.moved_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS moved_in_at,
              COALESCE(TO_CHAR(t.cancelled_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS cancelled_at,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.next_lead_action),'<<NULL>>') AS next_lead_action,
              v_lead_action_data.lead_action_data AS lead_action_data,
              CASE WHEN t.move_in_started IS NULL THEN '<<NULL>>' WHEN t.move_in_started = TRUE THEN 'TRUE' WHEN t.move_in_started = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS move_in_started,
              CASE WHEN t.missed_move_in IS NULL THEN '<<NULL>>' WHEN t.missed_move_in = TRUE THEN 'TRUE' WHEN t.missed_move_in = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS missed_move_in,
              CASE WHEN t.needs_closing IS NULL THEN '<<NULL>>' WHEN t.needs_closing = TRUE THEN 'TRUE' WHEN t.needs_closing = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS needs_closing,
              COALESCE(TO_VARCHAR(t.close_reason_id),'<<NULL>>') AS close_reason_id,
              COALESCE(TO_VARCHAR(t.length_of_stay_id),'<<NULL>>') AS length_of_stay_id,
              COALESCE(TRIM(t.most_recent_action_performed),'<<NULL>>') AS most_recent_action_performed,
              COALESCE(TRIM(t.next_action_to_perform),'<<NULL>>') AS next_action_to_perform,
              CASE WHEN t.confirmed IS NULL THEN '<<NULL>>' WHEN t.confirmed = TRUE THEN 'TRUE' WHEN t.confirmed = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS confirmed,
              CASE WHEN t.wait_list_available IS NULL THEN '<<NULL>>' WHEN t.wait_list_available = TRUE THEN 'TRUE' WHEN t.wait_list_available = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS wait_list_available,
              COALESCE(TO_CHAR(t.started_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS started_at,
              CASE WHEN t.appointment IS NULL THEN '<<NULL>>' WHEN t.appointment = TRUE THEN 'TRUE' WHEN t.appointment = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS appointment,
              COALESCE(TO_VARCHAR(t.standard_rate),'<<NULL>>') AS standard_rate,
              COALESCE(TRIM(t.origination),'<<NULL>>') AS origination,
              COALESCE(TRIM(t.origination_platform),'<<NULL>>') AS origination_platform,
              COALESCE(TO_VARCHAR(t.originating_client_application_id),'<<NULL>>') AS originating_client_application_id,
              COALESCE(TO_CHAR(t.last_online_move_in_action_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_online_move_in_action_at,
              COALESCE(TO_CHAR(t.abandoned_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS abandoned_at,
              COALESCE(TO_VARCHAR(t.transferred_from_lead_id),'<<NULL>>') AS transferred_from_lead_id
          FROM variant_lead_action_data v_lead_action_data LEFT JOIN variant_extra_details v_extra_details LEFT JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.leads t ON v_extra_details.id = t.id ON v_lead_action_data.id = t.id
          JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
