tables:
  ledger_delinquencies:
    validations:
      data_validation:
        source_table_name: ledger_delinquencies
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(t.delinquency_schedule_id AS TEXT),'<<NULL>>') AS delinquency_schedule_id,
              COALESCE(TO_CHAR(t.delinquency_start_date,'YYYY-MM-DD'),'<<NULL>>') AS delinquency_start_date,
              COALESCE(TO_CHAR(t.exited_delinquency_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS exited_delinquency_at,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM public.ledger_delinquencies t
          WHERE t.created_at >= '2026-08-01';
        target_table_name: ledger_delinquencies
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.delinquency_schedule_id),'<<NULL>>') AS delinquency_schedule_id,
              COALESCE(TO_CHAR(t.delinquency_start_date,'YYYY-MM-DD'),'<<NULL>>') AS delinquency_start_date,
              COALESCE(TO_CHAR(t.exited_delinquency_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS exited_delinquency_at,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledger_delinquencies t
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.created_at >= '2026-08-01'
