tables:
  ledger_items:
    validations:
      data_validation:
        source_table_name: ledger_items
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.type),'<<NULL>>') AS type,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(t.invoiceable_item_id AS TEXT),'<<NULL>>') AS invoiceable_item_id,
              COALESCE(TO_CHAR(t.effective_date,'YYYY-MM-DD'),'<<NULL>>') AS effective_date,
              COALESCE(TO_CHAR(t.cancel_date,'YYYY-MM-DD'),'<<NULL>>') AS cancel_date,
              CASE WHEN t.data IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.data) h) || '}', '{}') END AS data,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.signed IS NULL THEN '<<NULL>>' WHEN t.signed IS TRUE THEN 'TRUE' WHEN t.signed IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS signed,
              COALESCE(TRIM(t.status),'<<NULL>>') AS status,
              COALESCE(TO_CHAR(t.effective_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS effective_at
          FROM public.ledger_items t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: ledger_items
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_data AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledger_items AS _flt,
                   TABLE(FLATTEN(INPUT => _flt.data, RECURSIVE => FALSE)) flt_kv
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.data) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
              GROUP BY _flt.id
          ),
          variant_data AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.data IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.data
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.data
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.data
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.data
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.data
                      ),

                      '<<NULL>>'

                  )

          END AS data
              FROM
                  DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledger_items t
              LEFT JOIN obj_agg_data obj ON obj.id = t.id
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.type),'<<NULL>>') AS type,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.invoiceable_item_id),'<<NULL>>') AS invoiceable_item_id,
              COALESCE(TO_CHAR(t.effective_date,'YYYY-MM-DD'),'<<NULL>>') AS effective_date,
              COALESCE(TO_CHAR(t.cancel_date,'YYYY-MM-DD'),'<<NULL>>') AS cancel_date,
              v_data.data AS data,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.signed IS NULL THEN '<<NULL>>' WHEN t.signed = TRUE THEN 'TRUE' WHEN t.signed = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS signed,
              COALESCE(TRIM(t.status),'<<NULL>>') AS status,
              COALESCE(TO_CHAR(t.effective_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS effective_at
          FROM variant_data v_data LEFT JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledger_items t ON v_data.id = t.id
          JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
