tables:
  ledgers:
    validations:
      data_validation:
        source_table_name: ledgers
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(CAST(CAST(t.current_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS current_rate,
              COALESCE(TO_CHAR(t.rate_last_changed_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS rate_last_changed_on,
              COALESCE(TO_CHAR(t.closed_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS closed_on,
              COALESCE(TO_CHAR(t.moved_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS moved_in_at,
              COALESCE(CAST(t.invoice_day_of_month AS TEXT),'<<NULL>>') AS invoice_day_of_month,
              COALESCE(CAST(t.unit_id AS TEXT),'<<NULL>>') AS unit_id,
              COALESCE(CAST(t.tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(t.lease_number AS TEXT),'<<NULL>>') AS lease_number,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.locked_out IS NULL THEN '<<NULL>>' WHEN t.locked_out IS TRUE THEN 'TRUE' WHEN t.locked_out IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS locked_out,
              CASE WHEN t.lock_out_exempt IS NULL THEN '<<NULL>>' WHEN t.lock_out_exempt IS TRUE THEN 'TRUE' WHEN t.lock_out_exempt IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS lock_out_exempt,
              COALESCE(CAST(t.autopay_day AS TEXT),'<<NULL>>') AS autopay_day,
              COALESCE(CAST(t.revenue_plan_id AS TEXT),'<<NULL>>') AS revenue_plan_id,
              COALESCE(TRIM(t.manage_revenue),'<<NULL>>') AS manage_revenue,
              COALESCE(TO_CHAR(t.delinquent_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS delinquent_on,
              COALESCE(TO_CHAR(t.past_due_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS past_due_on,
              CASE WHEN t.not_taxed IS NULL THEN '<<NULL>>' WHEN t.not_taxed IS TRUE THEN 'TRUE' WHEN t.not_taxed IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS not_taxed,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted IS TRUE THEN 'TRUE' WHEN t.deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(t.deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(t.paid_thru,'YYYY-MM-DD'),'<<NULL>>') AS paid_thru,
              CASE WHEN t.private_insurance IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.private_insurance) h) || '}', '{}') END AS private_insurance,
              COALESCE(CAST(CAST(t.original_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS original_rate,
              COALESCE(CAST(t.auction_id AS TEXT),'<<NULL>>') AS auction_id,
              COALESCE(CAST(t.delinquency_start_day_modifier AS TEXT),'<<NULL>>') AS delinquency_start_day_modifier,
              COALESCE(CAST(t.acs_access_group_id AS TEXT),'<<NULL>>') AS acs_access_group_id,
              CASE WHEN t.rate_increase_exempt IS NULL THEN '<<NULL>>' WHEN t.rate_increase_exempt IS TRUE THEN 'TRUE' WHEN t.rate_increase_exempt IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS rate_increase_exempt,
              CASE WHEN t.declined_insurance IS NULL THEN '<<NULL>>' WHEN t.declined_insurance IS TRUE THEN 'TRUE' WHEN t.declined_insurance IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS declined_insurance,
              COALESCE(TO_CHAR(t.last_payment_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_payment_at,
              COALESCE(TO_CHAR(t.lease_signed_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS lease_signed_at,
              COALESCE(TO_CHAR(t.generate_next_invoice_on,'YYYY-MM-DD'),'<<NULL>>') AS generate_next_invoice_on,
              COALESCE(TRIM(t.proof_submission_url),'<<NULL>>') AS proof_submission_url,
              COALESCE(TO_CHAR(t.checked_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS checked_in_at,
              COALESCE(CAST(CAST(t.stored_goods_value AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS stored_goods_value,
              COALESCE(CAST(CAST(t.locked_max_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS locked_max_rate,
              COALESCE(TO_CHAR(t.locked_max_rate_end_date,'YYYY-MM-DD'),'<<NULL>>') AS locked_max_rate_end_date,
              COALESCE(CAST(t.transferred_from_ledger_id AS TEXT),'<<NULL>>') AS transferred_from_ledger_id,
              COALESCE(TO_CHAR(t.original_moved_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS original_moved_in_at
          FROM public.ledgers t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: ledgers
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_private_insurance AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledgers AS _flt
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
                   , TABLE(FLATTEN(INPUT => _flt.private_insurance, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.private_insurance) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
              GROUP BY _flt.id
          ),
          variant_private_insurance AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.private_insurance IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.private_insurance
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.private_insurance
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.private_insurance
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.private_insurance
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.private_insurance
                      ),

                      '<<NULL>>'

                  )

          END AS private_insurance
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledgers t
              LEFT JOIN obj_agg_private_insurance obj ON obj.id = t.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_VARCHAR(t.current_rate),'<<NULL>>') AS current_rate,
              COALESCE(TO_CHAR(t.rate_last_changed_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS rate_last_changed_on,
              COALESCE(TO_CHAR(t.closed_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS closed_on,
              COALESCE(TO_CHAR(t.moved_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS moved_in_at,
              COALESCE(TO_VARCHAR(t.invoice_day_of_month),'<<NULL>>') AS invoice_day_of_month,
              COALESCE(TO_VARCHAR(t.unit_id),'<<NULL>>') AS unit_id,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.lease_number),'<<NULL>>') AS lease_number,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.locked_out IS NULL THEN '<<NULL>>' WHEN t.locked_out = TRUE THEN 'TRUE' WHEN t.locked_out = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS locked_out,
              CASE WHEN t.lock_out_exempt IS NULL THEN '<<NULL>>' WHEN t.lock_out_exempt = TRUE THEN 'TRUE' WHEN t.lock_out_exempt = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS lock_out_exempt,
              COALESCE(TO_VARCHAR(t.autopay_day),'<<NULL>>') AS autopay_day,
              COALESCE(TO_VARCHAR(t.revenue_plan_id),'<<NULL>>') AS revenue_plan_id,
              COALESCE(TRIM(t.manage_revenue),'<<NULL>>') AS manage_revenue,
              COALESCE(TO_CHAR(t.delinquent_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS delinquent_on,
              COALESCE(TO_CHAR(t.past_due_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS past_due_on,
              CASE WHEN t.not_taxed IS NULL THEN '<<NULL>>' WHEN t.not_taxed = TRUE THEN 'TRUE' WHEN t.not_taxed = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS not_taxed,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(t.paid_thru,'YYYY-MM-DD'),'<<NULL>>') AS paid_thru,
              v_private_insurance.private_insurance AS private_insurance,
              COALESCE(TO_VARCHAR(t.original_rate),'<<NULL>>') AS original_rate,
              COALESCE(TO_VARCHAR(t.auction_id),'<<NULL>>') AS auction_id,
              COALESCE(TO_VARCHAR(t.delinquency_start_day_modifier),'<<NULL>>') AS delinquency_start_day_modifier,
              COALESCE(TO_VARCHAR(t.acs_access_group_id),'<<NULL>>') AS acs_access_group_id,
              CASE WHEN t.rate_increase_exempt IS NULL THEN '<<NULL>>' WHEN t.rate_increase_exempt = TRUE THEN 'TRUE' WHEN t.rate_increase_exempt = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS rate_increase_exempt,
              CASE WHEN t.declined_insurance IS NULL THEN '<<NULL>>' WHEN t.declined_insurance = TRUE THEN 'TRUE' WHEN t.declined_insurance = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS declined_insurance,
              COALESCE(TO_CHAR(t.last_payment_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_payment_at,
              COALESCE(TO_CHAR(t.lease_signed_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS lease_signed_at,
              COALESCE(TO_CHAR(t.generate_next_invoice_on,'YYYY-MM-DD'),'<<NULL>>') AS generate_next_invoice_on,
              COALESCE(TRIM(t.proof_submission_url),'<<NULL>>') AS proof_submission_url,
              COALESCE(TO_CHAR(t.checked_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS checked_in_at,
              COALESCE(TO_VARCHAR(t.stored_goods_value),'<<NULL>>') AS stored_goods_value,
              COALESCE(TO_VARCHAR(t.locked_max_rate),'<<NULL>>') AS locked_max_rate,
              COALESCE(TO_CHAR(t.locked_max_rate_end_date,'YYYY-MM-DD'),'<<NULL>>') AS locked_max_rate_end_date,
              COALESCE(TO_VARCHAR(t.transferred_from_ledger_id),'<<NULL>>') AS transferred_from_ledger_id,
              COALESCE(TO_CHAR(t.original_moved_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS original_moved_in_at
          FROM variant_private_insurance v_private_insurance LEFT JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.ledgers t ON v_private_insurance.id = t.id
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
