tables:
  line_items:
    validations:
      data_validation:
        source_table_name: line_items
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TRIM(t.product_code),'<<NULL>>') AS product_code,
              COALESCE(CAST(CAST(t.amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS amount,
              COALESCE(CAST(t.quantity AS TEXT),'<<NULL>>') AS quantity,
              COALESCE(TO_CHAR(t.service_start_date,'YYYY-MM-DD'),'<<NULL>>') AS service_start_date,
              COALESCE(TO_CHAR(t.service_end_date,'YYYY-MM-DD'),'<<NULL>>') AS service_end_date,
              CASE WHEN t.locked IS NULL THEN '<<NULL>>' WHEN t.locked IS TRUE THEN 'TRUE' WHEN t.locked IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS locked,
              COALESCE(TRIM(t.saved_account_code),'<<NULL>>') AS saved_account_code,
              COALESCE(CAST(t.created_by_id AS TEXT),'<<NULL>>') AS created_by_id,
              COALESCE(CAST(t.invoice_id AS TEXT),'<<NULL>>') AS invoice_id,
              COALESCE(CAST(t.invoiceable_id AS TEXT),'<<NULL>>') AS invoiceable_id,
              COALESCE(TRIM(t.invoiceable_type),'<<NULL>>') AS invoiceable_type,
              COALESCE(CAST(t.parent_line_item_id AS TEXT),'<<NULL>>') AS parent_line_item_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(t.tenant_id AS TEXT),'<<NULL>>') AS tenant_id,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              CASE WHEN t.tax_exempt IS NULL THEN '<<NULL>>' WHEN t.tax_exempt IS TRUE THEN 'TRUE' WHEN t.tax_exempt IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS tax_exempt,
              COALESCE(TRIM(t.tax_exempt_number),'<<NULL>>') AS tax_exempt_number,
              CASE WHEN t.modifiers IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.modifiers) h) || '}', '{}') END AS modifiers,
              COALESCE(CAST(t.original_line_item_id AS TEXT),'<<NULL>>') AS original_line_item_id,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code,
              COALESCE(TRIM(t.internal_accounts_receivable_account_code),'<<NULL>>') AS internal_accounts_receivable_account_code
          FROM public.line_items t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01';
        target_table_name: line_items
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_modifiers AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.line_items AS _flt
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
                   , TABLE(FLATTEN(INPUT => _flt.modifiers, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.modifiers) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND _flt.created_at >= '2025-08-01'
              GROUP BY _flt.id
          ),
          variant_modifiers AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.modifiers IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.modifiers
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.modifiers
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.modifiers
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.modifiers
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.modifiers
                      ),

                      '<<NULL>>'

                  )

          END AS modifiers
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.line_items t
              LEFT JOIN obj_agg_modifiers obj ON obj.id = t.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01'

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.description),'<<NULL>>') AS description,
              COALESCE(TRIM(t.product_code),'<<NULL>>') AS product_code,
              COALESCE(TO_VARCHAR(t.amount),'<<NULL>>') AS amount,
              COALESCE(TO_VARCHAR(t.quantity),'<<NULL>>') AS quantity,
              COALESCE(TO_CHAR(t.service_start_date,'YYYY-MM-DD'),'<<NULL>>') AS service_start_date,
              COALESCE(TO_CHAR(t.service_end_date,'YYYY-MM-DD'),'<<NULL>>') AS service_end_date,
              CASE WHEN t.locked IS NULL THEN '<<NULL>>' WHEN t.locked = TRUE THEN 'TRUE' WHEN t.locked = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS locked,
              COALESCE(TRIM(t.saved_account_code),'<<NULL>>') AS saved_account_code,
              COALESCE(TO_VARCHAR(t.created_by_id),'<<NULL>>') AS created_by_id,
              COALESCE(TO_VARCHAR(t.invoice_id),'<<NULL>>') AS invoice_id,
              COALESCE(TO_VARCHAR(t.invoiceable_id),'<<NULL>>') AS invoiceable_id,
              COALESCE(TRIM(t.invoiceable_type),'<<NULL>>') AS invoiceable_type,
              COALESCE(TO_VARCHAR(t.parent_line_item_id),'<<NULL>>') AS parent_line_item_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.tenant_id),'<<NULL>>') AS tenant_id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              CASE WHEN t.tax_exempt IS NULL THEN '<<NULL>>' WHEN t.tax_exempt = TRUE THEN 'TRUE' WHEN t.tax_exempt = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS tax_exempt,
              COALESCE(TRIM(t.tax_exempt_number),'<<NULL>>') AS tax_exempt_number,
              v_modifiers.modifiers AS modifiers,
              COALESCE(TO_VARCHAR(t.original_line_item_id),'<<NULL>>') AS original_line_item_id,
              COALESCE(TRIM(t.internal_account_code),'<<NULL>>') AS internal_account_code,
              COALESCE(TRIM(t.internal_accounts_receivable_account_code),'<<NULL>>') AS internal_accounts_receivable_account_code
          FROM variant_modifiers v_modifiers LEFT JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.line_items t ON v_modifiers.id = t.id
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01'
