tables:
  notes:
    validations:
      data_validation:
        source_table_name: notes
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.type),'<<NULL>>') AS type,
              COALESCE(CAST(t.event_id AS TEXT),'<<NULL>>') AS event_id,
              COALESCE(CAST(t.user_id AS TEXT),'<<NULL>>') AS user_id,
              COALESCE(TRIM(t.note),'<<NULL>>') AS note,
              CASE WHEN t.important IS NULL THEN '<<NULL>>' WHEN t.important IS TRUE THEN 'TRUE' WHEN t.important IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS important,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.event_type),'<<NULL>>') AS event_type
          FROM public.notes t
          WHERE t.created_at >= '2026-08-01';
        target_table_name: notes
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.type),'<<NULL>>') AS type,
              COALESCE(TO_VARCHAR(t.event_id),'<<NULL>>') AS event_id,
              COALESCE(TO_VARCHAR(t.user_id),'<<NULL>>') AS user_id,
              COALESCE(TRIM(t.note),'<<NULL>>') AS note,
              CASE WHEN t.important IS NULL THEN '<<NULL>>' WHEN t.important = TRUE THEN 'TRUE' WHEN t.important = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS important,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.event_type),'<<NULL>>') AS event_type
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.notes t
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.created_at >= '2026-08-01'
