tables:
  phone_numbers:
    validations:
      data_validation:
        source_table_name: phone_numbers
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.source),'<<NULL>>') AS source,
              COALESCE(TRIM(t.number),'<<NULL>>') AS number,
              COALESCE(TRIM(t.caller_id),'<<NULL>>') AS caller_id,
              COALESCE(CAST(t.owner_id AS TEXT),'<<NULL>>') AS owner_id,
              COALESCE(TRIM(t.owner_type),'<<NULL>>') AS owner_type,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.extension),'<<NULL>>') AS extension,
              COALESCE(TRIM(t.label),'<<NULL>>') AS label,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.invalid_data IS NULL THEN '<<NULL>>' WHEN t.invalid_data IS TRUE THEN 'TRUE' WHEN t.invalid_data IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS invalid_data,
              CASE WHEN t.sms_opt_in IS NULL THEN '<<NULL>>' WHEN t.sms_opt_in IS TRUE THEN 'TRUE' WHEN t.sms_opt_in IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS sms_opt_in,
              CASE WHEN t.sms_unsubscribed IS NULL THEN '<<NULL>>' WHEN t.sms_unsubscribed IS TRUE THEN 'TRUE' WHEN t.sms_unsubscribed IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS sms_unsubscribed,
              COALESCE(TRIM(t.country_code),'<<NULL>>') AS country_code,
              COALESCE(CAST(t.company_id AS TEXT),'<<NULL>>') AS company_id
          FROM public.phone_numbers t
          JOIN public.tenants t1 ON t.owner_id = t1.id
              JOIN public.facilities f ON t1.facility_id = f.id
          WHERE t.owner_type IN ('Tenant') AND f.company_id IN (137,9088,501);
        target_table_name: phone_numbers
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.source),'<<NULL>>') AS source,
              COALESCE(TRIM(t.number),'<<NULL>>') AS number,
              COALESCE(TRIM(t.caller_id),'<<NULL>>') AS caller_id,
              COALESCE(TO_VARCHAR(t.owner_id),'<<NULL>>') AS owner_id,
              COALESCE(TRIM(t.owner_type),'<<NULL>>') AS owner_type,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.extension),'<<NULL>>') AS extension,
              COALESCE(TRIM(t.label),'<<NULL>>') AS label,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.invalid_data IS NULL THEN '<<NULL>>' WHEN t.invalid_data = TRUE THEN 'TRUE' WHEN t.invalid_data = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS invalid_data,
              CASE WHEN t.sms_opt_in IS NULL THEN '<<NULL>>' WHEN t.sms_opt_in = TRUE THEN 'TRUE' WHEN t.sms_opt_in = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS sms_opt_in,
              CASE WHEN t.sms_unsubscribed IS NULL THEN '<<NULL>>' WHEN t.sms_unsubscribed = TRUE THEN 'TRUE' WHEN t.sms_unsubscribed = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS sms_unsubscribed,
              COALESCE(TRIM(t.country_code),'<<NULL>>') AS country_code,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.phone_numbers t
          JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants t1 ON t.owner_id = t1.id
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t1.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND t.owner_type IN ('Tenant') AND f.company_id IN (137,9088,501)
