tables:
  reasons:
    validations:
      data_validation:
        source_table_name: reasons
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(reason),'<<NULL>>') AS reason,
              COALESCE(TRIM(kind),'<<NULL>>') AS kind,
              COALESCE(CAST(company_id AS TEXT),'<<NULL>>') AS company_id,
              CASE WHEN deleted IS NULL THEN '<<NULL>>' WHEN deleted IS TRUE THEN 'TRUE' WHEN deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM public.reasons
          ;
        target_table_name: reasons
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.reason),'<<NULL>>') AS reason,
              COALESCE(TRIM(t.kind),'<<NULL>>') AS kind,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.reasons t
          WHERE t._FIVETRAN_ACTIVE = TRUE
