tables:
  sources:
    validations:
      data_validation:
        source_table_name: sources
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(name),'<<NULL>>') AS name,
              COALESCE(TRIM(category),'<<NULL>>') AS category,
              CASE WHEN deleted IS NULL THEN '<<NULL>>' WHEN deleted IS TRUE THEN 'TRUE' WHEN deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN user_selectable IS NULL THEN '<<NULL>>' WHEN user_selectable IS TRUE THEN 'TRUE' WHEN user_selectable IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS user_selectable,
              COALESCE(CAST(client_application_id AS TEXT),'<<NULL>>') AS client_application_id,
              COALESCE(CAST(company_id AS TEXT),'<<NULL>>') AS company_id
          FROM public.sources
          ;
        target_table_name: sources
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TRIM(t.category),'<<NULL>>') AS category,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.user_selectable IS NULL THEN '<<NULL>>' WHEN t.user_selectable = TRUE THEN 'TRUE' WHEN t.user_selectable = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS user_selectable,
              COALESCE(TO_VARCHAR(t.client_application_id),'<<NULL>>') AS client_application_id,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.sources t
          WHERE t._FIVETRAN_ACTIVE = TRUE
