tables:
  tenants:
    validations:
      data_validation:
        source_table_name: tenants
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.first_name),'<<NULL>>') AS first_name,
              COALESCE(TRIM(t.last_name),'<<NULL>>') AS last_name,
              COALESCE(TRIM(t.email),'<<NULL>>') AS email,
              CASE WHEN t.tax_exempt IS NULL THEN '<<NULL>>' WHEN t.tax_exempt IS TRUE THEN 'TRUE' WHEN t.tax_exempt IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS tax_exempt,
              COALESCE(TRIM(t.tax_exempt_number),'<<NULL>>') AS tax_exempt_number,
              COALESCE(TRIM(t.drivers_license_number),'<<NULL>>') AS drivers_license_number,
              COALESCE(TRIM(t.drivers_license_state),'<<NULL>>') AS drivers_license_state,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.payment_provider_checksum),'<<NULL>>') AS payment_provider_checksum,
              COALESCE(TRIM(t.business_name),'<<NULL>>') AS business_name,
              COALESCE(TRIM(t.encrypted_password),'<<NULL>>') AS encrypted_password,
              COALESCE(TRIM(t.reset_password_token),'<<NULL>>') AS reset_password_token,
              COALESCE(TO_CHAR(t.reset_password_sent_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS reset_password_sent_at,
              COALESCE(TO_CHAR(t.remember_created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS remember_created_at,
              COALESCE(CAST(t.sign_in_count AS TEXT),'<<NULL>>') AS sign_in_count,
              COALESCE(TO_CHAR(t.current_sign_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS current_sign_in_at,
              COALESCE(TO_CHAR(t.last_sign_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_sign_in_at,
              COALESCE(TRIM(t.current_sign_in_ip),'<<NULL>>') AS current_sign_in_ip,
              COALESCE(TRIM(t.last_sign_in_ip),'<<NULL>>') AS last_sign_in_ip,
              COALESCE(TRIM(t.last_ua),'<<NULL>>') AS last_ua,
              COALESCE(TRIM(t.middle_initial),'<<NULL>>') AS middle_initial,
              COALESCE(TRIM(t.title),'<<NULL>>') AS title,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.gate_vendor_data IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.gate_vendor_data) h) || '}', '{}') END AS gate_vendor_data,
              CASE WHEN t.delinquent IS NULL THEN '<<NULL>>' WHEN t.delinquent IS TRUE THEN 'TRUE' WHEN t.delinquent IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS delinquent,
              COALESCE(TRIM(t.username),'<<NULL>>') AS username,
              CASE WHEN t.password_expired IS NULL THEN '<<NULL>>' WHEN t.password_expired IS TRUE THEN 'TRUE' WHEN t.password_expired IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS password_expired,
              COALESCE(TRIM(t.payment_provider_token_enc),'<<NULL>>') AS payment_provider_token_enc,
              COALESCE(TRIM(t.vehicle_license_plate_number),'<<NULL>>') AS vehicle_license_plate_number,
              COALESCE(TRIM(t.vehicle_description),'<<NULL>>') AS vehicle_description,
              COALESCE(CAST(t.primary_contact_id AS TEXT),'<<NULL>>') AS primary_contact_id,
              COALESCE(CAST(t.primary_phone_number_id AS TEXT),'<<NULL>>') AS primary_phone_number_id,
              COALESCE(TRIM(t.vehicle_license_state),'<<NULL>>') AS vehicle_license_state,
              COALESCE(CAST(t.account_number AS TEXT),'<<NULL>>') AS account_number,
              COALESCE(CAST(t.company_id AS TEXT),'<<NULL>>') AS company_id,
              COALESCE(CAST(t.tenant_account_kind_id AS TEXT),'<<NULL>>') AS tenant_account_kind_id,
              COALESCE(CAST(t.confirmation_index AS TEXT),'<<NULL>>') AS confirmation_index,
              CASE WHEN t.invalid_email IS NULL THEN '<<NULL>>' WHEN t.invalid_email IS TRUE THEN 'TRUE' WHEN t.invalid_email IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS invalid_email,
              COALESCE(TO_CHAR(t.date_of_birth,'YYYY-MM-DD'),'<<NULL>>') AS date_of_birth,
              COALESCE(TO_CHAR(t.drivers_license_expiration_date,'YYYY-MM-DD'),'<<NULL>>') AS drivers_license_expiration_date,
              CASE WHEN t.military_information IS NULL THEN '<<NULL>>' ELSE COALESCE('{' || (SELECT STRING_AGG(TO_JSON(h.key::TEXT) || ': ' || TO_JSON(h.value::TEXT), ', ' ORDER BY h.key) FROM EACH(t.military_information) h) || '}', '{}') END AS military_information,
              CASE WHEN t.blocked_payments IS NULL THEN '<<NULL>>' WHEN t.blocked_payments IS TRUE THEN 'TRUE' WHEN t.blocked_payments IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS blocked_payments,
              COALESCE(TRIM(t.vehicle_make),'<<NULL>>') AS vehicle_make,
              COALESCE(TRIM(t.vehicle_model),'<<NULL>>') AS vehicle_model,
              COALESCE(TRIM(t.vehicle_vin),'<<NULL>>') AS vehicle_vin,
              CASE WHEN t.vehicle_motorized IS NULL THEN '<<NULL>>' WHEN t.vehicle_motorized IS TRUE THEN 'TRUE' WHEN t.vehicle_motorized IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS vehicle_motorized,
              CASE WHEN t.rental_review IS NULL THEN '<<NULL>>' WHEN t.rental_review IS TRUE THEN 'TRUE' WHEN t.rental_review IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS rental_review,
              COALESCE(TRIM(t.rental_review_reason),'<<NULL>>') AS rental_review_reason,
              COALESCE(TRIM(t.rental_review_remediation),'<<NULL>>') AS rental_review_remediation,
              COALESCE(CAST(t.primary_tenant_id AS TEXT),'<<NULL>>') AS primary_tenant_id,
              COALESCE(TO_CHAR(t.archived_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS archived_at
          FROM public.tenants t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: tenants
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_gate_vendor_data AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants AS _flt,
                   TABLE(FLATTEN(INPUT => _flt.gate_vendor_data, RECURSIVE => FALSE)) flt_kv
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.gate_vendor_data) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
              GROUP BY _flt.id
          ),
          variant_gate_vendor_data AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.gate_vendor_data IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.gate_vendor_data
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.gate_vendor_data
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.gate_vendor_data
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.gate_vendor_data
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.gate_vendor_data
                      ),

                      '<<NULL>>'

                  )

          END AS gate_vendor_data
              FROM
                  DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants t
              LEFT JOIN obj_agg_gate_vendor_data obj ON obj.id = t.id
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)

          ),
          obj_agg_military_information AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants AS _flt,
                   TABLE(FLATTEN(INPUT => _flt.military_information, RECURSIVE => FALSE)) flt_kv
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.military_information) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
              GROUP BY _flt.id
          ),
          variant_military_information AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.military_information IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.military_information
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.military_information
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.military_information
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.military_information
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.military_information
                      ),

                      '<<NULL>>'

                  )

          END AS military_information
              FROM
                  DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants t
              LEFT JOIN obj_agg_military_information obj ON obj.id = t.id
              JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.first_name),'<<NULL>>') AS first_name,
              COALESCE(TRIM(t.last_name),'<<NULL>>') AS last_name,
              COALESCE(TRIM(t.email),'<<NULL>>') AS email,
              CASE WHEN t.tax_exempt IS NULL THEN '<<NULL>>' WHEN t.tax_exempt = TRUE THEN 'TRUE' WHEN t.tax_exempt = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS tax_exempt,
              COALESCE(TRIM(t.tax_exempt_number),'<<NULL>>') AS tax_exempt_number,
              COALESCE(TRIM(t.drivers_license_number),'<<NULL>>') AS drivers_license_number,
              COALESCE(TRIM(t.drivers_license_state),'<<NULL>>') AS drivers_license_state,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.payment_provider_checksum),'<<NULL>>') AS payment_provider_checksum,
              COALESCE(TRIM(t.business_name),'<<NULL>>') AS business_name,
              COALESCE(TRIM(t.encrypted_password),'<<NULL>>') AS encrypted_password,
              COALESCE(TRIM(t.reset_password_token),'<<NULL>>') AS reset_password_token,
              COALESCE(TO_CHAR(t.reset_password_sent_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS reset_password_sent_at,
              COALESCE(TO_CHAR(t.remember_created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS remember_created_at,
              COALESCE(TO_VARCHAR(t.sign_in_count),'<<NULL>>') AS sign_in_count,
              COALESCE(TO_CHAR(t.current_sign_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS current_sign_in_at,
              COALESCE(TO_CHAR(t.last_sign_in_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS last_sign_in_at,
              COALESCE(TRIM(t.current_sign_in_ip),'<<NULL>>') AS current_sign_in_ip,
              COALESCE(TRIM(t.last_sign_in_ip),'<<NULL>>') AS last_sign_in_ip,
              COALESCE(TRIM(t.last_ua),'<<NULL>>') AS last_ua,
              COALESCE(TRIM(t.middle_initial),'<<NULL>>') AS middle_initial,
              COALESCE(TRIM(t.title),'<<NULL>>') AS title,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              v_gate_vendor_data.gate_vendor_data AS gate_vendor_data,
              CASE WHEN t.delinquent IS NULL THEN '<<NULL>>' WHEN t.delinquent = TRUE THEN 'TRUE' WHEN t.delinquent = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS delinquent,
              COALESCE(TRIM(t.username),'<<NULL>>') AS username,
              CASE WHEN t.password_expired IS NULL THEN '<<NULL>>' WHEN t.password_expired = TRUE THEN 'TRUE' WHEN t.password_expired = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS password_expired,
              COALESCE(TRIM(t.payment_provider_token_enc),'<<NULL>>') AS payment_provider_token_enc,
              COALESCE(TRIM(t.vehicle_license_plate_number),'<<NULL>>') AS vehicle_license_plate_number,
              COALESCE(TRIM(t.vehicle_description),'<<NULL>>') AS vehicle_description,
              COALESCE(TO_VARCHAR(t.primary_contact_id),'<<NULL>>') AS primary_contact_id,
              COALESCE(TO_VARCHAR(t.primary_phone_number_id),'<<NULL>>') AS primary_phone_number_id,
              COALESCE(TRIM(t.vehicle_license_state),'<<NULL>>') AS vehicle_license_state,
              COALESCE(TO_VARCHAR(t.account_number),'<<NULL>>') AS account_number,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              COALESCE(TO_VARCHAR(t.tenant_account_kind_id),'<<NULL>>') AS tenant_account_kind_id,
              COALESCE(TO_VARCHAR(t.confirmation_index),'<<NULL>>') AS confirmation_index,
              CASE WHEN t.invalid_email IS NULL THEN '<<NULL>>' WHEN t.invalid_email = TRUE THEN 'TRUE' WHEN t.invalid_email = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS invalid_email,
              COALESCE(TO_CHAR(t.date_of_birth,'YYYY-MM-DD'),'<<NULL>>') AS date_of_birth,
              COALESCE(TO_CHAR(t.drivers_license_expiration_date,'YYYY-MM-DD'),'<<NULL>>') AS drivers_license_expiration_date,
              v_military_information.military_information AS military_information,
              CASE WHEN t.blocked_payments IS NULL THEN '<<NULL>>' WHEN t.blocked_payments = TRUE THEN 'TRUE' WHEN t.blocked_payments = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS blocked_payments,
              COALESCE(TRIM(t.vehicle_make),'<<NULL>>') AS vehicle_make,
              COALESCE(TRIM(t.vehicle_model),'<<NULL>>') AS vehicle_model,
              COALESCE(TRIM(t.vehicle_vin),'<<NULL>>') AS vehicle_vin,
              CASE WHEN t.vehicle_motorized IS NULL THEN '<<NULL>>' WHEN t.vehicle_motorized = TRUE THEN 'TRUE' WHEN t.vehicle_motorized = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS vehicle_motorized,
              CASE WHEN t.rental_review IS NULL THEN '<<NULL>>' WHEN t.rental_review = TRUE THEN 'TRUE' WHEN t.rental_review = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS rental_review,
              COALESCE(TRIM(t.rental_review_reason),'<<NULL>>') AS rental_review_reason,
              COALESCE(TRIM(t.rental_review_remediation),'<<NULL>>') AS rental_review_remediation,
              COALESCE(TO_VARCHAR(t.primary_tenant_id),'<<NULL>>') AS primary_tenant_id,
              COALESCE(TO_CHAR(t.archived_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS archived_at
          FROM variant_military_information v_military_information LEFT JOIN variant_gate_vendor_data v_gate_vendor_data LEFT JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenants t ON v_gate_vendor_data.id = t.id ON v_military_information.id = t.id
          JOIN DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
