tables:
  tenant_account_kinds:
    validations:
      data_validation:
        source_table_name: tenant_account_kinds
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(name),'<<NULL>>') AS name,
              COALESCE(CAST(company_id AS TEXT),'<<NULL>>') AS company_id,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(UPPER(TRIM(CAST(uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(category),'<<NULL>>') AS category
          FROM public.tenant_account_kinds
          ;
        target_table_name: tenant_account_kinds
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TO_VARCHAR(t.company_id),'<<NULL>>') AS company_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.category),'<<NULL>>') AS category
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.tenant_account_kinds t
          WHERE t._FIVETRAN_ACTIVE = TRUE
