tables:
  time_zone_maps:
    validations:
      data_validation:
        source_table_name: time_zone_maps
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(active_support_time_zone_name),'<<NULL>>') AS active_support_time_zone_name,
              COALESCE(TRIM(postgres_time_zone_name),'<<NULL>>') AS postgres_time_zone_name,
              COALESCE(TO_CHAR(created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM public.time_zone_maps
          ;
        target_table_name: time_zone_maps
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.active_support_time_zone_name),'<<NULL>>') AS active_support_time_zone_name,
              COALESCE(TRIM(t.postgres_time_zone_name),'<<NULL>>') AS postgres_time_zone_name,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM DEV_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.time_zone_maps t
          WHERE t._FIVETRAN_ACTIVE = TRUE
