tables:
  transactions:
    validations:
      data_validation:
        source_table_name: transactions
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.transaction_type),'<<NULL>>') AS transaction_type,
              COALESCE(CAST(CAST(t.transaction_amount AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS transaction_amount,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(CAST(t.ledger_id AS TEXT),'<<NULL>>') AS ledger_id,
              COALESCE(CAST(t.event_id AS TEXT),'<<NULL>>') AS event_id,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.payable_balance_type),'<<NULL>>') AS payable_balance_type,
              COALESCE(CAST(t.payable_balance_id AS TEXT),'<<NULL>>') AS payable_balance_id,
              COALESCE(TO_CHAR(t.relevant_start_date,'YYYY-MM-DD'),'<<NULL>>') AS relevant_start_date,
              COALESCE(TO_CHAR(t.relevant_end_date,'YYYY-MM-DD'),'<<NULL>>') AS relevant_end_date,
              COALESCE((t.detail)::JSONB::TEXT,'<<NULL>>') AS detail,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              CASE WHEN t.backfilled IS NULL THEN '<<NULL>>' WHEN t.backfilled IS TRUE THEN 'TRUE' WHEN t.backfilled IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS backfilled,
              COALESCE(CAST(t.processed_count AS TEXT),'<<NULL>>') AS processed_count,
              COALESCE(CAST(t.parent_id AS TEXT),'<<NULL>>') AS parent_id,
              CASE WHEN t.gl_exempt IS NULL THEN '<<NULL>>' WHEN t.gl_exempt IS TRUE THEN 'TRUE' WHEN t.gl_exempt IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS gl_exempt
          FROM public.transactions t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01';
        target_table_name: transactions
        target: snowflake
        targetcolumn: id
        targetquery: |-
          WITH
          obj_agg_detail AS
          (
              SELECT
                  _flt.id AS id,
                  LISTAGG(
                      CASE
                          WHEN flt_kv.key IS NULL THEN NULL
                          ELSE
                              TO_JSON(TO_VARIANT(flt_kv.key::VARCHAR)) || ': ' ||
                              CASE
                                  WHEN flt_kv.value IS NULL THEN 'null'
                                  WHEN IS_NULL_VALUE(flt_kv.value) THEN 'null'
                                  WHEN TYPEOF(flt_kv.value) = 'VARCHAR' THEN TO_JSON(TO_VARIANT(flt_kv.value::VARCHAR))
                                  WHEN TYPEOF(flt_kv.value) = 'BOOLEAN' THEN LOWER(flt_kv.value::VARCHAR)
                                  WHEN TYPEOF(flt_kv.value) IN ('INTEGER','DECIMAL','DOUBLE','REAL','NUMBER') THEN flt_kv.value::VARCHAR
                                  ELSE TO_JSON(flt_kv.value)
                              END
                      END, ', ') WITHIN GROUP (ORDER BY flt_kv.key) AS obj_body
              FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.transactions AS _flt
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON _flt.facility_id = f.id
                   , TABLE(FLATTEN(INPUT => _flt.detail, RECURSIVE => FALSE)) flt_kv
              WHERE _flt._FIVETRAN_ACTIVE = TRUE
                AND TYPEOF(_flt.detail) = 'OBJECT'
                AND _flt._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND _flt.created_at >= '2025-08-01'
              GROUP BY _flt.id
          ),
          variant_detail AS
          (
              SELECT
                  t.id AS id,
                  CASE

              -- ======================================================
              -- SQL NULL
              -- ======================================================

              WHEN t.detail IS NULL
                  THEN '<<NULL>>'


              -- =====================================================
              -- JSON NULL
              -- =====================================================

              WHEN IS_NULL_VALUE(
                  t.detail
              )
                  THEN 'null'


              -- =====================================================
              -- OBJECT
              -- =====================================================

              WHEN TYPEOF(
                  t.detail
              ) = 'OBJECT'

                  THEN

                      CHR(123)

                      ||

                      COALESCE(COALESCE(obj.obj_body, ''), '')

                      ||

                      CHR(125)


              -- =====================================================
              -- ARRAY
              -- =====================================================

              WHEN TYPEOF(
                  t.detail
              ) = 'ARRAY'

                  THEN COALESCE(

                      TO_JSON(
                          t.detail
                      ),

                      '[]'

                  )


              -- =====================================================
              -- SCALAR
              -- =====================================================

              ELSE

                  COALESCE(

                      TO_JSON(
                          t.detail
                      ),

                      '<<NULL>>'

                  )

          END AS detail
              FROM
                  {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.transactions t
              LEFT JOIN obj_agg_detail obj ON obj.id = t.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
              WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01'

          )
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.transaction_type),'<<NULL>>') AS transaction_type,
              COALESCE(TO_VARCHAR(t.transaction_amount),'<<NULL>>') AS transaction_amount,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_VARCHAR(t.ledger_id),'<<NULL>>') AS ledger_id,
              COALESCE(TO_VARCHAR(t.event_id),'<<NULL>>') AS event_id,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              COALESCE(TRIM(t.payable_balance_type),'<<NULL>>') AS payable_balance_type,
              COALESCE(TO_VARCHAR(t.payable_balance_id),'<<NULL>>') AS payable_balance_id,
              COALESCE(TO_CHAR(t.relevant_start_date,'YYYY-MM-DD'),'<<NULL>>') AS relevant_start_date,
              COALESCE(TO_CHAR(t.relevant_end_date,'YYYY-MM-DD'),'<<NULL>>') AS relevant_end_date,
              v_detail.detail AS detail,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              CASE WHEN t.backfilled IS NULL THEN '<<NULL>>' WHEN t.backfilled = TRUE THEN 'TRUE' WHEN t.backfilled = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS backfilled,
              COALESCE(TO_VARCHAR(t.processed_count),'<<NULL>>') AS processed_count,
              COALESCE(TO_VARCHAR(t.parent_id),'<<NULL>>') AS parent_id,
              CASE WHEN t.gl_exempt IS NULL THEN '<<NULL>>' WHEN t.gl_exempt = TRUE THEN 'TRUE' WHEN t.gl_exempt = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS gl_exempt
          FROM variant_detail v_detail LEFT JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.transactions t ON v_detail.id = t.id
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501) AND t.created_at >= '2025-08-01'
