tables:
  unit_amenities_units:
    validations:
      data_validation:
        source_table_name: unit_amenities_units
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.unit_id AS TEXT),'<<NULL>>') AS unit_id,
              COALESCE(CAST(t.unit_amenity_id AS TEXT),'<<NULL>>') AS unit_amenity_id,
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM public.unit_amenities_units t
          JOIN public.units t1 ON t.unit_id = t1.id
              JOIN public.facilities f ON t1.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: unit_amenities_units
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.unit_id),'<<NULL>>') AS unit_id,
              COALESCE(TO_VARCHAR(t.unit_amenity_id),'<<NULL>>') AS unit_amenity_id,
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.unit_amenities_units t
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.units t1 ON t.unit_id = t1.id
              JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t1.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
