tables:
  units:
    validations:
      data_validation:
        source_table_name: units
        source: postgres
        sourcecolumn: id
        sourcequery: |-
          SELECT
              COALESCE(CAST(t.id AS TEXT),'<<NULL>>') AS id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TRIM(t.status),'<<NULL>>') AS status,
              CASE WHEN t.damaged IS NULL THEN '<<NULL>>' WHEN t.damaged IS TRUE THEN 'TRUE' WHEN t.damaged IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS damaged,
              CASE WHEN t.dirty IS NULL THEN '<<NULL>>' WHEN t.dirty IS TRUE THEN 'TRUE' WHEN t.dirty IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS dirty,
              CASE WHEN t.rentable IS NULL THEN '<<NULL>>' WHEN t.rentable IS TRUE THEN 'TRUE' WHEN t.rentable IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS rentable,
              COALESCE(TO_CHAR(t.available_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS available_on,
              COALESCE(CAST(t.width AS TEXT),'<<NULL>>') AS width,
              COALESCE(CAST(t.height AS TEXT),'<<NULL>>') AS height,
              COALESCE(CAST(t.length AS TEXT),'<<NULL>>') AS length,
              COALESCE(CAST(CAST(t.standard_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS standard_rate,
              COALESCE(CAST(t.door_width AS TEXT),'<<NULL>>') AS door_width,
              COALESCE(CAST(t.door_height AS TEXT),'<<NULL>>') AS door_height,
              COALESCE(TRIM(t.door_type),'<<NULL>>') AS door_type,
              COALESCE(TRIM(t.access_type),'<<NULL>>') AS access_type,
              COALESCE(CAST(t.floor AS TEXT),'<<NULL>>') AS floor,
              COALESCE(CAST(t.tax_id AS TEXT),'<<NULL>>') AS tax_id,
              COALESCE(CAST(t.unit_type_id AS TEXT),'<<NULL>>') AS unit_type_id,
              COALESCE(CAST(t.facility_id AS TEXT),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(CAST(t.walk_thru_order AS TEXT),'<<NULL>>') AS walk_thru_order,
              COALESCE(UPPER(TRIM(CAST(t.uuid AS TEXT))),'<<NULL>>') AS uuid,
              CASE WHEN t.exclude_from_api IS NULL THEN '<<NULL>>' WHEN t.exclude_from_api IS TRUE THEN 'TRUE' WHEN t.exclude_from_api IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS exclude_from_api,
              COALESCE(TRIM(t.sort_string),'<<NULL>>') AS sort_string,
              COALESCE(CAST(t.rate_plan_id AS TEXT),'<<NULL>>') AS rate_plan_id,
              COALESCE(CAST(CAST(t.managed_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS managed_rate,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted IS TRUE THEN 'TRUE' WHEN t.deleted IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(CAST(t.deleted_by_id AS TEXT),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.combination_lock_number),'<<NULL>>') AS combination_lock_number,
              COALESCE(CAST(t.unit_group_id AS TEXT),'<<NULL>>') AS unit_group_id,
              COALESCE(TRIM(t.attribute_description),'<<NULL>>') AS attribute_description,
              COALESCE(CAST(t.area AS TEXT),'<<NULL>>') AS area,
              COALESCE(CAST(t.unoccupied_rate_plan_id AS TEXT),'<<NULL>>') AS unoccupied_rate_plan_id,
              CASE WHEN t.company_owned IS NULL THEN '<<NULL>>' WHEN t.company_owned IS TRUE THEN 'TRUE' WHEN t.company_owned IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS company_owned,
              CASE WHEN t.manually_set_area IS NULL THEN '<<NULL>>' WHEN t.manually_set_area IS TRUE THEN 'TRUE' WHEN t.manually_set_area IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS manually_set_area,
              COALESCE(TRIM(t.directions),'<<NULL>>') AS directions,
              COALESCE(CAST(t.combo_lock_group_id AS TEXT),'<<NULL>>') AS combo_lock_group_id,
              CASE WHEN t.needs_prepped IS NULL THEN '<<NULL>>' WHEN t.needs_prepped IS TRUE THEN 'TRUE' WHEN t.needs_prepped IS FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS needs_prepped,
              COALESCE(TRIM(t.overlock_lock_number),'<<NULL>>') AS overlock_lock_number,
              COALESCE(CAST(t.rank AS TEXT),'<<NULL>>') AS rank,
              COALESCE(CAST(t.tier_id AS TEXT),'<<NULL>>') AS tier_id,
              COALESCE(CAST(t.unit_group_tier_rate_id AS TEXT),'<<NULL>>') AS unit_group_tier_rate_id,
              COALESCE(CAST(CAST(t.tiered_rate AS NUMERIC(38,2)) AS TEXT),'<<NULL>>') AS tiered_rate,
              COALESCE(CAST(t.allow_future_move_ins_limit AS TEXT),'<<NULL>>') AS allow_future_move_ins_limit
          FROM public.units t
          JOIN public.facilities f ON t.facility_id = f.id
          WHERE f.company_id IN (137,9088,501);
        target_table_name: units
        target: snowflake
        targetcolumn: id
        targetquery: |-
          SELECT
              COALESCE(TO_VARCHAR(t.id),'<<NULL>>') AS id,
              COALESCE(TRIM(t.name),'<<NULL>>') AS name,
              COALESCE(TRIM(t.status),'<<NULL>>') AS status,
              CASE WHEN t.damaged IS NULL THEN '<<NULL>>' WHEN t.damaged = TRUE THEN 'TRUE' WHEN t.damaged = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS damaged,
              CASE WHEN t.dirty IS NULL THEN '<<NULL>>' WHEN t.dirty = TRUE THEN 'TRUE' WHEN t.dirty = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS dirty,
              CASE WHEN t.rentable IS NULL THEN '<<NULL>>' WHEN t.rentable = TRUE THEN 'TRUE' WHEN t.rentable = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS rentable,
              COALESCE(TO_CHAR(t.available_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS available_on,
              COALESCE(TO_VARCHAR(t.width),'<<NULL>>') AS width,
              COALESCE(TO_VARCHAR(t.height),'<<NULL>>') AS height,
              COALESCE(TO_VARCHAR(t.length),'<<NULL>>') AS length,
              COALESCE(TO_VARCHAR(t.standard_rate),'<<NULL>>') AS standard_rate,
              COALESCE(TO_VARCHAR(t.door_width),'<<NULL>>') AS door_width,
              COALESCE(TO_VARCHAR(t.door_height),'<<NULL>>') AS door_height,
              COALESCE(TRIM(t.door_type),'<<NULL>>') AS door_type,
              COALESCE(TRIM(t.access_type),'<<NULL>>') AS access_type,
              COALESCE(TO_VARCHAR(t.floor),'<<NULL>>') AS floor,
              COALESCE(TO_VARCHAR(t.tax_id),'<<NULL>>') AS tax_id,
              COALESCE(TO_VARCHAR(t.unit_type_id),'<<NULL>>') AS unit_type_id,
              COALESCE(TO_VARCHAR(t.facility_id),'<<NULL>>') AS facility_id,
              COALESCE(TO_CHAR(t.created_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS created_at,
              COALESCE(TO_CHAR(t.updated_at,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS updated_at,
              COALESCE(TO_VARCHAR(t.walk_thru_order),'<<NULL>>') AS walk_thru_order,
              COALESCE(TRIM(t.uuid),'<<NULL>>') AS uuid,
              CASE WHEN t.exclude_from_api IS NULL THEN '<<NULL>>' WHEN t.exclude_from_api = TRUE THEN 'TRUE' WHEN t.exclude_from_api = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS exclude_from_api,
              COALESCE(TRIM(t.sort_string),'<<NULL>>') AS sort_string,
              COALESCE(TO_VARCHAR(t.rate_plan_id),'<<NULL>>') AS rate_plan_id,
              COALESCE(TO_VARCHAR(t.managed_rate),'<<NULL>>') AS managed_rate,
              CASE WHEN t.deleted IS NULL THEN '<<NULL>>' WHEN t.deleted = TRUE THEN 'TRUE' WHEN t.deleted = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS deleted,
              COALESCE(TO_CHAR(t.deleted_on,'YYYY-MM-DD HH24:MI:SS.FF3'),'<<NULL>>') AS deleted_on,
              COALESCE(TO_VARCHAR(t.deleted_by_id),'<<NULL>>') AS deleted_by_id,
              COALESCE(TRIM(t.combination_lock_number),'<<NULL>>') AS combination_lock_number,
              COALESCE(TO_VARCHAR(t.unit_group_id),'<<NULL>>') AS unit_group_id,
              COALESCE(TRIM(t.attribute_description),'<<NULL>>') AS attribute_description,
              COALESCE(TO_VARCHAR(t.area),'<<NULL>>') AS area,
              COALESCE(TO_VARCHAR(t.unoccupied_rate_plan_id),'<<NULL>>') AS unoccupied_rate_plan_id,
              CASE WHEN t.company_owned IS NULL THEN '<<NULL>>' WHEN t.company_owned = TRUE THEN 'TRUE' WHEN t.company_owned = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS company_owned,
              CASE WHEN t.manually_set_area IS NULL THEN '<<NULL>>' WHEN t.manually_set_area = TRUE THEN 'TRUE' WHEN t.manually_set_area = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS manually_set_area,
              COALESCE(TRIM(t.directions),'<<NULL>>') AS directions,
              COALESCE(TO_VARCHAR(t.combo_lock_group_id),'<<NULL>>') AS combo_lock_group_id,
              CASE WHEN t.needs_prepped IS NULL THEN '<<NULL>>' WHEN t.needs_prepped = TRUE THEN 'TRUE' WHEN t.needs_prepped = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS needs_prepped,
              COALESCE(TRIM(t.overlock_lock_number),'<<NULL>>') AS overlock_lock_number,
              COALESCE(TO_VARCHAR(t.rank),'<<NULL>>') AS rank,
              COALESCE(TO_VARCHAR(t.tier_id),'<<NULL>>') AS tier_id,
              COALESCE(TO_VARCHAR(t.unit_group_tier_rate_id),'<<NULL>>') AS unit_group_tier_rate_id,
              COALESCE(TO_VARCHAR(t.tiered_rate),'<<NULL>>') AS tiered_rate,
              COALESCE(TO_VARCHAR(t.allow_future_move_ins_limit),'<<NULL>>') AS allow_future_move_ins_limit
          FROM {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.units t
          JOIN {env}_EDGE_BRONZE.STOREDGE_FMS_PUBLIC.facilities f ON t.facility_id = f.id
          WHERE t._FIVETRAN_ACTIVE = TRUE AND f.company_id IN (137,9088,501)
