tables:
  AcctTypes:
    validations:
      data_validation:
        source_table_name: AcctTypes
        source: mssql
        sourcecolumn: AcctTypeID
        sourcequery: |
          SELECT
              COALESCE(CAST(AcctTypeID AS VARCHAR(100)),'<<NULL>>') AS AcctTypeID,
              COALESCE(CAST(AcctType_TermID AS VARCHAR(100)),'<<NULL>>') AS AcctType_TermID,
              COALESCE(LTRIM(RTRIM(sDefAcctTypeName)),'<<NULL>>') AS sDefAcctTypeName,
              COALESCE(LTRIM(RTRIM(sAcctTypeName)),'<<NULL>>') AS sAcctTypeName,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM dbo.AcctTypes;
        target_table_name: AcctTypes
        target: snowflake
        targetcolumn: AcctTypeID
        targetquery: |
          SELECT
              COALESCE(CAST(AcctTypeID AS VARCHAR(100)),'<<NULL>>') AS AcctTypeID,
              COALESCE(CAST(AcctType_TermID AS VARCHAR(100)),'<<NULL>>') AS AcctType_TermID,
              COALESCE(TRIM(sDefAcctTypeName),'<<NULL>>') AS sDefAcctTypeName,
              COALESCE(TRIM(sAcctTypeName),'<<NULL>>') AS sAcctTypeName,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.AcctTypes
          WHERE _FIVETRAN_ACTIVE = TRUE;
