tables:
  Addresses:
    validations:
      data_validation:
        source_table_name: Addresses
        source: mssql
        sourcecolumn: AddressID
        sourcequery: |
          SELECT
              COALESCE(CAST(AddressID AS VARCHAR(100)),'<<NULL>>') AS AddressID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(LTRIM(RTRIM(sMrMrs)),'<<NULL>>') AS sMrMrs,
              COALESCE(LTRIM(RTRIM(sFName)),'<<NULL>>') AS sFName,
              COALESCE(LTRIM(RTRIM(sMI)),'<<NULL>>') AS sMI,
              COALESCE(LTRIM(RTRIM(sLName)),'<<NULL>>') AS sLName,
              COALESCE(LTRIM(RTRIM(sCompany)),'<<NULL>>') AS sCompany,
              COALESCE(LTRIM(RTRIM(sAddr1)),'<<NULL>>') AS sAddr1,
              COALESCE(LTRIM(RTRIM(sAddr2)),'<<NULL>>') AS sAddr2,
              COALESCE(LTRIM(RTRIM(sCity)),'<<NULL>>') AS sCity,
              COALESCE(LTRIM(RTRIM(sRegion)),'<<NULL>>') AS sRegion,
              COALESCE(LTRIM(RTRIM(sPostalCode)),'<<NULL>>') AS sPostalCode,
              COALESCE(LTRIM(RTRIM(sCountry)),'<<NULL>>') AS sCountry,
              COALESCE(LTRIM(RTRIM(sPhone1)),'<<NULL>>') AS sPhone1,
              COALESCE(LTRIM(RTRIM(sPhone2)),'<<NULL>>') AS sPhone2,
              COALESCE(LTRIM(RTRIM(sPhone3)),'<<NULL>>') AS sPhone3,
              COALESCE(LTRIM(RTRIM(sPhone4)),'<<NULL>>') AS sPhone4,
              COALESCE(LTRIM(RTRIM(sPhone5)),'<<NULL>>') AS sPhone5,
              COALESCE(LTRIM(RTRIM(sPhone6)),'<<NULL>>') AS sPhone6,
              COALESCE(CAST(dcLongitude AS VARCHAR(100)),'<<NULL>>') AS dcLongitude,
              COALESCE(CAST(dcLatitude AS VARCHAR(100)),'<<NULL>>') AS dcLatitude,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM dbo.Addresses;
        target_table_name: Addresses
        target: snowflake
        targetcolumn: AddressID
        targetquery: |
          SELECT
              COALESCE(CAST(AddressID AS VARCHAR(100)),'<<NULL>>') AS AddressID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(TRIM(sMrMrs),'<<NULL>>') AS sMrMrs,
              COALESCE(TRIM(sFName),'<<NULL>>') AS sFName,
              COALESCE(TRIM(sMI),'<<NULL>>') AS sMI,
              COALESCE(TRIM(sLName),'<<NULL>>') AS sLName,
              COALESCE(TRIM(sCompany),'<<NULL>>') AS sCompany,
              COALESCE(TRIM(sAddr1),'<<NULL>>') AS sAddr1,
              COALESCE(TRIM(sAddr2),'<<NULL>>') AS sAddr2,
              COALESCE(TRIM(sCity),'<<NULL>>') AS sCity,
              COALESCE(TRIM(sRegion),'<<NULL>>') AS sRegion,
              COALESCE(TRIM(sPostalCode),'<<NULL>>') AS sPostalCode,
              COALESCE(TRIM(sCountry),'<<NULL>>') AS sCountry,
              COALESCE(TRIM(sPhone1),'<<NULL>>') AS sPhone1,
              COALESCE(TRIM(sPhone2),'<<NULL>>') AS sPhone2,
              COALESCE(TRIM(sPhone3),'<<NULL>>') AS sPhone3,
              COALESCE(TRIM(sPhone4),'<<NULL>>') AS sPhone4,
              COALESCE(TRIM(sPhone5),'<<NULL>>') AS sPhone5,
              COALESCE(TRIM(sPhone6),'<<NULL>>') AS sPhone6,
              COALESCE(CAST(dcLongitude AS VARCHAR(100)),'<<NULL>>') AS dcLongitude,
              COALESCE(CAST(dcLatitude AS VARCHAR(100)),'<<NULL>>') AS dcLatitude,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Addresses
          WHERE _FIVETRAN_ACTIVE = TRUE;
