tables:
  CallsAndLetters:
    validations:
      data_validation:
        source_table_name: CallsAndLetters
        source: mssql
        sourcecolumn: CallsAndLettersID
        sourcequery: |
          SELECT
              COALESCE(CAST(CallsAndLettersID AS VARCHAR(100)),'<<NULL>>') AS CallsAndLettersID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CONVERT(VARCHAR(26),CAST(dOccurred AS DATETIME2(6)),121),'<<NULL>>') AS dOccurred,
              COALESCE(LTRIM(RTRIM(sDesc)),'<<NULL>>') AS sDesc,
              CASE WHEN bMoveIn IS NULL THEN '<<NULL>>' WHEN bMoveIn = 1 THEN 'TRUE' WHEN bMoveIn = 0 THEN 'FALSE' END AS bMoveIn,
              CASE WHEN bLetter IS NULL THEN '<<NULL>>' WHEN bLetter = 1 THEN 'TRUE' WHEN bLetter = 0 THEN 'FALSE' END AS bLetter,
              COALESCE(CAST(iType AS VARCHAR(100)),'<<NULL>>') AS iType,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              COALESCE(CAST(CorpUserID AS VARCHAR(100)),'<<NULL>>') AS CorpUserID
          FROM dbo.CallsAndLetters;
        target_table_name: CallsAndLetters
        target: snowflake
        targetcolumn: CallsAndLettersID
        targetquery: |
          SELECT
              COALESCE(CAST(CallsAndLettersID AS VARCHAR(100)),'<<NULL>>') AS CallsAndLettersID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(TO_CHAR(dOccurred,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dOccurred,
              COALESCE(TRIM(sDesc),'<<NULL>>') AS sDesc,
              CASE WHEN bMoveIn IS NULL THEN '<<NULL>>' WHEN bMoveIn = TRUE THEN 'TRUE' WHEN bMoveIn = FALSE THEN 'FALSE' END AS bMoveIn,
              CASE WHEN bLetter IS NULL THEN '<<NULL>>' WHEN bLetter = TRUE THEN 'TRUE' WHEN bLetter = FALSE THEN 'FALSE' END AS bLetter,
              COALESCE(CAST(iType AS VARCHAR(100)),'<<NULL>>') AS iType,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              COALESCE(CAST(CorpUserID AS VARCHAR(100)),'<<NULL>>') AS CorpUserID
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.CallsAndLetters
          WHERE _FIVETRAN_ACTIVE = TRUE;
