tables:
  Charges:
    validations:
      data_validation:
        source_table_name: Charges
        source: mssql
        sourcecolumn: ChargeID
        sourcequery: |
          SELECT
              COALESCE(CAST(ChargeID AS VARCHAR(100)),'<<NULL>>') AS ChargeID,
              COALESCE(CAST(ChargeDescID AS VARCHAR(100)),'<<NULL>>') AS ChargeDescID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(InsurLedgerID AS VARCHAR(100)),'<<NULL>>') AS InsurLedgerID,
              COALESCE(CAST(FiscalID AS VARCHAR(100)),'<<NULL>>') AS FiscalID,
              COALESCE(CAST(ConcessionID AS VARCHAR(100)),'<<NULL>>') AS ConcessionID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(ACHID AS VARCHAR(100)),'<<NULL>>') AS ACHID,
              COALESCE(CAST(Disc_MemoID AS VARCHAR(100)),'<<NULL>>') AS Disc_MemoID,
              COALESCE(CAST(dcAmt AS VARCHAR(100)),'<<NULL>>') AS dcAmt,
              COALESCE(CAST(dcTax1 AS VARCHAR(100)),'<<NULL>>') AS dcTax1,
              COALESCE(CAST(dcTax2 AS VARCHAR(100)),'<<NULL>>') AS dcTax2,
              COALESCE(CAST(dcQty AS VARCHAR(100)),'<<NULL>>') AS dcQty,
              COALESCE(CAST(dcStdPrice AS VARCHAR(100)),'<<NULL>>') AS dcStdPrice,
              COALESCE(CAST(dcPrice AS VARCHAR(100)),'<<NULL>>') AS dcPrice,
              COALESCE(CAST(dcCost AS VARCHAR(100)),'<<NULL>>') AS dcCost,
              COALESCE(CONVERT(VARCHAR(26),CAST(dChgStrt AS DATETIME2(6)),121),'<<NULL>>') AS dChgStrt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dChgEnd AS DATETIME2(6)),121),'<<NULL>>') AS dChgEnd,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              CASE WHEN bMoveIn IS NULL THEN '<<NULL>>' WHEN bMoveIn = 1 THEN 'TRUE' WHEN bMoveIn = 0 THEN 'FALSE' END AS bMoveIn,
              CASE WHEN bMoveOut IS NULL THEN '<<NULL>>' WHEN bMoveOut = 1 THEN 'TRUE' WHEN bMoveOut = 0 THEN 'FALSE' END AS bMoveOut,
              CASE WHEN bNSF IS NULL THEN '<<NULL>>' WHEN bNSF = 1 THEN 'TRUE' WHEN bNSF = 0 THEN 'FALSE' END AS bNSF,
              COALESCE(CAST(ReceiptID_NSF AS VARCHAR(100)),'<<NULL>>') AS ReceiptID_NSF,
              COALESCE(CAST(QTChargeID AS VARCHAR(100)),'<<NULL>>') AS QTChargeID,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CAST(dcPriceTax1 AS VARCHAR(100)),'<<NULL>>') AS dcPriceTax1,
              COALESCE(CAST(dcPriceTax2 AS VARCHAR(100)),'<<NULL>>') AS dcPriceTax2,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              COALESCE(CAST(iNSFFlag AS VARCHAR(100)),'<<NULL>>') AS iNSFFlag
          FROM dbo.Charges;
        target_table_name: Charges
        target: snowflake
        targetcolumn: ChargeID
        targetquery: |
          SELECT
              COALESCE(CAST(ChargeID AS VARCHAR(100)),'<<NULL>>') AS ChargeID,
              COALESCE(CAST(ChargeDescID AS VARCHAR(100)),'<<NULL>>') AS ChargeDescID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(InsurLedgerID AS VARCHAR(100)),'<<NULL>>') AS InsurLedgerID,
              COALESCE(CAST(FiscalID AS VARCHAR(100)),'<<NULL>>') AS FiscalID,
              COALESCE(CAST(ConcessionID AS VARCHAR(100)),'<<NULL>>') AS ConcessionID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(ACHID AS VARCHAR(100)),'<<NULL>>') AS ACHID,
              COALESCE(CAST(Disc_MemoID AS VARCHAR(100)),'<<NULL>>') AS Disc_MemoID,
              COALESCE(CAST(dcAmt AS VARCHAR(100)),'<<NULL>>') AS dcAmt,
              COALESCE(CAST(dcTax1 AS VARCHAR(100)),'<<NULL>>') AS dcTax1,
              COALESCE(CAST(dcTax2 AS VARCHAR(100)),'<<NULL>>') AS dcTax2,
              COALESCE(CAST(dcQty AS VARCHAR(100)),'<<NULL>>') AS dcQty,
              COALESCE(CAST(dcStdPrice AS VARCHAR(100)),'<<NULL>>') AS dcStdPrice,
              COALESCE(CAST(dcPrice AS VARCHAR(100)),'<<NULL>>') AS dcPrice,
              COALESCE(CAST(dcCost AS VARCHAR(100)),'<<NULL>>') AS dcCost,
              COALESCE(TO_CHAR(dChgStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dChgStrt,
              COALESCE(TO_CHAR(dChgEnd,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dChgEnd,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              CASE WHEN bMoveIn IS NULL THEN '<<NULL>>' WHEN bMoveIn = TRUE THEN 'TRUE' WHEN bMoveIn = FALSE THEN 'FALSE' END AS bMoveIn,
              CASE WHEN bMoveOut IS NULL THEN '<<NULL>>' WHEN bMoveOut = TRUE THEN 'TRUE' WHEN bMoveOut = FALSE THEN 'FALSE' END AS bMoveOut,
              CASE WHEN bNSF IS NULL THEN '<<NULL>>' WHEN bNSF = TRUE THEN 'TRUE' WHEN bNSF = FALSE THEN 'FALSE' END AS bNSF,
              COALESCE(CAST(ReceiptID_NSF AS VARCHAR(100)),'<<NULL>>') AS ReceiptID_NSF,
              COALESCE(CAST(QTChargeID AS VARCHAR(100)),'<<NULL>>') AS QTChargeID,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CAST(dcPriceTax1 AS VARCHAR(100)),'<<NULL>>') AS dcPriceTax1,
              COALESCE(CAST(dcPriceTax2 AS VARCHAR(100)),'<<NULL>>') AS dcPriceTax2,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              COALESCE(CAST(iNSFFlag AS VARCHAR(100)),'<<NULL>>') AS iNSFFlag
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Charges
          WHERE _FIVETRAN_ACTIVE = TRUE;
