tables:
  PromoRentals:
    validations:
      data_validation:
        source_table_name: PromoRentals
        source: mssql
        sourcecolumn: PromoRentalID
        sourcequery: |
          SELECT
              COALESCE(CAST(PromoRentalID AS VARCHAR(100)),'<<NULL>>') AS PromoRentalID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(TenantID AS VARCHAR(100)),'<<NULL>>') AS TenantID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(iPromoGlobalNum_First AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum_First,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              COALESCE(CAST(PromoFirst_PromoAccountID AS VARCHAR(100)),'<<NULL>>') AS PromoFirst_PromoAccountID,
              COALESCE(LTRIM(RTRIM(sPromoFirst_TrackingSuffix)),'<<NULL>>') AS sPromoFirst_TrackingSuffix,
              COALESCE(CAST(PromoApplied_PromoAccountID AS VARCHAR(100)),'<<NULL>>') AS PromoApplied_PromoAccountID,
              COALESCE(LTRIM(RTRIM(sPromoApplied_TrackingSuffix)),'<<NULL>>') AS sPromoApplied_TrackingSuffix,
              CASE WHEN bPromotionApplied IS NULL THEN '<<NULL>>' WHEN bPromotionApplied = 1 THEN 'TRUE' WHEN bPromotionApplied = 0 THEN 'FALSE' END AS bPromotionApplied,
              COALESCE(CONVERT(VARCHAR(26),CAST(dPromoModified AS DATETIME2(6)),121),'<<NULL>>') AS dPromoModified,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM dbo.PromoRentals;
        target_table_name: PromoRentals
        target: snowflake
        targetcolumn: PromoRentalID
        targetquery: |
          SELECT
              COALESCE(CAST(PromoRentalID AS VARCHAR(100)),'<<NULL>>') AS PromoRentalID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(TenantID AS VARCHAR(100)),'<<NULL>>') AS TenantID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(iPromoGlobalNum_First AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum_First,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              COALESCE(CAST(PromoFirst_PromoAccountID AS VARCHAR(100)),'<<NULL>>') AS PromoFirst_PromoAccountID,
              COALESCE(TRIM(sPromoFirst_TrackingSuffix),'<<NULL>>') AS sPromoFirst_TrackingSuffix,
              COALESCE(CAST(PromoApplied_PromoAccountID AS VARCHAR(100)),'<<NULL>>') AS PromoApplied_PromoAccountID,
              COALESCE(TRIM(sPromoApplied_TrackingSuffix),'<<NULL>>') AS sPromoApplied_TrackingSuffix,
              CASE WHEN bPromotionApplied IS NULL THEN '<<NULL>>' WHEN bPromotionApplied = TRUE THEN 'TRUE' WHEN bPromotionApplied = FALSE THEN 'FALSE' END AS bPromotionApplied,
              COALESCE(TO_CHAR(dPromoModified,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dPromoModified,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.PromoRentals
          WHERE _FIVETRAN_ACTIVE = TRUE;
