tables:
  Promotions:
    validations:
      data_validation:
        source_table_name: Promotions
        source: mssql
        sourcecolumn: PromotionID
        sourcequery: |
          SELECT
              COALESCE(CAST(PromotionID AS VARCHAR(100)),'<<NULL>>') AS PromotionID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              CASE WHEN bWebEditable IS NULL THEN '<<NULL>>' WHEN bWebEditable = 1 THEN 'TRUE' WHEN bWebEditable = 0 THEN 'FALSE' END AS bWebEditable,
              COALESCE(LTRIM(RTRIM(sCorpCode)),'<<NULL>>') AS sCorpCode,
              CASE WHEN bSiteIsEligible IS NULL THEN '<<NULL>>' WHEN bSiteIsEligible = 1 THEN 'TRUE' WHEN bSiteIsEligible = 0 THEN 'FALSE' END AS bSiteIsEligible,
              COALESCE(CAST(PromoAccountID AS VARCHAR(100)),'<<NULL>>') AS PromoAccountID,
              COALESCE(CAST(PromoChannelID AS VARCHAR(100)),'<<NULL>>') AS PromoChannelID,
              COALESCE(CAST(PromoFormatsID AS VARCHAR(100)),'<<NULL>>') AS PromoFormatsID,
              COALESCE(CAST(PromoCampaignID AS VARCHAR(100)),'<<NULL>>') AS PromoCampaignID,
              COALESCE(CAST(PromoTypeID AS VARCHAR(100)),'<<NULL>>') AS PromoTypeID,
              COALESCE(CAST(PromoOfferID AS VARCHAR(100)),'<<NULL>>') AS PromoOfferID,
              COALESCE(LTRIM(RTRIM(sGlobalSiteNum)),'<<NULL>>') AS sGlobalSiteNum,
              COALESCE(CONVERT(VARCHAR(26),CAST(dMaterialsDrop AS DATETIME2(6)),121),'<<NULL>>') AS dMaterialsDrop,
              COALESCE(CONVERT(VARCHAR(26),CAST(dPromoStrt AS DATETIME2(6)),121),'<<NULL>>') AS dPromoStrt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dPromoEnd AS DATETIME2(6)),121),'<<NULL>>') AS dPromoEnd,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              COALESCE(LTRIM(RTRIM(sPromotionCode)),'<<NULL>>') AS sPromotionCode,
              COALESCE(LTRIM(RTRIM(sPromoDescription)),'<<NULL>>') AS sPromoDescription,
              COALESCE(LTRIM(RTRIM(sPromoComment)),'<<NULL>>') AS sPromoComment,
              COALESCE(LTRIM(RTRIM(sWebDesc)),'<<NULL>>') AS sWebDesc,
              COALESCE(CAST(dcMarketingDollars AS VARCHAR(100)),'<<NULL>>') AS dcMarketingDollars,
              CASE WHEN bGeneric IS NULL THEN '<<NULL>>' WHEN bGeneric = 1 THEN 'TRUE' WHEN bGeneric = 0 THEN 'FALSE' END AS bGeneric,
              CASE WHEN bWebOnly IS NULL THEN '<<NULL>>' WHEN bWebOnly = 1 THEN 'TRUE' WHEN bWebOnly = 0 THEN 'FALSE' END AS bWebOnly,
              CASE WHEN bWebExcluded IS NULL THEN '<<NULL>>' WHEN bWebExcluded = 1 THEN 'TRUE' WHEN bWebExcluded = 0 THEN 'FALSE' END AS bWebExcluded,
              CASE WHEN bSuffixRequired IS NULL THEN '<<NULL>>' WHEN bSuffixRequired = 1 THEN 'TRUE' WHEN bSuffixRequired = 0 THEN 'FALSE' END AS bSuffixRequired,
              COALESCE(LTRIM(RTRIM(sSuffix)),'<<NULL>>') AS sSuffix,
              COALESCE(CAST(iManagedBy_CorpUserID AS VARCHAR(100)),'<<NULL>>') AS iManagedBy_CorpUserID,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              CASE WHEN bApproved IS NULL THEN '<<NULL>>' WHEN bApproved = 1 THEN 'TRUE' WHEN bApproved = 0 THEN 'FALSE' END AS bApproved,
              COALESCE(CONVERT(VARCHAR(26),CAST(dApproved AS DATETIME2(6)),121),'<<NULL>>') AS dApproved,
              CASE WHEN bForAllSites IS NULL THEN '<<NULL>>' WHEN bForAllSites = 1 THEN 'TRUE' WHEN bForAllSites = 0 THEN 'FALSE' END AS bForAllSites,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDisabled AS DATETIME2(6)),121),'<<NULL>>') AS dDisabled,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM dbo.Promotions;
        target_table_name: Promotions
        target: snowflake
        targetcolumn: PromotionID
        targetquery: |
          SELECT
              COALESCE(CAST(PromotionID AS VARCHAR(100)),'<<NULL>>') AS PromotionID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              CASE WHEN bWebEditable IS NULL THEN '<<NULL>>' WHEN bWebEditable = TRUE THEN 'TRUE' WHEN bWebEditable = FALSE THEN 'FALSE' END AS bWebEditable,
              COALESCE(TRIM(sCorpCode),'<<NULL>>') AS sCorpCode,
              CASE WHEN bSiteIsEligible IS NULL THEN '<<NULL>>' WHEN bSiteIsEligible = TRUE THEN 'TRUE' WHEN bSiteIsEligible = FALSE THEN 'FALSE' END AS bSiteIsEligible,
              COALESCE(CAST(PromoAccountID AS VARCHAR(100)),'<<NULL>>') AS PromoAccountID,
              COALESCE(CAST(PromoChannelID AS VARCHAR(100)),'<<NULL>>') AS PromoChannelID,
              COALESCE(CAST(PromoFormatsID AS VARCHAR(100)),'<<NULL>>') AS PromoFormatsID,
              COALESCE(CAST(PromoCampaignID AS VARCHAR(100)),'<<NULL>>') AS PromoCampaignID,
              COALESCE(CAST(PromoTypeID AS VARCHAR(100)),'<<NULL>>') AS PromoTypeID,
              COALESCE(CAST(PromoOfferID AS VARCHAR(100)),'<<NULL>>') AS PromoOfferID,
              COALESCE(TRIM(sGlobalSiteNum),'<<NULL>>') AS sGlobalSiteNum,
              COALESCE(TO_CHAR(dMaterialsDrop,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dMaterialsDrop,
              COALESCE(TO_CHAR(dPromoStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dPromoStrt,
              COALESCE(TO_CHAR(dPromoEnd,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dPromoEnd,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              COALESCE(TRIM(sPromotionCode),'<<NULL>>') AS sPromotionCode,
              COALESCE(TRIM(sPromoDescription),'<<NULL>>') AS sPromoDescription,
              COALESCE(TRIM(sPromoComment),'<<NULL>>') AS sPromoComment,
              COALESCE(TRIM(sWebDesc),'<<NULL>>') AS sWebDesc,
              COALESCE(CAST(dcMarketingDollars AS VARCHAR(100)),'<<NULL>>') AS dcMarketingDollars,
              CASE WHEN bGeneric IS NULL THEN '<<NULL>>' WHEN bGeneric = TRUE THEN 'TRUE' WHEN bGeneric = FALSE THEN 'FALSE' END AS bGeneric,
              CASE WHEN bWebOnly IS NULL THEN '<<NULL>>' WHEN bWebOnly = TRUE THEN 'TRUE' WHEN bWebOnly = FALSE THEN 'FALSE' END AS bWebOnly,
              CASE WHEN bWebExcluded IS NULL THEN '<<NULL>>' WHEN bWebExcluded = TRUE THEN 'TRUE' WHEN bWebExcluded = FALSE THEN 'FALSE' END AS bWebExcluded,
              CASE WHEN bSuffixRequired IS NULL THEN '<<NULL>>' WHEN bSuffixRequired = TRUE THEN 'TRUE' WHEN bSuffixRequired = FALSE THEN 'FALSE' END AS bSuffixRequired,
              COALESCE(TRIM(sSuffix),'<<NULL>>') AS sSuffix,
              COALESCE(CAST(iManagedBy_CorpUserID AS VARCHAR(100)),'<<NULL>>') AS iManagedBy_CorpUserID,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              CASE WHEN bApproved IS NULL THEN '<<NULL>>' WHEN bApproved = TRUE THEN 'TRUE' WHEN bApproved = FALSE THEN 'FALSE' END AS bApproved,
              COALESCE(TO_CHAR(dApproved,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dApproved,
              CASE WHEN bForAllSites IS NULL THEN '<<NULL>>' WHEN bForAllSites = TRUE THEN 'TRUE' WHEN bForAllSites = FALSE THEN 'FALSE' END AS bForAllSites,
              COALESCE(TO_CHAR(dDisabled,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDisabled,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Promotions
          WHERE _FIVETRAN_ACTIVE = TRUE;
