tables:
  PromoOffers:
    validations:
      data_validation:
        source_table_name: PromoOffers
        source: mssql
        sourcecolumn: PromoOfferID
        sourcequery: |
          SELECT
              COALESCE(CAST(PromoOfferID AS VARCHAR(100)),'<<NULL>>') AS PromoOfferID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(iPromoOfferGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoOfferGlobalNum,
              COALESCE(LTRIM(RTRIM(sCorpCode)),'<<NULL>>') AS sCorpCode,
              COALESCE(CAST(PromoOfferCatID AS VARCHAR(100)),'<<NULL>>') AS PromoOfferCatID,
              COALESCE(LTRIM(RTRIM(sOfferDesc)),'<<NULL>>') AS sOfferDesc,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDisabled AS DATETIME2(6)),121),'<<NULL>>') AS dDisabled,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM dbo.PromoOffers;
        target_table_name: PromoOffers
        target: snowflake
        targetcolumn: PromoOfferID
        targetquery: |
          SELECT
              COALESCE(CAST(PromoOfferID AS VARCHAR(100)),'<<NULL>>') AS PromoOfferID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(iPromoOfferGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoOfferGlobalNum,
              COALESCE(TRIM(sCorpCode),'<<NULL>>') AS sCorpCode,
              COALESCE(CAST(PromoOfferCatID AS VARCHAR(100)),'<<NULL>>') AS PromoOfferCatID,
              COALESCE(TRIM(sOfferDesc),'<<NULL>>') AS sOfferDesc,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              COALESCE(TO_CHAR(dDisabled,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDisabled,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.PromoOffers
          WHERE _FIVETRAN_ACTIVE = TRUE;
