tables:
  Reports:
    validations:
      data_validation:
        source_table_name: Reports
        source: mssql
        sourcecolumn: ReportID
        sourcequery: |
          SELECT
              COALESCE(CAST(ReportID AS VARCHAR(100)),'<<NULL>>') AS ReportID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(iPeriod AS VARCHAR(100)),'<<NULL>>') AS iPeriod,
              COALESCE(CAST(iPeriodRestrictedTo AS VARCHAR(100)),'<<NULL>>') AS iPeriodRestrictedTo,
              COALESCE(CAST(Report_TermID AS VARCHAR(100)),'<<NULL>>') AS Report_TermID,
              COALESCE(LTRIM(RTRIM(sCategory)),'<<NULL>>') AS sCategory,
              CASE WHEN bStartOfDay IS NULL THEN '<<NULL>>' WHEN bStartOfDay = 1 THEN 'TRUE' WHEN bStartOfDay = 0 THEN 'FALSE' END AS bStartOfDay,
              CASE WHEN bEndOfDay IS NULL THEN '<<NULL>>' WHEN bEndOfDay = 1 THEN 'TRUE' WHEN bEndOfDay = 0 THEN 'FALSE' END AS bEndOfDay,
              CASE WHEN bEndOfMonth IS NULL THEN '<<NULL>>' WHEN bEndOfMonth = 1 THEN 'TRUE' WHEN bEndOfMonth = 0 THEN 'FALSE' END AS bEndOfMonth,
              CASE WHEN bDefaultBatch IS NULL THEN '<<NULL>>' WHEN bDefaultBatch = 1 THEN 'TRUE' WHEN bDefaultBatch = 0 THEN 'FALSE' END AS bDefaultBatch,
              CASE WHEN bBatchEmail IS NULL THEN '<<NULL>>' WHEN bBatchEmail = 1 THEN 'TRUE' WHEN bBatchEmail = 0 THEN 'FALSE' END AS bBatchEmail,
              CASE WHEN bBatchPrint IS NULL THEN '<<NULL>>' WHEN bBatchPrint = 1 THEN 'TRUE' WHEN bBatchPrint = 0 THEN 'FALSE' END AS bBatchPrint,
              CASE WHEN bInUse IS NULL THEN '<<NULL>>' WHEN bInUse = 1 THEN 'TRUE' WHEN bInUse = 0 THEN 'FALSE' END AS bInUse,
              CASE WHEN bAvailableForBatch IS NULL THEN '<<NULL>>' WHEN bAvailableForBatch = 1 THEN 'TRUE' WHEN bAvailableForBatch = 0 THEN 'FALSE' END AS bAvailableForBatch,
              COALESCE(CAST(iCopies AS VARCHAR(100)),'<<NULL>>') AS iCopies,
              COALESCE(LTRIM(RTRIM(sEmail_Site_Desc_1)),'<<NULL>>') AS sEmail_Site_Desc_1,
              COALESCE(LTRIM(RTRIM(sEmail_Site_Desc_2)),'<<NULL>>') AS sEmail_Site_Desc_2,
              COALESCE(LTRIM(RTRIM(sEmail_Site_Desc_3)),'<<NULL>>') AS sEmail_Site_Desc_3,
              COALESCE(LTRIM(RTRIM(sEmail_Site_To_1)),'<<NULL>>') AS sEmail_Site_To_1,
              COALESCE(LTRIM(RTRIM(sEmail_Site_To_2)),'<<NULL>>') AS sEmail_Site_To_2,
              COALESCE(LTRIM(RTRIM(sEmail_Site_To_3)),'<<NULL>>') AS sEmail_Site_To_3,
              COALESCE(LTRIM(RTRIM(sEmail_Corp_Desc_1)),'<<NULL>>') AS sEmail_Corp_Desc_1,
              COALESCE(LTRIM(RTRIM(sEmail_Corp_Desc_2)),'<<NULL>>') AS sEmail_Corp_Desc_2,
              COALESCE(LTRIM(RTRIM(sEmail_Corp_Desc_3)),'<<NULL>>') AS sEmail_Corp_Desc_3,
              COALESCE(LTRIM(RTRIM(sEmail_Corp_To_1)),'<<NULL>>') AS sEmail_Corp_To_1,
              COALESCE(LTRIM(RTRIM(sEmail_Corp_To_2)),'<<NULL>>') AS sEmail_Corp_To_2,
              COALESCE(LTRIM(RTRIM(sEmail_Corp_To_3)),'<<NULL>>') AS sEmail_Corp_To_3,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM dbo.Reports;
        target_table_name: Reports
        target: snowflake
        targetcolumn: ReportID
        targetquery: |
          SELECT
              COALESCE(CAST(ReportID AS VARCHAR(100)),'<<NULL>>') AS ReportID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(iPeriod AS VARCHAR(100)),'<<NULL>>') AS iPeriod,
              COALESCE(CAST(iPeriodRestrictedTo AS VARCHAR(100)),'<<NULL>>') AS iPeriodRestrictedTo,
              COALESCE(CAST(Report_TermID AS VARCHAR(100)),'<<NULL>>') AS Report_TermID,
              COALESCE(TRIM(sCategory),'<<NULL>>') AS sCategory,
              CASE WHEN bStartOfDay IS NULL THEN '<<NULL>>' WHEN bStartOfDay = TRUE THEN 'TRUE' WHEN bStartOfDay = FALSE THEN 'FALSE' END AS bStartOfDay,
              CASE WHEN bEndOfDay IS NULL THEN '<<NULL>>' WHEN bEndOfDay = TRUE THEN 'TRUE' WHEN bEndOfDay = FALSE THEN 'FALSE' END AS bEndOfDay,
              CASE WHEN bEndOfMonth IS NULL THEN '<<NULL>>' WHEN bEndOfMonth = TRUE THEN 'TRUE' WHEN bEndOfMonth = FALSE THEN 'FALSE' END AS bEndOfMonth,
              CASE WHEN bDefaultBatch IS NULL THEN '<<NULL>>' WHEN bDefaultBatch = TRUE THEN 'TRUE' WHEN bDefaultBatch = FALSE THEN 'FALSE' END AS bDefaultBatch,
              CASE WHEN bBatchEmail IS NULL THEN '<<NULL>>' WHEN bBatchEmail = TRUE THEN 'TRUE' WHEN bBatchEmail = FALSE THEN 'FALSE' END AS bBatchEmail,
              CASE WHEN bBatchPrint IS NULL THEN '<<NULL>>' WHEN bBatchPrint = TRUE THEN 'TRUE' WHEN bBatchPrint = FALSE THEN 'FALSE' END AS bBatchPrint,
              CASE WHEN bInUse IS NULL THEN '<<NULL>>' WHEN bInUse = TRUE THEN 'TRUE' WHEN bInUse = FALSE THEN 'FALSE' END AS bInUse,
              CASE WHEN bAvailableForBatch IS NULL THEN '<<NULL>>' WHEN bAvailableForBatch = TRUE THEN 'TRUE' WHEN bAvailableForBatch = FALSE THEN 'FALSE' END AS bAvailableForBatch,
              COALESCE(CAST(iCopies AS VARCHAR(100)),'<<NULL>>') AS iCopies,
              COALESCE(TRIM(sEmail_Site_Desc_1),'<<NULL>>') AS sEmail_Site_Desc_1,
              COALESCE(TRIM(sEmail_Site_Desc_2),'<<NULL>>') AS sEmail_Site_Desc_2,
              COALESCE(TRIM(sEmail_Site_Desc_3),'<<NULL>>') AS sEmail_Site_Desc_3,
              COALESCE(TRIM(sEmail_Site_To_1),'<<NULL>>') AS sEmail_Site_To_1,
              COALESCE(TRIM(sEmail_Site_To_2),'<<NULL>>') AS sEmail_Site_To_2,
              COALESCE(TRIM(sEmail_Site_To_3),'<<NULL>>') AS sEmail_Site_To_3,
              COALESCE(TRIM(sEmail_Corp_Desc_1),'<<NULL>>') AS sEmail_Corp_Desc_1,
              COALESCE(TRIM(sEmail_Corp_Desc_2),'<<NULL>>') AS sEmail_Corp_Desc_2,
              COALESCE(TRIM(sEmail_Corp_Desc_3),'<<NULL>>') AS sEmail_Corp_Desc_3,
              COALESCE(TRIM(sEmail_Corp_To_1),'<<NULL>>') AS sEmail_Corp_To_1,
              COALESCE(TRIM(sEmail_Corp_To_2),'<<NULL>>') AS sEmail_Corp_To_2,
              COALESCE(TRIM(sEmail_Corp_To_3),'<<NULL>>') AS sEmail_Corp_To_3,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Reports
          WHERE _FIVETRAN_ACTIVE = TRUE;
