tables:
  Sites:
    validations:
      data_validation:
        source_table_name: Sites
        source: mssql
        sourcecolumn: SiteID
        sourcequery: |
          SELECT
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(OwnerID AS VARCHAR(100)),'<<NULL>>') AS OwnerID,
              COALESCE(CAST(LanguageID AS VARCHAR(100)),'<<NULL>>') AS LanguageID,
              COALESCE(LTRIM(RTRIM(sLocationCode)),'<<NULL>>') AS sLocationCode,
              COALESCE(LTRIM(RTRIM(sGlobalSiteNum)),'<<NULL>>') AS sGlobalSiteNum,
              COALESCE(CAST(iMobileType AS VARCHAR(100)),'<<NULL>>') AS iMobileType,
              COALESCE(CAST(iRegionalOptions AS VARCHAR(100)),'<<NULL>>') AS iRegionalOptions,
              COALESCE(CAST(iOnLineChargeType AS VARCHAR(100)),'<<NULL>>') AS iOnLineChargeType,
              COALESCE(CAST(iGMTTimeOffset AS VARCHAR(100)),'<<NULL>>') AS iGMTTimeOffset,
              COALESCE(LTRIM(RTRIM(sLocationDesc)),'<<NULL>>') AS sLocationDesc,
              COALESCE(LTRIM(RTRIM(sSiteIDCode)),'<<NULL>>') AS sSiteIDCode,
              COALESCE(LTRIM(RTRIM(sSiteRegionCode)),'<<NULL>>') AS sSiteRegionCode,
              COALESCE(LTRIM(RTRIM(sContactName)),'<<NULL>>') AS sContactName,
              COALESCE(LTRIM(RTRIM(sEmailAddress)),'<<NULL>>') AS sEmailAddress,
              COALESCE(LTRIM(RTRIM(sSiteName)),'<<NULL>>') AS sSiteName,
              COALESCE(LTRIM(RTRIM(sSiteAddr1)),'<<NULL>>') AS sSiteAddr1,
              COALESCE(LTRIM(RTRIM(sSiteAddr2)),'<<NULL>>') AS sSiteAddr2,
              COALESCE(LTRIM(RTRIM(sSiteCity)),'<<NULL>>') AS sSiteCity,
              COALESCE(LTRIM(RTRIM(sSiteRegion)),'<<NULL>>') AS sSiteRegion,
              COALESCE(LTRIM(RTRIM(sSitePostalCode)),'<<NULL>>') AS sSitePostalCode,
              COALESCE(LTRIM(RTRIM(sSiteCountry)),'<<NULL>>') AS sSiteCountry,
              COALESCE(LTRIM(RTRIM(sSitePhone)),'<<NULL>>') AS sSitePhone,
              COALESCE(LTRIM(RTRIM(sSiteFAX)),'<<NULL>>') AS sSiteFAX,
              COALESCE(LTRIM(RTRIM(sWebSiteURL)),'<<NULL>>') AS sWebSiteURL,
              COALESCE(CAST(iFeatMaxUnits AS VARCHAR(100)),'<<NULL>>') AS iFeatMaxUnits,
              CASE WHEN bFeatGate IS NULL THEN '<<NULL>>' WHEN bFeatGate = 1 THEN 'TRUE' WHEN bFeatGate = 0 THEN 'FALSE' END AS bFeatGate,
              CASE WHEN bFeatKiosk IS NULL THEN '<<NULL>>' WHEN bFeatKiosk = 1 THEN 'TRUE' WHEN bFeatKiosk = 0 THEN 'FALSE' END AS bFeatKiosk,
              CASE WHEN bFeatRevMgmt IS NULL THEN '<<NULL>>' WHEN bFeatRevMgmt = 1 THEN 'TRUE' WHEN bFeatRevMgmt = 0 THEN 'FALSE' END AS bFeatRevMgmt,
              CASE WHEN bFeatCreditCards IS NULL THEN '<<NULL>>' WHEN bFeatCreditCards = 1 THEN 'TRUE' WHEN bFeatCreditCards = 0 THEN 'FALSE' END AS bFeatCreditCards,
              CASE WHEN bFeatCorpOffice IS NULL THEN '<<NULL>>' WHEN bFeatCorpOffice = 1 THEN 'TRUE' WHEN bFeatCorpOffice = 0 THEN 'FALSE' END AS bFeatCorpOffice,
              CASE WHEN bFeatAccounting IS NULL THEN '<<NULL>>' WHEN bFeatAccounting = 1 THEN 'TRUE' WHEN bFeatAccounting = 0 THEN 'FALSE' END AS bFeatAccounting,
              CASE WHEN bFeatRecordStorage IS NULL THEN '<<NULL>>' WHEN bFeatRecordStorage = 1 THEN 'TRUE' WHEN bFeatRecordStorage = 0 THEN 'FALSE' END AS bFeatRecordStorage,
              CASE WHEN bFeatACH IS NULL THEN '<<NULL>>' WHEN bFeatACH = 1 THEN 'TRUE' WHEN bFeatACH = 0 THEN 'FALSE' END AS bFeatACH,
              CASE WHEN bFeatMobileStorage IS NULL THEN '<<NULL>>' WHEN bFeatMobileStorage = 1 THEN 'TRUE' WHEN bFeatMobileStorage = 0 THEN 'FALSE' END AS bFeatMobileStorage,
              CASE WHEN bFeatPromoAdvanced IS NULL THEN '<<NULL>>' WHEN bFeatPromoAdvanced = 1 THEN 'TRUE' WHEN bFeatPromoAdvanced = 0 THEN 'FALSE' END AS bFeatPromoAdvanced,
              COALESCE(CONVERT(VARCHAR(26),CAST(dACHStatus AS DATETIME2(6)),121),'<<NULL>>') AS dACHStatus,
              CASE WHEN bLiteVersion IS NULL THEN '<<NULL>>' WHEN bLiteVersion = 1 THEN 'TRUE' WHEN bLiteVersion = 0 THEN 'FALSE' END AS bLiteVersion,
              CASE WHEN bTrial IS NULL THEN '<<NULL>>' WHEN bTrial = 1 THEN 'TRUE' WHEN bTrial = 0 THEN 'FALSE' END AS bTrial,
              COALESCE(CONVERT(VARCHAR(26),CAST(dTrialEnds AS DATETIME2(6)),121),'<<NULL>>') AS dTrialEnds,
              CASE WHEN bSubscription IS NULL THEN '<<NULL>>' WHEN bSubscription = 1 THEN 'TRUE' WHEN bSubscription = 0 THEN 'FALSE' END AS bSubscription,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSubscriptionEnds AS DATETIME2(6)),121),'<<NULL>>') AS dSubscriptionEnds,
              CASE WHEN bSiteDisabled IS NULL THEN '<<NULL>>' WHEN bSiteDisabled = 1 THEN 'TRUE' WHEN bSiteDisabled = 0 THEN 'FALSE' END AS bSiteDisabled,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSiteDisabled AS DATETIME2(6)),121),'<<NULL>>') AS dSiteDisabled,
              COALESCE(CONVERT(VARCHAR(26),CAST(dGateUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dGateUpdated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dOvernightProcess AS DATETIME2(6)),121),'<<NULL>>') AS dOvernightProcess,
              COALESCE(CONVERT(VARCHAR(26),CAST(dStartOfDay AS DATETIME2(6)),121),'<<NULL>>') AS dStartOfDay,
              COALESCE(LTRIM(RTRIM(sLegalName)),'<<NULL>>') AS sLegalName,
              CASE WHEN bZipCodeData_Use IS NULL THEN '<<NULL>>' WHEN bZipCodeData_Use = 1 THEN 'TRUE' WHEN bZipCodeData_Use = 0 THEN 'FALSE' END AS bZipCodeData_Use,
              COALESCE(CAST(dcLongitude AS VARCHAR(100)),'<<NULL>>') AS dcLongitude,
              COALESCE(CAST(dcLatitude AS VARCHAR(100)),'<<NULL>>') AS dcLatitude,
              CASE WHEN bClosedWeekdays IS NULL THEN '<<NULL>>' WHEN bClosedWeekdays = 1 THEN 'TRUE' WHEN bClosedWeekdays = 0 THEN 'FALSE' END AS bClosedWeekdays,
              CASE WHEN bClosedSaturday IS NULL THEN '<<NULL>>' WHEN bClosedSaturday = 1 THEN 'TRUE' WHEN bClosedSaturday = 0 THEN 'FALSE' END AS bClosedSaturday,
              CASE WHEN bClosedSunday IS NULL THEN '<<NULL>>' WHEN bClosedSunday = 1 THEN 'TRUE' WHEN bClosedSunday = 0 THEN 'FALSE' END AS bClosedSunday,
              COALESCE(CONVERT(VARCHAR(26),CAST(dWeekdayStrt AS DATETIME2(6)),121),'<<NULL>>') AS dWeekdayStrt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dWeekdayEnd AS DATETIME2(6)),121),'<<NULL>>') AS dWeekdayEnd,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSaturdayStrt AS DATETIME2(6)),121),'<<NULL>>') AS dSaturdayStrt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSaturdayEnd AS DATETIME2(6)),121),'<<NULL>>') AS dSaturdayEnd,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSundayStrt AS DATETIME2(6)),121),'<<NULL>>') AS dSundayStrt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSundayEnd AS DATETIME2(6)),121),'<<NULL>>') AS dSundayEnd,
              COALESCE(CAST(iIdentifier AS VARCHAR(100)),'<<NULL>>') AS iIdentifier,
              COALESCE(LTRIM(RTRIM(sIdentifier)),'<<NULL>>') AS sIdentifier,
              CASE WHEN bUseInclusiveTaxation IS NULL THEN '<<NULL>>' WHEN bUseInclusiveTaxation = 1 THEN 'TRUE' WHEN bUseInclusiveTaxation = 0 THEN 'FALSE' END AS bUseInclusiveTaxation,
              COALESCE(CAST(iBusinessType AS VARCHAR(100)),'<<NULL>>') AS iBusinessType,
              COALESCE(CAST(iSiteDataType AS VARCHAR(100)),'<<NULL>>') AS iSiteDataType,
              COALESCE(LTRIM(RTRIM(sTaxNumber)),'<<NULL>>') AS sTaxNumber,
              COALESCE(CAST(iFacilityUsage AS VARCHAR(100)),'<<NULL>>') AS iFacilityUsage,
              COALESCE(CAST(iFacilityOwnership AS VARCHAR(100)),'<<NULL>>') AS iFacilityOwnership,
              COALESCE(CAST(iFacilityMgmt AS VARCHAR(100)),'<<NULL>>') AS iFacilityMgmt,
              COALESCE(CAST(iFacilityLocType AS VARCHAR(100)),'<<NULL>>') AS iFacilityLocType,
              COALESCE(CAST(iMobileBungoRules AS VARCHAR(100)),'<<NULL>>') AS iMobileBungoRules,
              COALESCE(CAST(iOnLinePmtsAllowed AS VARCHAR(100)),'<<NULL>>') AS iOnLinePmtsAllowed,
              COALESCE(CAST(iEdition AS VARCHAR(100)),'<<NULL>>') AS iEdition,
              COALESCE(CAST(iTerminalServices AS VARCHAR(100)),'<<NULL>>') AS iTerminalServices,
              COALESCE(CAST(iDST AS VARCHAR(100)),'<<NULL>>') AS iDST,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              CASE WHEN bArchived IS NULL THEN '<<NULL>>' WHEN bArchived = 1 THEN 'TRUE' WHEN bArchived = 0 THEN 'FALSE' END AS bArchived,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CAST(DivisionID AS VARCHAR(100)),'<<NULL>>') AS DivisionID,
              COALESCE(CAST(iVerboseLogging AS VARCHAR(100)),'<<NULL>>') AS iVerboseLogging,
              COALESCE(CAST(iSiteLinkStoreTier AS VARCHAR(100)),'<<NULL>>') AS iSiteLinkStoreTier,
              COALESCE(LTRIM(RTRIM(sSLBillingRef)),'<<NULL>>') AS sSLBillingRef,
              COALESCE(CAST(iSubscriptionType AS VARCHAR(100)),'<<NULL>>') AS iSubscriptionType
          FROM dbo.Sites;
        target_table_name: Sites
        target: snowflake
        targetcolumn: SiteID
        targetquery: |
          SELECT
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(OwnerID AS VARCHAR(100)),'<<NULL>>') AS OwnerID,
              COALESCE(CAST(LanguageID AS VARCHAR(100)),'<<NULL>>') AS LanguageID,
              COALESCE(TRIM(sLocationCode),'<<NULL>>') AS sLocationCode,
              COALESCE(TRIM(sGlobalSiteNum),'<<NULL>>') AS sGlobalSiteNum,
              COALESCE(CAST(iMobileType AS VARCHAR(100)),'<<NULL>>') AS iMobileType,
              COALESCE(CAST(iRegionalOptions AS VARCHAR(100)),'<<NULL>>') AS iRegionalOptions,
              COALESCE(CAST(iOnLineChargeType AS VARCHAR(100)),'<<NULL>>') AS iOnLineChargeType,
              COALESCE(CAST(iGMTTimeOffset AS VARCHAR(100)),'<<NULL>>') AS iGMTTimeOffset,
              COALESCE(TRIM(sLocationDesc),'<<NULL>>') AS sLocationDesc,
              COALESCE(TRIM(sSiteIDCode),'<<NULL>>') AS sSiteIDCode,
              COALESCE(TRIM(sSiteRegionCode),'<<NULL>>') AS sSiteRegionCode,
              COALESCE(TRIM(sContactName),'<<NULL>>') AS sContactName,
              COALESCE(TRIM(sEmailAddress),'<<NULL>>') AS sEmailAddress,
              COALESCE(TRIM(sSiteName),'<<NULL>>') AS sSiteName,
              COALESCE(TRIM(sSiteAddr1),'<<NULL>>') AS sSiteAddr1,
              COALESCE(TRIM(sSiteAddr2),'<<NULL>>') AS sSiteAddr2,
              COALESCE(TRIM(sSiteCity),'<<NULL>>') AS sSiteCity,
              COALESCE(TRIM(sSiteRegion),'<<NULL>>') AS sSiteRegion,
              COALESCE(TRIM(sSitePostalCode),'<<NULL>>') AS sSitePostalCode,
              COALESCE(TRIM(sSiteCountry),'<<NULL>>') AS sSiteCountry,
              COALESCE(TRIM(sSitePhone),'<<NULL>>') AS sSitePhone,
              COALESCE(TRIM(sSiteFAX),'<<NULL>>') AS sSiteFAX,
              COALESCE(TRIM(sWebSiteURL),'<<NULL>>') AS sWebSiteURL,
              COALESCE(CAST(iFeatMaxUnits AS VARCHAR(100)),'<<NULL>>') AS iFeatMaxUnits,
              CASE WHEN bFeatGate IS NULL THEN '<<NULL>>' WHEN bFeatGate = TRUE THEN 'TRUE' WHEN bFeatGate = FALSE THEN 'FALSE' END AS bFeatGate,
              CASE WHEN bFeatKiosk IS NULL THEN '<<NULL>>' WHEN bFeatKiosk = TRUE THEN 'TRUE' WHEN bFeatKiosk = FALSE THEN 'FALSE' END AS bFeatKiosk,
              CASE WHEN bFeatRevMgmt IS NULL THEN '<<NULL>>' WHEN bFeatRevMgmt = TRUE THEN 'TRUE' WHEN bFeatRevMgmt = FALSE THEN 'FALSE' END AS bFeatRevMgmt,
              CASE WHEN bFeatCreditCards IS NULL THEN '<<NULL>>' WHEN bFeatCreditCards = TRUE THEN 'TRUE' WHEN bFeatCreditCards = FALSE THEN 'FALSE' END AS bFeatCreditCards,
              CASE WHEN bFeatCorpOffice IS NULL THEN '<<NULL>>' WHEN bFeatCorpOffice = TRUE THEN 'TRUE' WHEN bFeatCorpOffice = FALSE THEN 'FALSE' END AS bFeatCorpOffice,
              CASE WHEN bFeatAccounting IS NULL THEN '<<NULL>>' WHEN bFeatAccounting = TRUE THEN 'TRUE' WHEN bFeatAccounting = FALSE THEN 'FALSE' END AS bFeatAccounting,
              CASE WHEN bFeatRecordStorage IS NULL THEN '<<NULL>>' WHEN bFeatRecordStorage = TRUE THEN 'TRUE' WHEN bFeatRecordStorage = FALSE THEN 'FALSE' END AS bFeatRecordStorage,
              CASE WHEN bFeatACH IS NULL THEN '<<NULL>>' WHEN bFeatACH = TRUE THEN 'TRUE' WHEN bFeatACH = FALSE THEN 'FALSE' END AS bFeatACH,
              CASE WHEN bFeatMobileStorage IS NULL THEN '<<NULL>>' WHEN bFeatMobileStorage = TRUE THEN 'TRUE' WHEN bFeatMobileStorage = FALSE THEN 'FALSE' END AS bFeatMobileStorage,
              CASE WHEN bFeatPromoAdvanced IS NULL THEN '<<NULL>>' WHEN bFeatPromoAdvanced = TRUE THEN 'TRUE' WHEN bFeatPromoAdvanced = FALSE THEN 'FALSE' END AS bFeatPromoAdvanced,
              COALESCE(TO_CHAR(dACHStatus,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dACHStatus,
              CASE WHEN bLiteVersion IS NULL THEN '<<NULL>>' WHEN bLiteVersion = TRUE THEN 'TRUE' WHEN bLiteVersion = FALSE THEN 'FALSE' END AS bLiteVersion,
              CASE WHEN bTrial IS NULL THEN '<<NULL>>' WHEN bTrial = TRUE THEN 'TRUE' WHEN bTrial = FALSE THEN 'FALSE' END AS bTrial,
              COALESCE(TO_CHAR(dTrialEnds,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dTrialEnds,
              CASE WHEN bSubscription IS NULL THEN '<<NULL>>' WHEN bSubscription = TRUE THEN 'TRUE' WHEN bSubscription = FALSE THEN 'FALSE' END AS bSubscription,
              COALESCE(TO_CHAR(dSubscriptionEnds,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSubscriptionEnds,
              CASE WHEN bSiteDisabled IS NULL THEN '<<NULL>>' WHEN bSiteDisabled = TRUE THEN 'TRUE' WHEN bSiteDisabled = FALSE THEN 'FALSE' END AS bSiteDisabled,
              COALESCE(TO_CHAR(dSiteDisabled,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSiteDisabled,
              COALESCE(TO_CHAR(dGateUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dGateUpdated,
              COALESCE(TO_CHAR(dOvernightProcess,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dOvernightProcess,
              COALESCE(TO_CHAR(dStartOfDay,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dStartOfDay,
              COALESCE(TRIM(sLegalName),'<<NULL>>') AS sLegalName,
              CASE WHEN bZipCodeData_Use IS NULL THEN '<<NULL>>' WHEN bZipCodeData_Use = TRUE THEN 'TRUE' WHEN bZipCodeData_Use = FALSE THEN 'FALSE' END AS bZipCodeData_Use,
              COALESCE(CAST(dcLongitude AS VARCHAR(100)),'<<NULL>>') AS dcLongitude,
              COALESCE(CAST(dcLatitude AS VARCHAR(100)),'<<NULL>>') AS dcLatitude,
              CASE WHEN bClosedWeekdays IS NULL THEN '<<NULL>>' WHEN bClosedWeekdays = TRUE THEN 'TRUE' WHEN bClosedWeekdays = FALSE THEN 'FALSE' END AS bClosedWeekdays,
              CASE WHEN bClosedSaturday IS NULL THEN '<<NULL>>' WHEN bClosedSaturday = TRUE THEN 'TRUE' WHEN bClosedSaturday = FALSE THEN 'FALSE' END AS bClosedSaturday,
              CASE WHEN bClosedSunday IS NULL THEN '<<NULL>>' WHEN bClosedSunday = TRUE THEN 'TRUE' WHEN bClosedSunday = FALSE THEN 'FALSE' END AS bClosedSunday,
              COALESCE(TO_CHAR(dWeekdayStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dWeekdayStrt,
              COALESCE(TO_CHAR(dWeekdayEnd,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dWeekdayEnd,
              COALESCE(TO_CHAR(dSaturdayStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSaturdayStrt,
              COALESCE(TO_CHAR(dSaturdayEnd,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSaturdayEnd,
              COALESCE(TO_CHAR(dSundayStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSundayStrt,
              COALESCE(TO_CHAR(dSundayEnd,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSundayEnd,
              COALESCE(CAST(iIdentifier AS VARCHAR(100)),'<<NULL>>') AS iIdentifier,
              COALESCE(TRIM(sIdentifier),'<<NULL>>') AS sIdentifier,
              CASE WHEN bUseInclusiveTaxation IS NULL THEN '<<NULL>>' WHEN bUseInclusiveTaxation = TRUE THEN 'TRUE' WHEN bUseInclusiveTaxation = FALSE THEN 'FALSE' END AS bUseInclusiveTaxation,
              COALESCE(CAST(iBusinessType AS VARCHAR(100)),'<<NULL>>') AS iBusinessType,
              COALESCE(CAST(iSiteDataType AS VARCHAR(100)),'<<NULL>>') AS iSiteDataType,
              COALESCE(TRIM(sTaxNumber),'<<NULL>>') AS sTaxNumber,
              COALESCE(CAST(iFacilityUsage AS VARCHAR(100)),'<<NULL>>') AS iFacilityUsage,
              COALESCE(CAST(iFacilityOwnership AS VARCHAR(100)),'<<NULL>>') AS iFacilityOwnership,
              COALESCE(CAST(iFacilityMgmt AS VARCHAR(100)),'<<NULL>>') AS iFacilityMgmt,
              COALESCE(CAST(iFacilityLocType AS VARCHAR(100)),'<<NULL>>') AS iFacilityLocType,
              COALESCE(CAST(iMobileBungoRules AS VARCHAR(100)),'<<NULL>>') AS iMobileBungoRules,
              COALESCE(CAST(iOnLinePmtsAllowed AS VARCHAR(100)),'<<NULL>>') AS iOnLinePmtsAllowed,
              COALESCE(CAST(iEdition AS VARCHAR(100)),'<<NULL>>') AS iEdition,
              COALESCE(CAST(iTerminalServices AS VARCHAR(100)),'<<NULL>>') AS iTerminalServices,
              COALESCE(CAST(iDST AS VARCHAR(100)),'<<NULL>>') AS iDST,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              CASE WHEN bArchived IS NULL THEN '<<NULL>>' WHEN bArchived = TRUE THEN 'TRUE' WHEN bArchived = FALSE THEN 'FALSE' END AS bArchived,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CAST(DivisionID AS VARCHAR(100)),'<<NULL>>') AS DivisionID,
              COALESCE(CAST(iVerboseLogging AS VARCHAR(100)),'<<NULL>>') AS iVerboseLogging,
              COALESCE(CAST(iSiteLinkStoreTier AS VARCHAR(100)),'<<NULL>>') AS iSiteLinkStoreTier,
              COALESCE(TRIM(sSLBillingRef),'<<NULL>>') AS sSLBillingRef,
              COALESCE(CAST(iSubscriptionType AS VARCHAR(100)),'<<NULL>>') AS iSubscriptionType
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Sites
          WHERE _FIVETRAN_ACTIVE = TRUE;
