tables:
  Units:
    validations:
      data_validation:
        source_table_name: Units
        source: mssql
        sourcecolumn: UnitID
        sourcequery: |
          SELECT
              COALESCE(CAST(UnitID AS VARCHAR(100)),'<<NULL>>') AS UnitID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(UnitTypeID AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID,
              COALESCE(CAST(UnitZoneID AS VARCHAR(100)),'<<NULL>>') AS UnitZoneID,
              COALESCE(CAST(MapRAID_Row AS VARCHAR(100)),'<<NULL>>') AS MapRAID_Row,
              COALESCE(CAST(MapRAID_Aisle AS VARCHAR(100)),'<<NULL>>') AS MapRAID_Aisle,
              COALESCE(LTRIM(RTRIM(sTrackingCode)),'<<NULL>>') AS sTrackingCode,
              COALESCE(LTRIM(RTRIM(sRFID)),'<<NULL>>') AS sRFID,
              COALESCE(LTRIM(RTRIM(sGlobalUnitName)),'<<NULL>>') AS sGlobalUnitName,
              COALESCE(LTRIM(RTRIM(TransferredTo_sGlobalSiteNum)),'<<NULL>>') AS TransferredTo_sGlobalSiteNum,
              COALESCE(LTRIM(RTRIM(TransferredFrom_sGlobalSiteNum)),'<<NULL>>') AS TransferredFrom_sGlobalSiteNum,
              COALESCE(CONVERT(VARCHAR(26),CAST(dTransferred AS DATETIME2(6)),121),'<<NULL>>') AS dTransferred,
              COALESCE(CAST(TransferredBy_EmployeeID AS VARCHAR(100)),'<<NULL>>') AS TransferredBy_EmployeeID,
              COALESCE(LTRIM(RTRIM(sUnitName)),'<<NULL>>') AS sUnitName,
              COALESCE(CAST(iWalkThruOrder AS VARCHAR(100)),'<<NULL>>') AS iWalkThruOrder,
              COALESCE(CAST(iFloor AS VARCHAR(100)),'<<NULL>>') AS iFloor,
              COALESCE(CAST(dcWidth AS VARCHAR(100)),'<<NULL>>') AS dcWidth,
              COALESCE(CAST(dcLength AS VARCHAR(100)),'<<NULL>>') AS dcLength,
              COALESCE(CAST(dcMapTop AS VARCHAR(100)),'<<NULL>>') AS dcMapTop,
              COALESCE(CAST(dcMapLeft AS VARCHAR(100)),'<<NULL>>') AS dcMapLeft,
              COALESCE(CAST(dcMapTheta AS VARCHAR(100)),'<<NULL>>') AS dcMapTheta,
              CASE WHEN bMapReversWL IS NULL THEN '<<NULL>>' WHEN bMapReversWL = 1 THEN 'TRUE' WHEN bMapReversWL = 0 THEN 'FALSE' END AS bMapReversWL,
              COALESCE(CAST(dcPushRate AS VARCHAR(100)),'<<NULL>>') AS dcPushRate,
              COALESCE(CAST(dcStdRate AS VARCHAR(100)),'<<NULL>>') AS dcStdRate,
              COALESCE(CAST(dcStdWeeklyRate AS VARCHAR(100)),'<<NULL>>') AS dcStdWeeklyRate,
              COALESCE(CAST(dcStdSecDep AS VARCHAR(100)),'<<NULL>>') AS dcStdSecDep,
              COALESCE(CAST(dcStdLateFee AS VARCHAR(100)),'<<NULL>>') AS dcStdLateFee,
              CASE WHEN bPower IS NULL THEN '<<NULL>>' WHEN bPower = 1 THEN 'TRUE' WHEN bPower = 0 THEN 'FALSE' END AS bPower,
              CASE WHEN bClimate IS NULL THEN '<<NULL>>' WHEN bClimate = 1 THEN 'TRUE' WHEN bClimate = 0 THEN 'FALSE' END AS bClimate,
              CASE WHEN bInside IS NULL THEN '<<NULL>>' WHEN bInside = 1 THEN 'TRUE' WHEN bInside = 0 THEN 'FALSE' END AS bInside,
              CASE WHEN bAlarm IS NULL THEN '<<NULL>>' WHEN bAlarm = 1 THEN 'TRUE' WHEN bAlarm = 0 THEN 'FALSE' END AS bAlarm,
              CASE WHEN bRentable IS NULL THEN '<<NULL>>' WHEN bRentable = 1 THEN 'TRUE' WHEN bRentable = 0 THEN 'FALSE' END AS bRentable,
              CASE WHEN bRented IS NULL THEN '<<NULL>>' WHEN bRented = 1 THEN 'TRUE' WHEN bRented = 0 THEN 'FALSE' END AS bRented,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(LTRIM(RTRIM(sUnitNote)),'<<NULL>>') AS sUnitNote,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUnitNote AS DATETIME2(6)),121),'<<NULL>>') AS dUnitNote,
              COALESCE(LTRIM(RTRIM(sOSSType)),'<<NULL>>') AS sOSSType,
              CASE WHEN bCorporate IS NULL THEN '<<NULL>>' WHEN bCorporate = 1 THEN 'TRUE' WHEN bCorporate = 0 THEN 'FALSE' END AS bCorporate,
              CASE WHEN bMobile IS NULL THEN '<<NULL>>' WHEN bMobile = 1 THEN 'TRUE' WHEN bMobile = 0 THEN 'FALSE' END AS bMobile,
              COALESCE(CONVERT(VARCHAR(26),CAST(dBuilt AS DATETIME2(6)),121),'<<NULL>>') AS dBuilt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dFirstInService AS DATETIME2(6)),121),'<<NULL>>') AS dFirstInService,
              COALESCE(CAST(iMobileStatus AS VARCHAR(100)),'<<NULL>>') AS iMobileStatus,
              CASE WHEN bDamaged IS NULL THEN '<<NULL>>' WHEN bDamaged = 1 THEN 'TRUE' WHEN bDamaged = 0 THEN 'FALSE' END AS bDamaged,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDamaged AS DATETIME2(6)),121),'<<NULL>>') AS dDamaged,
              CASE WHEN bCollapsible IS NULL THEN '<<NULL>>' WHEN bCollapsible = 1 THEN 'TRUE' WHEN bCollapsible = 0 THEN 'FALSE' END AS bCollapsible,
              COALESCE(CAST(EmployeeID_BuiltBy AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_BuiltBy,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CAST(MarketID_Whse AS VARCHAR(100)),'<<NULL>>') AS MarketID_Whse,
              COALESCE(LTRIM(RTRIM(sUnitDesc)),'<<NULL>>') AS sUnitDesc,
              COALESCE(CAST(iEntryLoc AS VARCHAR(100)),'<<NULL>>') AS iEntryLoc,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              CASE WHEN bExcludeFromSqftReports IS NULL THEN '<<NULL>>' WHEN bExcludeFromSqftReports = 1 THEN 'TRUE' WHEN bExcludeFromSqftReports = 0 THEN 'FALSE' END AS bExcludeFromSqftReports,
              CASE WHEN bExcludeFromWebsite IS NULL THEN '<<NULL>>' WHEN bExcludeFromWebsite = 1 THEN 'TRUE' WHEN bExcludeFromWebsite = 0 THEN 'FALSE' END AS bExcludeFromWebsite,
              CASE WHEN bNotReadyToRent IS NULL THEN '<<NULL>>' WHEN bNotReadyToRent = 1 THEN 'TRUE' WHEN bNotReadyToRent = 0 THEN 'FALSE' END AS bNotReadyToRent,
              COALESCE(CAST(dcSchedRateMonthly AS VARCHAR(100)),'<<NULL>>') AS dcSchedRateMonthly,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSchedRateMonthStrt AS DATETIME2(6)),121),'<<NULL>>') AS dSchedRateMonthStrt,
              COALESCE(CAST(dcSchedRateWeekly AS VARCHAR(100)),'<<NULL>>') AS dcSchedRateWeekly,
              COALESCE(CONVERT(VARCHAR(26),CAST(dSchedRateWeeklyStrt AS DATETIME2(6)),121),'<<NULL>>') AS dSchedRateWeeklyStrt,
              COALESCE(CAST(iADA AS VARCHAR(100)),'<<NULL>>') AS iADA,
              COALESCE(CAST(iDoorType AS VARCHAR(100)),'<<NULL>>') AS iDoorType,
              COALESCE(CAST(iVehicleStorageAllowed AS VARCHAR(100)),'<<NULL>>') AS iVehicleStorageAllowed,
              COALESCE(CAST(iDaysVacant AS VARCHAR(100)),'<<NULL>>') AS iDaysVacant,
              COALESCE(CAST(dcWebRate AS VARCHAR(100)),'<<NULL>>') AS dcWebRate,
              COALESCE(CAST(dcWebPushRate AS VARCHAR(100)),'<<NULL>>') AS dcWebPushRate,
              COALESCE(CAST(LockID AS VARCHAR(100)),'<<NULL>>') AS LockID,
              COALESCE(CAST(dcMaxRentalRate AS VARCHAR(100)),'<<NULL>>') AS dcMaxRentalRate
          FROM dbo.Units;
        target_table_name: Units
        target: snowflake
        targetcolumn: UnitID
        targetquery: |
          SELECT
              COALESCE(CAST(UnitID AS VARCHAR(100)),'<<NULL>>') AS UnitID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(UnitTypeID AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID,
              COALESCE(CAST(UnitZoneID AS VARCHAR(100)),'<<NULL>>') AS UnitZoneID,
              COALESCE(CAST(MapRAID_Row AS VARCHAR(100)),'<<NULL>>') AS MapRAID_Row,
              COALESCE(CAST(MapRAID_Aisle AS VARCHAR(100)),'<<NULL>>') AS MapRAID_Aisle,
              COALESCE(TRIM(sTrackingCode),'<<NULL>>') AS sTrackingCode,
              COALESCE(TRIM(sRFID),'<<NULL>>') AS sRFID,
              COALESCE(TRIM(sGlobalUnitName),'<<NULL>>') AS sGlobalUnitName,
              COALESCE(TRIM(TransferredTo_sGlobalSiteNum),'<<NULL>>') AS TransferredTo_sGlobalSiteNum,
              COALESCE(TRIM(TransferredFrom_sGlobalSiteNum),'<<NULL>>') AS TransferredFrom_sGlobalSiteNum,
              COALESCE(TO_CHAR(dTransferred,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dTransferred,
              COALESCE(CAST(TransferredBy_EmployeeID AS VARCHAR(100)),'<<NULL>>') AS TransferredBy_EmployeeID,
              COALESCE(TRIM(sUnitName),'<<NULL>>') AS sUnitName,
              COALESCE(CAST(iWalkThruOrder AS VARCHAR(100)),'<<NULL>>') AS iWalkThruOrder,
              COALESCE(CAST(iFloor AS VARCHAR(100)),'<<NULL>>') AS iFloor,
              COALESCE(CAST(dcWidth AS VARCHAR(100)),'<<NULL>>') AS dcWidth,
              COALESCE(CAST(dcLength AS VARCHAR(100)),'<<NULL>>') AS dcLength,
              COALESCE(CAST(dcMapTop AS VARCHAR(100)),'<<NULL>>') AS dcMapTop,
              COALESCE(CAST(dcMapLeft AS VARCHAR(100)),'<<NULL>>') AS dcMapLeft,
              COALESCE(CAST(dcMapTheta AS VARCHAR(100)),'<<NULL>>') AS dcMapTheta,
              CASE WHEN bMapReversWL IS NULL THEN '<<NULL>>' WHEN bMapReversWL = TRUE THEN 'TRUE' WHEN bMapReversWL = FALSE THEN 'FALSE' END AS bMapReversWL,
              COALESCE(CAST(dcPushRate AS VARCHAR(100)),'<<NULL>>') AS dcPushRate,
              COALESCE(CAST(dcStdRate AS VARCHAR(100)),'<<NULL>>') AS dcStdRate,
              COALESCE(CAST(dcStdWeeklyRate AS VARCHAR(100)),'<<NULL>>') AS dcStdWeeklyRate,
              COALESCE(CAST(dcStdSecDep AS VARCHAR(100)),'<<NULL>>') AS dcStdSecDep,
              COALESCE(CAST(dcStdLateFee AS VARCHAR(100)),'<<NULL>>') AS dcStdLateFee,
              CASE WHEN bPower IS NULL THEN '<<NULL>>' WHEN bPower = TRUE THEN 'TRUE' WHEN bPower = FALSE THEN 'FALSE' END AS bPower,
              CASE WHEN bClimate IS NULL THEN '<<NULL>>' WHEN bClimate = TRUE THEN 'TRUE' WHEN bClimate = FALSE THEN 'FALSE' END AS bClimate,
              CASE WHEN bInside IS NULL THEN '<<NULL>>' WHEN bInside = TRUE THEN 'TRUE' WHEN bInside = FALSE THEN 'FALSE' END AS bInside,
              CASE WHEN bAlarm IS NULL THEN '<<NULL>>' WHEN bAlarm = TRUE THEN 'TRUE' WHEN bAlarm = FALSE THEN 'FALSE' END AS bAlarm,
              CASE WHEN bRentable IS NULL THEN '<<NULL>>' WHEN bRentable = TRUE THEN 'TRUE' WHEN bRentable = FALSE THEN 'FALSE' END AS bRentable,
              CASE WHEN bRented IS NULL THEN '<<NULL>>' WHEN bRented = TRUE THEN 'TRUE' WHEN bRented = FALSE THEN 'FALSE' END AS bRented,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TRIM(sUnitNote),'<<NULL>>') AS sUnitNote,
              COALESCE(TO_CHAR(dUnitNote,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUnitNote,
              COALESCE(TRIM(sOSSType),'<<NULL>>') AS sOSSType,
              CASE WHEN bCorporate IS NULL THEN '<<NULL>>' WHEN bCorporate = TRUE THEN 'TRUE' WHEN bCorporate = FALSE THEN 'FALSE' END AS bCorporate,
              CASE WHEN bMobile IS NULL THEN '<<NULL>>' WHEN bMobile = TRUE THEN 'TRUE' WHEN bMobile = FALSE THEN 'FALSE' END AS bMobile,
              COALESCE(TO_CHAR(dBuilt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dBuilt,
              COALESCE(TO_CHAR(dFirstInService,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dFirstInService,
              COALESCE(CAST(iMobileStatus AS VARCHAR(100)),'<<NULL>>') AS iMobileStatus,
              CASE WHEN bDamaged IS NULL THEN '<<NULL>>' WHEN bDamaged = TRUE THEN 'TRUE' WHEN bDamaged = FALSE THEN 'FALSE' END AS bDamaged,
              COALESCE(TO_CHAR(dDamaged,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDamaged,
              CASE WHEN bCollapsible IS NULL THEN '<<NULL>>' WHEN bCollapsible = TRUE THEN 'TRUE' WHEN bCollapsible = FALSE THEN 'FALSE' END AS bCollapsible,
              COALESCE(CAST(EmployeeID_BuiltBy AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_BuiltBy,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(CAST(MarketID_Whse AS VARCHAR(100)),'<<NULL>>') AS MarketID_Whse,
              COALESCE(TRIM(sUnitDesc),'<<NULL>>') AS sUnitDesc,
              COALESCE(CAST(iEntryLoc AS VARCHAR(100)),'<<NULL>>') AS iEntryLoc,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              CASE WHEN bExcludeFromSqftReports IS NULL THEN '<<NULL>>' WHEN bExcludeFromSqftReports = TRUE THEN 'TRUE' WHEN bExcludeFromSqftReports = FALSE THEN 'FALSE' END AS bExcludeFromSqftReports,
              CASE WHEN bExcludeFromWebsite IS NULL THEN '<<NULL>>' WHEN bExcludeFromWebsite = TRUE THEN 'TRUE' WHEN bExcludeFromWebsite = FALSE THEN 'FALSE' END AS bExcludeFromWebsite,
              CASE WHEN bNotReadyToRent IS NULL THEN '<<NULL>>' WHEN bNotReadyToRent = TRUE THEN 'TRUE' WHEN bNotReadyToRent = FALSE THEN 'FALSE' END AS bNotReadyToRent,
              COALESCE(CAST(dcSchedRateMonthly AS VARCHAR(100)),'<<NULL>>') AS dcSchedRateMonthly,
              COALESCE(TO_CHAR(dSchedRateMonthStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSchedRateMonthStrt,
              COALESCE(CAST(dcSchedRateWeekly AS VARCHAR(100)),'<<NULL>>') AS dcSchedRateWeekly,
              COALESCE(TO_CHAR(dSchedRateWeeklyStrt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dSchedRateWeeklyStrt,
              COALESCE(CAST(iADA AS VARCHAR(100)),'<<NULL>>') AS iADA,
              COALESCE(CAST(iDoorType AS VARCHAR(100)),'<<NULL>>') AS iDoorType,
              COALESCE(CAST(iVehicleStorageAllowed AS VARCHAR(100)),'<<NULL>>') AS iVehicleStorageAllowed,
              COALESCE(CAST(iDaysVacant AS VARCHAR(100)),'<<NULL>>') AS iDaysVacant,
              COALESCE(CAST(dcWebRate AS VARCHAR(100)),'<<NULL>>') AS dcWebRate,
              COALESCE(CAST(dcWebPushRate AS VARCHAR(100)),'<<NULL>>') AS dcWebPushRate,
              COALESCE(CAST(LockID AS VARCHAR(100)),'<<NULL>>') AS LockID,
              COALESCE(CAST(dcMaxRentalRate AS VARCHAR(100)),'<<NULL>>') AS dcMaxRentalRate
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Units
          WHERE _FIVETRAN_ACTIVE = TRUE;
