tables:
  UnitTypes:
    validations:
      data_validation:
        source_table_name: UnitTypes
        source: mssql
        sourcecolumn: UnitTypeID
        sourcequery: |
          SELECT
              COALESCE(CAST(UnitTypeID AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(UnitType_TermID AS VARCHAR(100)),'<<NULL>>') AS UnitType_TermID,
              COALESCE(LTRIM(RTRIM(sDefTypeName)),'<<NULL>>') AS sDefTypeName,
              COALESCE(LTRIM(RTRIM(sTypeName)),'<<NULL>>') AS sTypeName,
              COALESCE(LTRIM(RTRIM(sCategory)),'<<NULL>>') AS sCategory,
              COALESCE(CAST(iDefLeaseNum AS VARCHAR(100)),'<<NULL>>') AS iDefLeaseNum,
              CASE WHEN bExcludeFromAutoTenRateMgmt IS NULL THEN '<<NULL>>' WHEN bExcludeFromAutoTenRateMgmt = 1 THEN 'TRUE' WHEN bExcludeFromAutoTenRateMgmt = 0 THEN 'FALSE' END AS bExcludeFromAutoTenRateMgmt,
              CASE WHEN bExcludeFromRevenueMgmt IS NULL THEN '<<NULL>>' WHEN bExcludeFromRevenueMgmt = 1 THEN 'TRUE' WHEN bExcludeFromRevenueMgmt = 0 THEN 'FALSE' END AS bExcludeFromRevenueMgmt,
              CASE WHEN bChargeTax1 IS NULL THEN '<<NULL>>' WHEN bChargeTax1 = 1 THEN 'TRUE' WHEN bChargeTax1 = 0 THEN 'FALSE' END AS bChargeTax1,
              CASE WHEN bChargeTax2 IS NULL THEN '<<NULL>>' WHEN bChargeTax2 = 1 THEN 'TRUE' WHEN bChargeTax2 = 0 THEN 'FALSE' END AS bChargeTax2,
              CASE WHEN bShowOnReservations IS NULL THEN '<<NULL>>' WHEN bShowOnReservations = 1 THEN 'TRUE' WHEN bShowOnReservations = 0 THEN 'FALSE' END AS bShowOnReservations,
              COALESCE(CAST(BillingFreqID_Default AS VARCHAR(100)),'<<NULL>>') AS BillingFreqID_Default,
              COALESCE(CAST(iInsuranceRequired AS VARCHAR(100)),'<<NULL>>') AS iInsuranceRequired,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent = 0 THEN 'FALSE' END AS bPermanent,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              CASE WHEN bExcludeFromInsurance IS NULL THEN '<<NULL>>' WHEN bExcludeFromInsurance = 1 THEN 'TRUE' WHEN bExcludeFromInsurance = 0 THEN 'FALSE' END AS bExcludeFromInsurance,
              CASE WHEN bExcludeFromOccupancy IS NULL THEN '<<NULL>>' WHEN bExcludeFromOccupancy = 1 THEN 'TRUE' WHEN bExcludeFromOccupancy = 0 THEN 'FALSE' END AS bExcludeFromOccupancy,
              CASE WHEN bExcludeFromArea IS NULL THEN '<<NULL>>' WHEN bExcludeFromArea = 1 THEN 'TRUE' WHEN bExcludeFromArea = 0 THEN 'FALSE' END AS bExcludeFromArea,
              COALESCE(CAST(iVacateNoticeDays AS VARCHAR(100)),'<<NULL>>') AS iVacateNoticeDays,
              COALESCE(CAST(iVacateNoticeGraceDays AS VARCHAR(100)),'<<NULL>>') AS iVacateNoticeGraceDays
          FROM dbo.UnitTypes;
        target_table_name: UnitTypes
        target: snowflake
        targetcolumn: UnitTypeID
        targetquery: |
          SELECT
              COALESCE(CAST(UnitTypeID AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(UnitType_TermID AS VARCHAR(100)),'<<NULL>>') AS UnitType_TermID,
              COALESCE(TRIM(sDefTypeName),'<<NULL>>') AS sDefTypeName,
              COALESCE(TRIM(sTypeName),'<<NULL>>') AS sTypeName,
              COALESCE(TRIM(sCategory),'<<NULL>>') AS sCategory,
              COALESCE(CAST(iDefLeaseNum AS VARCHAR(100)),'<<NULL>>') AS iDefLeaseNum,
              CASE WHEN bExcludeFromAutoTenRateMgmt IS NULL THEN '<<NULL>>' WHEN bExcludeFromAutoTenRateMgmt = TRUE THEN 'TRUE' WHEN bExcludeFromAutoTenRateMgmt = FALSE THEN 'FALSE' END AS bExcludeFromAutoTenRateMgmt,
              CASE WHEN bExcludeFromRevenueMgmt IS NULL THEN '<<NULL>>' WHEN bExcludeFromRevenueMgmt = TRUE THEN 'TRUE' WHEN bExcludeFromRevenueMgmt = FALSE THEN 'FALSE' END AS bExcludeFromRevenueMgmt,
              CASE WHEN bChargeTax1 IS NULL THEN '<<NULL>>' WHEN bChargeTax1 = TRUE THEN 'TRUE' WHEN bChargeTax1 = FALSE THEN 'FALSE' END AS bChargeTax1,
              CASE WHEN bChargeTax2 IS NULL THEN '<<NULL>>' WHEN bChargeTax2 = TRUE THEN 'TRUE' WHEN bChargeTax2 = FALSE THEN 'FALSE' END AS bChargeTax2,
              CASE WHEN bShowOnReservations IS NULL THEN '<<NULL>>' WHEN bShowOnReservations = TRUE THEN 'TRUE' WHEN bShowOnReservations = FALSE THEN 'FALSE' END AS bShowOnReservations,
              COALESCE(CAST(BillingFreqID_Default AS VARCHAR(100)),'<<NULL>>') AS BillingFreqID_Default,
              COALESCE(CAST(iInsuranceRequired AS VARCHAR(100)),'<<NULL>>') AS iInsuranceRequired,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              CASE WHEN bPermanent IS NULL THEN '<<NULL>>' WHEN bPermanent = TRUE THEN 'TRUE' WHEN bPermanent = FALSE THEN 'FALSE' END AS bPermanent,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              CASE WHEN bExcludeFromInsurance IS NULL THEN '<<NULL>>' WHEN bExcludeFromInsurance = TRUE THEN 'TRUE' WHEN bExcludeFromInsurance = FALSE THEN 'FALSE' END AS bExcludeFromInsurance,
              CASE WHEN bExcludeFromOccupancy IS NULL THEN '<<NULL>>' WHEN bExcludeFromOccupancy = TRUE THEN 'TRUE' WHEN bExcludeFromOccupancy = FALSE THEN 'FALSE' END AS bExcludeFromOccupancy,
              CASE WHEN bExcludeFromArea IS NULL THEN '<<NULL>>' WHEN bExcludeFromArea = TRUE THEN 'TRUE' WHEN bExcludeFromArea = FALSE THEN 'FALSE' END AS bExcludeFromArea,
              COALESCE(CAST(iVacateNoticeDays AS VARCHAR(100)),'<<NULL>>') AS iVacateNoticeDays,
              COALESCE(CAST(iVacateNoticeGraceDays AS VARCHAR(100)),'<<NULL>>') AS iVacateNoticeGraceDays
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.UnitTypes
          WHERE _FIVETRAN_ACTIVE = TRUE;
