tables:
  Waitings:
    validations:
      data_validation:
        source_table_name: Waitings
        source: mssql
        sourcecolumn: WaitingID
        sourcequery: |
          SELECT
              COALESCE(CAST(WaitingID AS VARCHAR(100)),'<<NULL>>') AS WaitingID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(TenantID AS VARCHAR(100)),'<<NULL>>') AS TenantID,
              COALESCE(CAST(UnitID1 AS VARCHAR(100)),'<<NULL>>') AS UnitID1,
              COALESCE(CAST(UnitID2 AS VARCHAR(100)),'<<NULL>>') AS UnitID2,
              COALESCE(CAST(UnitID3 AS VARCHAR(100)),'<<NULL>>') AS UnitID3,
              COALESCE(CAST(UnitTypeID AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID,
              COALESCE(CAST(CreditCardID AS VARCHAR(100)),'<<NULL>>') AS CreditCardID,
              COALESCE(CAST(AddressID_To AS VARCHAR(100)),'<<NULL>>') AS AddressID_To,
              COALESCE(CAST(AddressID_From AS VARCHAR(100)),'<<NULL>>') AS AddressID_From,
              COALESCE(CAST(dcArea AS VARCHAR(100)),'<<NULL>>') AS dcArea,
              COALESCE(CONVERT(VARCHAR(26),CAST(dPlaced AS DATETIME2(6)),121),'<<NULL>>') AS dPlaced,
              COALESCE(CONVERT(VARCHAR(26),CAST(dNeeded AS DATETIME2(6)),121),'<<NULL>>') AS dNeeded,
              COALESCE(CAST(dcPaidReserveFee AS VARCHAR(100)),'<<NULL>>') AS dcPaidReserveFee,
              COALESCE(CAST(iReserveFeeReceiptID AS VARCHAR(100)),'<<NULL>>') AS iReserveFeeReceiptID,
              COALESCE(LTRIM(RTRIM(sComment)),'<<NULL>>') AS sComment,
              COALESCE(CAST(iCallType AS VARCHAR(100)),'<<NULL>>') AS iCallType,
              CASE WHEN bFollowup IS NULL THEN '<<NULL>>' WHEN bFollowup = 1 THEN 'TRUE' WHEN bFollowup = 0 THEN 'FALSE' END AS bFollowup,
              COALESCE(CONVERT(VARCHAR(26),CAST(dFollowup AS DATETIME2(6)),121),'<<NULL>>') AS dFollowup,
              COALESCE(CONVERT(VARCHAR(26),CAST(dExpires AS DATETIME2(6)),121),'<<NULL>>') AS dExpires,
              COALESCE(CONVERT(VARCHAR(26),CAST(dDeleted AS DATETIME2(6)),121),'<<NULL>>') AS dDeleted,
              COALESCE(CONVERT(VARCHAR(26),CAST(dUpdated AS DATETIME2(6)),121),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(LTRIM(RTRIM(sSource)),'<<NULL>>') AS sSource,
              COALESCE(CAST(ConcessionID AS VARCHAR(100)),'<<NULL>>') AS ConcessionID,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              COALESCE(CONVERT(VARCHAR(26),CAST(dArchived AS DATETIME2(6)),121),'<<NULL>>') AS dArchived,
              COALESCE(CAST(iGlobalWaitingNum AS VARCHAR(100)),'<<NULL>>') AS iGlobalWaitingNum,
              COALESCE(CAST(iWaitingStatus AS VARCHAR(100)),'<<NULL>>') AS iWaitingStatus,
              COALESCE(CAST(BillingFreqID AS VARCHAR(100)),'<<NULL>>') AS BillingFreqID,
              COALESCE(CAST(UnitTypeID_Quoted AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID_Quoted,
              COALESCE(CAST(iPeriodsNeeded AS VARCHAR(100)),'<<NULL>>') AS iPeriodsNeeded,
              COALESCE(CAST(iUnitsNeeded AS VARCHAR(100)),'<<NULL>>') AS iUnitsNeeded,
              COALESCE(CAST(dcRate_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcRate_Quoted,
              COALESCE(CAST(dcRate_Tax1_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcRate_Tax1_Quoted,
              COALESCE(CAST(dcRate_Tax2_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcRate_Tax2_Quoted,
              COALESCE(CAST(dcLength_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcLength_Quoted,
              COALESCE(CAST(dcWidth_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcWidth_Quoted,
              CASE WHEN bClimate_Quoted IS NULL THEN '<<NULL>>' WHEN bClimate_Quoted = 1 THEN 'TRUE' WHEN bClimate_Quoted = 0 THEN 'FALSE' END AS bClimate_Quoted,
              COALESCE(CAST(CorpUserID AS VARCHAR(100)),'<<NULL>>') AS CorpUserID,
              COALESCE(CAST(CorpUserID_Followup AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_Followup,
              COALESCE(CAST(EmployeeID_Followup AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_Followup,
              COALESCE(CAST(CorpUserID_ConvertedToRsv AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_ConvertedToRsv,
              COALESCE(CAST(EmployeeID_ConvertedToRsv AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_ConvertedToRsv,
              COALESCE(CAST(CorpUserID_ConvertedToMoveIn AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_ConvertedToMoveIn,
              COALESCE(CAST(EmployeeID_ConvertedToMoveIn AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_ConvertedToMoveIn,
              COALESCE(CAST(QTRentalTypeID AS VARCHAR(100)),'<<NULL>>') AS QTRentalTypeID,
              COALESCE(CAST(QTRentalStatusID AS VARCHAR(100)),'<<NULL>>') AS QTRentalStatusID,
              COALESCE(CAST(QTCancellationTypeID AS VARCHAR(100)),'<<NULL>>') AS QTCancellationTypeID,
              COALESCE(LTRIM(RTRIM(sCancellationReason)),'<<NULL>>') AS sCancellationReason,
              COALESCE(CAST(UnitID_Rsvd AS VARCHAR(100)),'<<NULL>>') AS UnitID_Rsvd,
              COALESCE(CAST(UnitID_PriceRef AS VARCHAR(100)),'<<NULL>>') AS UnitID_PriceRef,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCreated AS DATETIME2(6)),121),'<<NULL>>') AS dCreated,
              COALESCE(CONVERT(VARCHAR(26),CAST(dCancelled AS DATETIME2(6)),121),'<<NULL>>') AS dCancelled,
              COALESCE(CONVERT(VARCHAR(26),CAST(dFollowupLast AS DATETIME2(6)),121),'<<NULL>>') AS dFollowupLast,
              COALESCE(CONVERT(VARCHAR(26),CAST(dConverted_ToRsv AS DATETIME2(6)),121),'<<NULL>>') AS dConverted_ToRsv,
              COALESCE(CONVERT(VARCHAR(26),CAST(dConverted_ToMoveIn AS DATETIME2(6)),121),'<<NULL>>') AS dConverted_ToMoveIn,
              COALESCE(CAST(iInquiryType AS VARCHAR(100)),'<<NULL>>') AS iInquiryType,
              CASE WHEN bApptmt IS NULL THEN '<<NULL>>' WHEN bApptmt = 1 THEN 'TRUE' WHEN bApptmt = 0 THEN 'FALSE' END AS bApptmt,
              COALESCE(CONVERT(VARCHAR(26),CAST(dApptmt AS DATETIME2(6)),121),'<<NULL>>') AS dApptmt,
              COALESCE(CAST(CorpUserID_Apptmt AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_Apptmt,
              COALESCE(CAST(EmployeeID_Apptmt AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_Apptmt,
              COALESCE(LTRIM(RTRIM(sTrackingSuffix)),'<<NULL>>') AS sTrackingSuffix,
              COALESCE(LTRIM(RTRIM(sCallerID)),'<<NULL>>') AS sCallerID,
              COALESCE(CAST(dcStdRate AS VARCHAR(100)),'<<NULL>>') AS dcStdRate,
              COALESCE(CAST(dcStdRateTax1 AS VARCHAR(100)),'<<NULL>>') AS dcStdRateTax1,
              COALESCE(CAST(dcStdRateTax2 AS VARCHAR(100)),'<<NULL>>') AS dcStdRateTax2,
              COALESCE(CAST(dcPushRate AS VARCHAR(100)),'<<NULL>>') AS dcPushRate,
              COALESCE(CAST(dcPushRateTax1 AS VARCHAR(100)),'<<NULL>>') AS dcPushRateTax1,
              COALESCE(CAST(dcPushRateTax2 AS VARCHAR(100)),'<<NULL>>') AS dcPushRateTax2,
              COALESCE(LTRIM(RTRIM(sTrackingReferralURL)),'<<NULL>>') AS sTrackingReferralURL,
              COALESCE(LTRIM(RTRIM(sTrackingSearchTerms)),'<<NULL>>') AS sTrackingSearchTerms,
              COALESCE(LTRIM(RTRIM(sTrackingField1)),'<<NULL>>') AS sTrackingField1,
              COALESCE(LTRIM(RTRIM(sTrackingField2)),'<<NULL>>') AS sTrackingField2
          FROM dbo.Waitings;
        target_table_name: Waitings
        target: snowflake
        targetcolumn: WaitingID
        targetquery: |
          SELECT
              COALESCE(CAST(WaitingID AS VARCHAR(100)),'<<NULL>>') AS WaitingID,
              COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>') AS SiteID,
              COALESCE(CAST(EmployeeID AS VARCHAR(100)),'<<NULL>>') AS EmployeeID,
              COALESCE(CAST(LedgerID AS VARCHAR(100)),'<<NULL>>') AS LedgerID,
              COALESCE(CAST(TenantID AS VARCHAR(100)),'<<NULL>>') AS TenantID,
              COALESCE(CAST(UnitID1 AS VARCHAR(100)),'<<NULL>>') AS UnitID1,
              COALESCE(CAST(UnitID2 AS VARCHAR(100)),'<<NULL>>') AS UnitID2,
              COALESCE(CAST(UnitID3 AS VARCHAR(100)),'<<NULL>>') AS UnitID3,
              COALESCE(CAST(UnitTypeID AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID,
              COALESCE(CAST(CreditCardID AS VARCHAR(100)),'<<NULL>>') AS CreditCardID,
              COALESCE(CAST(AddressID_To AS VARCHAR(100)),'<<NULL>>') AS AddressID_To,
              COALESCE(CAST(AddressID_From AS VARCHAR(100)),'<<NULL>>') AS AddressID_From,
              COALESCE(CAST(dcArea AS VARCHAR(100)),'<<NULL>>') AS dcArea,
              COALESCE(TO_CHAR(dPlaced,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dPlaced,
              COALESCE(TO_CHAR(dNeeded,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dNeeded,
              COALESCE(CAST(dcPaidReserveFee AS VARCHAR(100)),'<<NULL>>') AS dcPaidReserveFee,
              COALESCE(CAST(iReserveFeeReceiptID AS VARCHAR(100)),'<<NULL>>') AS iReserveFeeReceiptID,
              COALESCE(TRIM(sComment),'<<NULL>>') AS sComment,
              COALESCE(CAST(iCallType AS VARCHAR(100)),'<<NULL>>') AS iCallType,
              CASE WHEN bFollowup IS NULL THEN '<<NULL>>' WHEN bFollowup = TRUE THEN 'TRUE' WHEN bFollowup = FALSE THEN 'FALSE' END AS bFollowup,
              COALESCE(TO_CHAR(dFollowup,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dFollowup,
              COALESCE(TO_CHAR(dExpires,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dExpires,
              COALESCE(TO_CHAR(dDeleted,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dDeleted,
              COALESCE(TO_CHAR(dUpdated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dUpdated,
              COALESCE(CAST(OldPK AS VARCHAR(100)),'<<NULL>>') AS OldPK,
              COALESCE(TRIM(sSource),'<<NULL>>') AS sSource,
              COALESCE(CAST(ConcessionID AS VARCHAR(100)),'<<NULL>>') AS ConcessionID,
              COALESCE(CAST(iPromoGlobalNum AS VARCHAR(100)),'<<NULL>>') AS iPromoGlobalNum,
              COALESCE(TO_CHAR(dArchived,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dArchived,
              COALESCE(CAST(iGlobalWaitingNum AS VARCHAR(100)),'<<NULL>>') AS iGlobalWaitingNum,
              COALESCE(CAST(iWaitingStatus AS VARCHAR(100)),'<<NULL>>') AS iWaitingStatus,
              COALESCE(CAST(BillingFreqID AS VARCHAR(100)),'<<NULL>>') AS BillingFreqID,
              COALESCE(CAST(UnitTypeID_Quoted AS VARCHAR(100)),'<<NULL>>') AS UnitTypeID_Quoted,
              COALESCE(CAST(iPeriodsNeeded AS VARCHAR(100)),'<<NULL>>') AS iPeriodsNeeded,
              COALESCE(CAST(iUnitsNeeded AS VARCHAR(100)),'<<NULL>>') AS iUnitsNeeded,
              COALESCE(CAST(dcRate_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcRate_Quoted,
              COALESCE(CAST(dcRate_Tax1_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcRate_Tax1_Quoted,
              COALESCE(CAST(dcRate_Tax2_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcRate_Tax2_Quoted,
              COALESCE(CAST(dcLength_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcLength_Quoted,
              COALESCE(CAST(dcWidth_Quoted AS VARCHAR(100)),'<<NULL>>') AS dcWidth_Quoted,
              CASE WHEN bClimate_Quoted IS NULL THEN '<<NULL>>' WHEN bClimate_Quoted = TRUE THEN 'TRUE' WHEN bClimate_Quoted = FALSE THEN 'FALSE' END AS bClimate_Quoted,
              COALESCE(CAST(CorpUserID AS VARCHAR(100)),'<<NULL>>') AS CorpUserID,
              COALESCE(CAST(CorpUserID_Followup AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_Followup,
              COALESCE(CAST(EmployeeID_Followup AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_Followup,
              COALESCE(CAST(CorpUserID_ConvertedToRsv AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_ConvertedToRsv,
              COALESCE(CAST(EmployeeID_ConvertedToRsv AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_ConvertedToRsv,
              COALESCE(CAST(CorpUserID_ConvertedToMoveIn AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_ConvertedToMoveIn,
              COALESCE(CAST(EmployeeID_ConvertedToMoveIn AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_ConvertedToMoveIn,
              COALESCE(CAST(QTRentalTypeID AS VARCHAR(100)),'<<NULL>>') AS QTRentalTypeID,
              COALESCE(CAST(QTRentalStatusID AS VARCHAR(100)),'<<NULL>>') AS QTRentalStatusID,
              COALESCE(CAST(QTCancellationTypeID AS VARCHAR(100)),'<<NULL>>') AS QTCancellationTypeID,
              COALESCE(TRIM(sCancellationReason),'<<NULL>>') AS sCancellationReason,
              COALESCE(CAST(UnitID_Rsvd AS VARCHAR(100)),'<<NULL>>') AS UnitID_Rsvd,
              COALESCE(CAST(UnitID_PriceRef AS VARCHAR(100)),'<<NULL>>') AS UnitID_PriceRef,
              COALESCE(TO_CHAR(dCreated,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCreated,
              COALESCE(TO_CHAR(dCancelled,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dCancelled,
              COALESCE(TO_CHAR(dFollowupLast,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dFollowupLast,
              COALESCE(TO_CHAR(dConverted_ToRsv,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dConverted_ToRsv,
              COALESCE(TO_CHAR(dConverted_ToMoveIn,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dConverted_ToMoveIn,
              COALESCE(CAST(iInquiryType AS VARCHAR(100)),'<<NULL>>') AS iInquiryType,
              CASE WHEN bApptmt IS NULL THEN '<<NULL>>' WHEN bApptmt = TRUE THEN 'TRUE' WHEN bApptmt = FALSE THEN 'FALSE' END AS bApptmt,
              COALESCE(TO_CHAR(dApptmt,'YYYY-MM-DD HH24:MI:SS.FF6'),'<<NULL>>') AS dApptmt,
              COALESCE(CAST(CorpUserID_Apptmt AS VARCHAR(100)),'<<NULL>>') AS CorpUserID_Apptmt,
              COALESCE(CAST(EmployeeID_Apptmt AS VARCHAR(100)),'<<NULL>>') AS EmployeeID_Apptmt,
              COALESCE(TRIM(sTrackingSuffix),'<<NULL>>') AS sTrackingSuffix,
              COALESCE(TRIM(sCallerID),'<<NULL>>') AS sCallerID,
              COALESCE(CAST(dcStdRate AS VARCHAR(100)),'<<NULL>>') AS dcStdRate,
              COALESCE(CAST(dcStdRateTax1 AS VARCHAR(100)),'<<NULL>>') AS dcStdRateTax1,
              COALESCE(CAST(dcStdRateTax2 AS VARCHAR(100)),'<<NULL>>') AS dcStdRateTax2,
              COALESCE(CAST(dcPushRate AS VARCHAR(100)),'<<NULL>>') AS dcPushRate,
              COALESCE(CAST(dcPushRateTax1 AS VARCHAR(100)),'<<NULL>>') AS dcPushRateTax1,
              COALESCE(CAST(dcPushRateTax2 AS VARCHAR(100)),'<<NULL>>') AS dcPushRateTax2,
              COALESCE(TRIM(sTrackingReferralURL),'<<NULL>>') AS sTrackingReferralURL,
              COALESCE(TRIM(sTrackingSearchTerms),'<<NULL>>') AS sTrackingSearchTerms,
              COALESCE(TRIM(sTrackingField1),'<<NULL>>') AS sTrackingField1,
              COALESCE(TRIM(sTrackingField2),'<<NULL>>') AS sTrackingField2
          FROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.Waitings
          WHERE _FIVETRAN_ACTIVE = TRUE;
