tables:
  InsurCoverage:
    validations:
      data_validation:
        source_table_name: InsurCoverage
        source: mssql
        sourcecolumn: InsurCoverageID
        sourcequery: "SELECT\n    COALESCE(CAST(InsurCoverageID AS VARCHAR(100)),'<<NULL>>')\
          \ AS InsurCoverageID,\n    COALESCE(CAST(SiteID AS VARCHAR(100)),'<<NULL>>')\
          \ AS SiteID,\n    COALESCE(CAST(InsurProviderID AS VARCHAR(100)),'<<NULL>>')\
          \ AS InsurProviderID,\n    COALESCE(CAST(CAST(dcCoverage AS DECIMAL(38,4))\
          \ AS VARCHAR(100)),'<<NULL>>') AS dcCoverage,\n    COALESCE(CAST(CAST(dcPremium\
          \ AS DECIMAL(38,4)) AS VARCHAR(100)),'<<NULL>>') AS dcPremium,\n    COALESCE(CAST(CAST(dcPCTheft\
          \ AS DECIMAL(38,4)) AS VARCHAR(100)),'<<NULL>>') AS dcPCTheft,\n    COALESCE(TRIM(sCoverageDesc),'<<NULL>>')\
          \ AS sCoverageDesc,\n    COALESCE(CONVERT(VARCHAR(23),CAST(dDisabled AS\
          \ DATETIME2(3)),121),'<<NULL>>') AS dDisabled,\n    CASE WHEN bPermanent\
          \ IS NULL THEN '<<NULL>>' WHEN bPermanent = 1 THEN 'TRUE' WHEN bPermanent\
          \ = 0 THEN 'FALSE' ELSE '<<NULL>>' END AS bPermanent,\n    COALESCE(CONVERT(VARCHAR(23),CAST(dDeleted\
          \ AS DATETIME2(3)),121),'<<NULL>>') AS dDeleted,\n    COALESCE(CONVERT(VARCHAR(23),CAST(dUpdated\
          \ AS DATETIME2(3)),121),'<<NULL>>') AS dUpdated,\n    COALESCE(CAST(OldPK\
          \ AS VARCHAR(100)),'<<NULL>>') AS OldPK\nFROM dbo.InsurCoverage;"
        target_table_name: InsurCoverage
        target: snowflake
        targetcolumn: InsurCoverageID
        targetquery: "SELECT\n    COALESCE(TO_VARCHAR(t.InsurCoverageID),'<<NULL>>')\
          \ AS InsurCoverageID,\n    COALESCE(TO_VARCHAR(t.SiteID),'<<NULL>>') AS\
          \ SiteID,\n    COALESCE(TO_VARCHAR(t.InsurProviderID),'<<NULL>>') AS InsurProviderID,\n\
          \    COALESCE(TO_VARCHAR(t.dcCoverage),'<<NULL>>') AS dcCoverage,\n    COALESCE(TO_VARCHAR(t.dcPremium),'<<NULL>>')\
          \ AS dcPremium,\n    COALESCE(TO_VARCHAR(t.dcPCTheft),'<<NULL>>') AS dcPCTheft,\n\
          \    COALESCE(TRIM(t.sCoverageDesc),'<<NULL>>') AS sCoverageDesc,\n    COALESCE(TO_CHAR(t.dDisabled,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS dDisabled,\n    CASE WHEN t.bPermanent\
          \ IS NULL THEN '<<NULL>>' WHEN t.bPermanent = TRUE THEN 'TRUE' WHEN t.bPermanent\
          \ = FALSE THEN 'FALSE' ELSE '<<NULL>>' END AS bPermanent,\n    COALESCE(TO_CHAR(t.dDeleted,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS dDeleted,\n    COALESCE(TO_CHAR(t.dUpdated,'YYYY-MM-DD\
          \ HH24:MI:SS.FF3'),'<<NULL>>') AS dUpdated,\n    COALESCE(TO_VARCHAR(t.OldPK),'<<NULL>>')\
          \ AS OldPK\nFROM DEV_SITELINK_BRONZE.AWSDEV_DEVT5000_DBO.InsurCoverage t\n\
          WHERE t._FIVETRAN_ACTIVE = TRUE"
